---
permalink: protect-scsql/concept_snapcenter_plug_in_for_microsoft_sql_server_features.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for Microsoft SQL Server 
summary: 'Il plug-in per SQL Server si integra con Microsoft SQL Server sull"host Windows e con la tecnologia NetApp Snapshot sul sistema di storage.  Per lavorare con il plug-in per SQL Server, utilizzare l"interfaccia SnapCenter .' 
---
= Funzionalità del plug-in SnapCenter per Microsoft SQL Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il plug-in per SQL Server si integra con Microsoft SQL Server sull'host Windows e con la tecnologia NetApp Snapshot sul sistema di storage.  Per lavorare con il plug-in per SQL Server, utilizzare l'interfaccia SnapCenter .

Il plug-in per SQL Server include le seguenti funzionalità principali:

* *Interfaccia utente grafica unificata basata su SnapCenter*
+
L'interfaccia SnapCenter garantisce standardizzazione e coerenza tra plug-in e ambienti.  L'interfaccia SnapCenter consente di completare processi di backup e ripristino coerenti su tutti i plug-in, utilizzare report centralizzati, utilizzare viste dashboard immediate, impostare il controllo degli accessi basato sui ruoli (RBAC) e monitorare i processi su tutti i plug-in.  SnapCenter offre inoltre una pianificazione centralizzata e una gestione delle policy per supportare le operazioni di backup e clonazione.

* *Amministrazione centrale automatizzata*
+
È possibile pianificare backup di routine di SQL Server, configurare la conservazione dei backup basata su criteri e impostare operazioni di ripristino puntuali e aggiornate al minuto.  È anche possibile monitorare in modo proattivo l'ambiente SQL Server configurando SnapCenter per l'invio di avvisi tramite e-mail.

* *Tecnologia NetApp Snapshot non disruptiva*
+
Il plug-in per SQL Server utilizza la tecnologia NetApp Snapshot con il plug-in NetApp SnapCenter per Microsoft Windows.  Ciò consente di eseguire il backup dei database in pochi secondi e di ripristinarli rapidamente senza dover disconnettere SQL Server.  Gli snapshot occupano uno spazio di archiviazione minimo.



Oltre a queste funzionalità principali, il plug-in per SQL Server offre i seguenti vantaggi:

* Supporto per il flusso di lavoro di backup, ripristino, clonazione e verifica
* Sicurezza supportata da RBAC e delega centralizzata dei ruoli
* Creazione di copie point-in-time e a basso consumo di spazio dei database di produzione per test o estrazione dati utilizzando la tecnologia NetApp FlexClone
+
È richiesta una licenza FlexClone sul sistema di archiviazione che contiene il clone.

* Verifica del backup automatizzata e non distruttiva
* Possibilità di eseguire più backup contemporaneamente su più server
* Cmdlet di PowerShell per la creazione di script per operazioni di backup, verifica, ripristino e clonazione
* Supporto per gruppi di disponibilità AlwaysOn (AG) in SQL Server per accelerare le operazioni di configurazione, backup e ripristino degli AG
* Database in memoria e Buffer Pool Extension (BPE) come parte di SQL Server 2014
* Supporto per il backup di LUN e dischi di macchine virtuali (VMDK)
* Supporto per infrastrutture fisiche e virtualizzate
* Supporto per iSCSI, Fibre Channel, FCoE, raw device mapping (RDM) e VMDK su NFS e VMFS
+

NOTE: I volumi NAS dovrebbero avere una politica di esportazione predefinita nella macchina virtuale di archiviazione (SVM).

* Supporto per FileStream e file group nei database autonomi di SQL Server.
* Supporto per la memoria non volatile express (NVMe) su Windows Server 2022
+
** Flussi di lavoro di backup, ripristino, clonazione e verifica su layout VMDK creati su NVMe tramite TCP/IP.
** Supporta il firmware NVMe versione 1.3 a partire dall'aggiornamento 2 di ESX 8.0 e richiede l'hardware virtuale versione 21.
** Windows Server Failover Clustering (WSFC) non è supportato per le applicazioni su VMDK su NVMe su TCP/IP.


* Supporta la sincronizzazione attiva SnapMirror (inizialmente rilasciata come SnapMirror Business Continuity [SM-BC]) che consente ai servizi aziendali di continuare a funzionare anche in caso di guasto completo del sito, supportando il failover delle applicazioni in modo trasparente utilizzando una copia secondaria.  Per attivare un failover con SnapMirror ActiveSync non è necessario alcun intervento manuale né scripting aggiuntivo.

