---
permalink: protect-scsql/concept_how_long_to_retain_transaction_log_backups_on_the_source_storage_system.html 
sidebar: sidebar 
keywords: retain transaction log backups 
summary: Il plug-in SnapCenter per Microsoft SQL Server necessita di backup del registro delle transazioni per eseguire operazioni di ripristino aggiornate al minuto, che ripristinano il database a un orario compreso tra due backup completi. 
---
= Per quanto tempo conservare i backup del registro delle transazioni sul sistema di archiviazione di origine
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il plug-in SnapCenter per Microsoft SQL Server necessita di backup del registro delle transazioni per eseguire operazioni di ripristino aggiornate al minuto, che ripristinano il database a un orario compreso tra due backup completi.

Ad esempio, se Plug-in per SQL Server ha eseguito un backup completo alle 8:00 e un altro backup completo alle 17:00, potrebbe utilizzare l'ultimo backup del registro delle transazioni per ripristinare il database a un orario qualsiasi compreso tra le 8:00 e le 17:00. Se i registri delle transazioni non sono disponibili, Plug-in per SQL Server può eseguire solo operazioni di ripristino temporizzato, che ripristinano un database all'orario in cui Plug-in per SQL Server ha completato un backup completo.

In genere, sono necessarie operazioni di ripristino aggiornate solo per uno o due giorni.  Per impostazione predefinita, SnapCenter conserva un minimo di due giorni.
