---
permalink: protect-scsql/concept_when_to_schedule_verification_jobs.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for Microsoft SQL Server 
summary: 'Sebbene SnapCenter possa verificare i backup subito dopo averli creati, questa operazione può aumentare significativamente il tempo necessario per completare il processo di backup e richiede molte risorse.  Pertanto, è quasi sempre meglio programmare la verifica in un lavoro separato, da svolgere in un secondo momento.  Ad esempio, se esegui il backup di un database alle 17:00 ogni giorno, potresti pianificare la verifica in modo che avvenga un"ora dopo, alle 18:00.' 
---
= Quando pianificare i lavori di verifica
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sebbene SnapCenter possa verificare i backup subito dopo averli creati, questa operazione può aumentare significativamente il tempo necessario per completare il processo di backup e richiede molte risorse.  Pertanto, è quasi sempre meglio programmare la verifica in un lavoro separato, da svolgere in un secondo momento.  Ad esempio, se esegui il backup di un database alle 17:00 ogni giorno, potresti pianificare la verifica in modo che avvenga un'ora dopo, alle 18:00.

Per lo stesso motivo, solitamente non è necessario eseguire la verifica del backup ogni volta che si esegue un backup.  Di solito, per garantire l'integrità del backup è sufficiente eseguire la verifica a intervalli regolari ma meno frequenti.  Un singolo processo di verifica può verificare più backup contemporaneamente.
