---
permalink: protect-scsql/reference_prerequisites_to_adding_hosts_and_installing_snapcenter_plug_in_for_microsoft_sql_server.html 
sidebar: sidebar 
keywords: credentials 
summary: Prima di aggiungere un host e installare i pacchetti plug-in, è necessario soddisfare tutti i requisiti. 
---
= Prerequisiti per aggiungere host e installare il plug-in SnapCenter per Microsoft SQL Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di aggiungere un host e installare i pacchetti plug-in, è necessario soddisfare tutti i requisiti.

* Se si utilizza iSCSI, il servizio iSCSI deve essere in esecuzione.
* È necessario disporre di un utente con privilegi di amministratore locale e autorizzazioni di accesso locale sull'host remoto.
* Se si gestiscono i nodi del cluster in SnapCenter, è necessario disporre di un utente con privilegi amministrativi per tutti i nodi del cluster.
* È necessario disporre di un utente con autorizzazioni di amministratore di sistema su SQL Server.
+
Il plug-in SnapCenter per Microsoft SQL Server utilizza Microsoft VDI Framework, che richiede l'accesso come amministratore di sistema.

+
https://mskb.pkisolutions.com/kb/2926557["Articolo del supporto Microsoft 2926557: le operazioni di backup e ripristino di SQL Server VDI richiedono privilegi di amministratore di sistema"^]

* Quando si installa un plug-in su un host Windows, se si specifica una credenziale non integrata o se l'utente appartiene a un utente del gruppo di lavoro locale, è necessario disabilitare UAC sull'host.
* Se SnapManager per Microsoft SQL Server è installato, è necessario aver arrestato o disabilitato il servizio e le pianificazioni.
+
Se si prevede di importare processi di backup o clonazione in SnapCenter, non disinstallare SnapManager per Microsoft SQL Server.

* L'host deve essere risolvibile nel nome di dominio completo (FQDN) dal server.
+
Se il file hosts viene modificato per renderlo risolvibile e se sia il nome breve che l'FQDN sono specificati nel file hosts, creare una voce nel file hosts SnapCenter nel seguente formato: <indirizzo_ip> <fqdn_host> <nome_host>


