---
permalink: protect-scsql/task_set_up_credentials_for_snapcenter_plug_ins_package_for_windows.html 
sidebar: sidebar 
keywords: credentials 
summary: 'SnapCenter utilizza le credenziali per autenticare gli utenti per le operazioni SnapCenter .  È necessario creare credenziali per l"installazione dei plug-in SnapCenter e credenziali aggiuntive per eseguire operazioni di protezione dei dati su database o file system Windows.' 
---
= Imposta le credenziali per il pacchetto plug-in SnapCenter per Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter utilizza le credenziali per autenticare gli utenti per le operazioni SnapCenter .  È necessario creare credenziali per l'installazione dei plug-in SnapCenter e credenziali aggiuntive per eseguire operazioni di protezione dei dati su database o file system Windows.

.Prima di iniziare
* Prima di installare i plug-in è necessario impostare le credenziali di Windows.
* È necessario impostare le credenziali con privilegi di amministratore, inclusi i diritti di amministratore sull'host remoto.
* Autenticazione SQL su host Windows
+
Dopo aver installato i plug-in, è necessario impostare le credenziali SQL.

+
Se si distribuisce il plug-in SnapCenter per Microsoft SQL Server, è necessario impostare le credenziali SQL dopo aver installato i plug-in.  Impostare le credenziali per un utente con autorizzazioni di amministratore di sistema di SQL Server.

+
Il metodo di autenticazione SQL esegue l'autenticazione su un'istanza di SQL Server.  Ciò significa che un'istanza di SQL Server deve essere individuata in SnapCenter.  Pertanto, prima di aggiungere una credenziale SQL, è necessario aggiungere un host, installare pacchetti plug-in e aggiornare le risorse.  Per eseguire operazioni quali la pianificazione o l'individuazione di risorse è necessaria l'autenticazione di SQL Server.



.Passi
. Nel riquadro di navigazione a sinistra, fare clic su *Impostazioni*.
. Nella pagina Impostazioni, fare clic su *Credenziali*.
. Fare clic su *Nuovo*.
. Nella pagina Credenziali, specificare le informazioni richieste per la configurazione delle credenziali:
+
|===
| Per questo campo... | Fai questo... 


 a| 
Nome della credenziale
 a| 
Inserisci un nome per la credenziale.



 a| 
Nome utente/Password
 a| 
Immettere il nome utente e la password da utilizzare per l'autenticazione.

** Amministratore di dominio
+
Specificare l'amministratore di dominio sul sistema su cui si sta installando il plug-in SnapCenter . I formati validi per il campo Nome utente sono:

+
*** `NetBIOS\UserName`
*** `Domain FQDN\UserName`


** Amministratore locale (solo per gruppi di lavoro)
+
Per i sistemi che appartengono a un gruppo di lavoro, specificare l'amministratore locale predefinito sul sistema su cui si sta installando il plug-in SnapCenter . È possibile specificare un account utente locale appartenente al gruppo degli amministratori locali se l'account utente dispone di privilegi elevati o se la funzionalità di controllo degli accessi utente è disabilitata sul sistema host.  Il formato valido per il campo Nome utente è: `UserName`

+
Non utilizzare virgolette doppie (") o apici inversi (`) nelle password.  Non dovresti usare insieme i simboli minore (<) e punto esclamativo (!) nelle password.  Ad esempio, lessthan<!10, lessthan10<!, backtick`12.





 a| 
Modalità di autenticazione
 a| 
Seleziona la modalità di autenticazione che desideri utilizzare.  Se si seleziona la modalità di autenticazione SQL, è necessario specificare anche l'istanza del server SQL e l'host in cui si trova l'istanza SQL.

|===
. Fare clic su *OK*.


Dopo aver completato la configurazione delle credenziali, potresti voler assegnare la manutenzione delle credenziali a un utente o a un gruppo di utenti nella pagina Utente e accesso.
