---
permalink: protect-scsql/task_disaster_recovery_scsql.html 
sidebar: sidebar 
keywords: disaster recovery 
summary: Quando il plug-in SnapCenter per SQL Server non è attivo, eseguire manualmente i seguenti passaggi per ripristinarlo. 
---
= Ripristino di emergenza del plug-in SnapCenter per SQL Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando il plug-in SnapCenter per SQL Server non è attivo, utilizzare i passaggi seguenti per passare a un host SQL diverso e ripristinare i dati.

.Prima di iniziare
* L'host secondario deve avere lo stesso sistema operativo, la stessa applicazione e lo stesso nome host dell'host primario.
* Inviare il plug-in SnapCenter per SQL Server a un host alternativo utilizzando la pagina *Aggiungi host* o *Modifica host*. Vedere link:https://docs.netapp.com/us-en/snapcenter/admin/concept_manage_hosts.html["Gestisci gli host"] per maggiori informazioni.


.Passi
. Selezionare l'host dalla pagina *Host* per modificare e installare il plug-in SnapCenter per SQL Server.
. (Facoltativo) Sostituire il plug-in SnapCenter per i file di configurazione di SQL Server dal backup di disaster recovery (DR) al nuovo computer.
. Importare le pianificazioni Windows e SQL dalla cartella del plug-in SnapCenter per SQL Server dal backup DR.


.Informazioni correlate
Vedi illink:https://www.youtube.com/watch?v=_8NG-tTGy8k&list=PLdXI3bZJEw7nofM6lN44eOe4aOSoryckg["API di disaster recovery"^] video.
