---
permalink: protect-scsql/task_create_backup_policies_for_sql_server_databases.html 
sidebar: sidebar 
keywords: backup policy 
summary: È possibile creare un criterio di backup per la risorsa o il gruppo di risorse prima di utilizzare SnapCenter per eseguire il backup delle risorse di SQL Server oppure è possibile creare un criterio di backup al momento della creazione di un gruppo di risorse o del backup di una singola risorsa. 
---
= Creare criteri di backup per i database di SQL Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile creare un criterio di backup per la risorsa o il gruppo di risorse prima di utilizzare SnapCenter per eseguire il backup delle risorse di SQL Server oppure è possibile creare un criterio di backup al momento della creazione di un gruppo di risorse o del backup di una singola risorsa.

.Prima di iniziare
* Devi aver definito la tua strategia di protezione dei dati.
* È necessario prepararsi alla protezione dei dati completando attività quali l'installazione SnapCenter, l'aggiunta di host, l'identificazione delle risorse e la creazione di connessioni al sistema di archiviazione.
* È necessario aver configurato la directory del registro host per il backup del registro.
* È necessario aver aggiornato (rilevato) le risorse di SQL Server.
* Se si replicano gli snapshot su un mirror o un vault, l'amministratore SnapCenter deve aver assegnato le macchine virtuali di archiviazione (SVM) sia per i volumi di origine che per quelli di destinazione.
+
Per informazioni su come gli amministratori assegnano le risorse agli utenti, consultare le informazioni sull'installazione SnapCenter .

* Se si desidera eseguire gli script di PowerShell in prescript e postscript, è necessario impostare il valore del parametro usePowershellProcessforScripts su true nel file web.config.
+
Il valore predefinito è falso.

* Esaminare i prerequisiti e le limitazioni specifici SnapMirror ActiveSync. Per informazioni, fare riferimento https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes["Limiti degli oggetti per la sincronizzazione attiva SnapMirror"] .


.Informazioni su questo compito
* Una policy di backup è un insieme di regole che regolano il modo in cui vengono gestiti e conservati i backup, nonché la frequenza con cui viene eseguito il backup della risorsa o del gruppo di risorse.  Inoltre, è possibile specificare le impostazioni di replica e script.  Specificare le opzioni in un criterio consente di risparmiare tempo quando si desidera riutilizzare il criterio per un altro gruppo di risorse.
+
SCRIPTS_PATH viene definito utilizzando la chiave PredefinedWindowsScriptsDirectory che si trova nel file SMCoreServiceHost.exe.Config dell'host del plug-in.

+
Se necessario, è possibile modificare questo percorso e riavviare il servizio SMcore.  Per motivi di sicurezza, si consiglia di utilizzare il percorso predefinito.

+
Il valore della chiave può essere visualizzato da Swagger tramite l'API: API /4.7/configsettings

+
È possibile utilizzare l'API GET per visualizzare il valore della chiave.  L'API SET non è supportata.

* SnapLock
+
** Se è selezionata l'opzione "Conserva le copie di backup per un numero specifico di giorni", il periodo di conservazione SnapLock deve essere inferiore o uguale ai giorni di conservazione indicati.
+
Specificando un periodo di blocco degli snapshot si impedisce l'eliminazione degli snapshot fino alla scadenza del periodo di conservazione. Ciò potrebbe comportare la conservazione di un numero di snapshot maggiore rispetto al conteggio specificato nella policy.

+
Per ONTAP 9.12.1 e versioni precedenti, i cloni creati dagli SnapLock Vault Snapshot come parte del ripristino erediteranno il tempo di scadenza SnapLock Vault. L'amministratore dell'archiviazione deve pulire manualmente i cloni dopo la scadenza SnapLock .







== Passaggio 1: creare il nome della policy

. Nel riquadro di navigazione a sinistra, seleziona *Impostazioni*.
. Nella pagina Impostazioni, seleziona *Criteri*.
. Seleziona *Nuovo*.
. Nella pagina *Nome*, inserisci il nome e i dettagli della polizza.




== Passaggio 2: configurare le opzioni dei criteri

. Nella pagina Tipo di policy, procedere come segue:
+
.. Seleziona il tipo di archiviazione.
.. Seleziona l'ambito della tua policy.
+
[role="tabbed-block"]
====
.Backup completo e backup del registro
--
Eseguire il backup dei file del database e dei registri delle transazioni e troncare i registri delle transazioni.

... Selezionare *Backup completo e Backup del registro*.
... Immettere il numero massimo di database di cui eseguire il backup per ogni snapshot.
+

NOTE: È necessario aumentare questo valore se si desidera eseguire più operazioni di backup contemporaneamente.



--
.Backup completo
--
Eseguire il backup dei file del database.

... Selezionare *Backup completo*.
... Immettere il numero massimo di database di cui eseguire il backup per ogni snapshot.  Il valore predefinito è 100
+

NOTE: È necessario aumentare questo valore se si desidera eseguire più operazioni di backup contemporaneamente.



--
.Backup del registro
--
... Eseguire il backup dei registri delle transazioni.
... Selezionare *Backup del registro*.


--
.Copia solo backup
--
... Se si esegue il backup delle risorse utilizzando un'altra applicazione di backup, selezionare *Copia solo backup*.


Mantenere intatti i registri delle transazioni consente a qualsiasi applicazione di backup di ripristinare i database.  In genere non dovresti usare l'opzione "solo copia" in nessun'altra circostanza.


NOTE: Microsoft SQL non supporta l'opzione *Backup solo copia* insieme all'opzione *Backup completo e Backup del registro* per l'archiviazione secondaria.

--
====






== Passaggio 3: configurare le impostazioni del gruppo di disponibilità

. Nella sezione Impostazioni gruppo di disponibilità, eseguire le seguenti azioni:
+
.. Backup solo sulla replica di backup preferita.
+
Selezionare questa opzione per eseguire il backup solo sulla replica di backup preferita.  La replica di backup preferita viene decisa dalle preferenze di backup configurate per l'AG in SQL Server.

.. Selezionare le repliche per il backup.
+
Selezionare la replica AG primaria o la replica AG secondaria per il backup.

.. Seleziona la priorità di backup (priorità di backup minima e massima)
+
Specificare un numero minimo e un numero massimo di priorità di backup che decidano la replica AG per il backup.  Ad esempio, è possibile avere una priorità minima di 10 e una priorità massima di 50.  In questo caso, vengono prese in considerazione per il backup tutte le repliche AG con priorità superiore a 10 e inferiore a 50.

+
Per impostazione predefinita, la priorità minima è 1 e quella massima è 100.



+

NOTE: Nelle configurazioni cluster, i backup vengono conservati in ciascun nodo del cluster in base alle impostazioni di conservazione definite nella policy.  Se cambia il nodo proprietario dell'AG, i backup vengono eseguiti in base alle impostazioni di conservazione e verranno conservati i backup del nodo proprietario precedente.  La conservazione per AG è applicabile solo a livello di nodo.





== Passaggio 4: configurare le impostazioni di snapshot e replica

. Nella pagina Snapshot e replica, procedere come segue:
+
.. Specificare il tipo di pianificazione selezionando *Su richiesta*, *Ora*, *Giornaliera*, *Settimanale* o *Mensile*.
+
È possibile selezionare un solo tipo di pianificazione per una policy.

+

NOTE: È possibile specificare la pianificazione (data di inizio, data di fine e frequenza) per l'operazione di backup durante la creazione di un gruppo di risorse.  Ciò consente di creare gruppi di risorse che condividono la stessa policy e la stessa frequenza di backup, ma consente di assegnare pianificazioni di backup diverse a ciascuna policy.

+

NOTE: Se hai programmato per le 2:00, la pianificazione non verrà attivata durante l'ora legale (DST).







== Passaggio 5: configura le impostazioni di conservazione aggiornate

. Nella sezione Impostazioni di conservazione aggiornate, a seconda del tipo di backup selezionato nella pagina Tipo di backup, eseguire una o più delle seguenti azioni:


[role="tabbed-block"]
====
.Numero specifico di copie
--
Conserva solo un numero specifico di snapshot.

. Selezionare l'opzione *Mantieni i backup del registro applicabili agli ultimi <numero> giorni* e specificare il numero di giorni da conservare.  Se ti avvicini a questo limite, potresti voler eliminare le copie più vecchie.


--
.Numero specifico di giorni
--
Conservare le copie di backup per un numero specifico di giorni.

. Selezionare l'opzione *Mantieni i backup del registro applicabili agli ultimi <numero> giorni di backup completi* e specificare il numero di giorni per cui conservare le copie di backup del registro.


--
====


== Passaggio 6: configurare le impostazioni di Snapshot

. Per le impostazioni di conservazione del backup completo, eseguire le seguenti azioni:
+
.. Specificare il numero totale di snapshot da conservare
+
... Per specificare il numero di snapshot da conservare, selezionare *Copie da conservare*.
... Se il numero di snapshot supera il numero specificato, gli snapshot vengono eliminati partendo dalle copie più vecchie.
+

IMPORTANT: Per impostazione predefinita, il valore del conteggio di conservazione è impostato su 2.  Se si imposta il conteggio di conservazione su 1, l'operazione di conservazione potrebbe non riuscire perché il primo snapshot è lo snapshot di riferimento per la relazione SnapVault finché uno snapshot più recente non viene replicato sulla destinazione.

+

NOTE: Il valore massimo di ritenzione è 1018. I backup non riusciranno se la conservazione è impostata su un valore superiore a quello supportato dalla versione di NetApp ONTAP sottostante.







. Periodo di tempo per conservare gli snapshot
+
.. Se si desidera specificare il numero di giorni per cui conservare gli snapshot prima di eliminarli, selezionare *Conserva copie per*.


. Selezionare *Periodo di blocco della copia snapshot* e specificare la durata in giorni, mesi o anni.
+
Il periodo di conservazione di Snaplock dovrebbe essere inferiore a 100 anni.

. Selezionare un'etichetta di criterio.
+

NOTE: È possibile assegnare etichette SnapMirror agli snapshot primari per la replica remota, consentendo agli snapshot primari di trasferire l'operazione di replica degli snapshot da SnapCenter ai sistemi secondari ONTAP . Questa operazione può essere eseguita senza abilitare l'opzione SnapMirror o SnapVault nella pagina dei criteri.





== Passaggio 7: configurare le opzioni di replicazione secondaria

. Nella sezione Seleziona opzioni di replicazione secondaria, seleziona una o entrambe le seguenti opzioni di replicazione secondaria:


[role="tabbed-block"]
====
.Aggiorna SnapMirror
--
Aggiorna SnapMirror dopo aver creato una copia Snapshot locale.

. Selezionare questa opzione per creare copie mirror dei set di backup su un altro volume (SnapMirror).
+
Questa opzione dovrebbe essere abilitata per la sincronizzazione attiva SnapMirror .

+
Durante la replicazione secondaria, il tempo di scadenza SnapLock carica il tempo di scadenza SnapLock primario.  Facendo clic sul pulsante *Aggiorna* nella pagina Topologia, vengono aggiornati i tempi di scadenza SnapLock secondari e primari recuperati da ONTAP.

+
Vedere link:../protect-scsql/task_view_sql_server_backups_and_clones_in_the_topology_page.html["Visualizza i backup e i cloni di SQL Server nella pagina Topologia"] .



--
.Aggiorna SnapVault
--
Aggiorna SnapVault dopo aver creato una copia Snapshot.

. Selezionare questa opzione per eseguire la replica del backup da disco a disco.
+
Durante la replicazione secondaria, il tempo di scadenza SnapLock carica il tempo di scadenza SnapLock primario.  Facendo clic sul pulsante *Aggiorna* nella pagina Topologia, vengono aggiornati i tempi di scadenza SnapLock secondari e primari recuperati da ONTAP.

+
Quando SnapLock è configurato solo sul secondario da ONTAP noto come SnapLock Vault, facendo clic sul pulsante *Aggiorna* nella pagina Topologia si aggiorna il periodo di blocco sul secondario recuperato da ONTAP.

+
Per maggiori informazioni su SnapLock Vault vedere https://docs.netapp.com/us-en/ontap/snaplock/commit-snapshot-copies-worm-concept.html["Eseguire il commit delle copie Snapshot su WORM in una destinazione vault"]

+
Vedere link:../protect-scsql/task_view_sql_server_backups_and_clones_in_the_topology_page.html["Visualizza i backup e i cloni di SQL Server nella pagina Topologia"] .



--
.Errore conteggio tentativi
--
. Immettere il numero di tentativi di replica che devono essere eseguiti prima che il processo si interrompa.


--
====


== Passaggio 8: configurare le impostazioni dello script

. Nella pagina Script, immettere il percorso e gli argomenti del prescript o del postscript che devono essere eseguiti rispettivamente prima o dopo l'operazione di backup.
+
Ad esempio, è possibile eseguire uno script per aggiornare le trap SNMP, automatizzare gli avvisi e inviare i registri.

+

NOTE: Il percorso prescripts o postscripts non deve includere unità o condivisioni.  Il percorso dovrebbe essere relativo a SCRIPTS_PATH.

+

NOTE: È necessario configurare il criterio di conservazione SnapMirror in ONTAP in modo che l'archiviazione secondaria non raggiunga il limite massimo di snapshot.





== Passaggio 9: configurare le impostazioni di verifica

Nella pagina Verifica, procedere come segue:

. Nella sezione Esegui verifica per le seguenti pianificazioni di backup, seleziona la frequenza della pianificazione.
. Nella sezione Opzioni di controllo della coerenza del database, eseguire le seguenti azioni:
+
.. Limitare la struttura di integrità alla struttura fisica del database (PHYSICAL_ONLY)
+
... Selezionare *Limita la struttura di integrità alla struttura fisica del database (PHYSICAL_ONLY)* per limitare il controllo di integrità alla struttura fisica del database e per rilevare pagine danneggiate, errori di checksum e guasti hardware comuni che hanno un impatto sul database.


.. Sopprimi tutti i messaggi informativi (NO INFOMSGS)
+
... Selezionare *Sopprimi tutti i messaggi informativi (NO_INFOMSGS)* per sopprimere tutti i messaggi informativi.  Selezionato per impostazione predefinita.


.. Visualizza tutti i messaggi di errore segnalati per oggetto (ALL_ERRORMSGS)
+
... Selezionare *Visualizza tutti i messaggi di errore segnalati per oggetto (ALL_ERRORMSGS)* per visualizzare tutti gli errori segnalati per oggetto.


.. Non controllare gli indici non cluster (NOINDEX)
+
... Selezionare *Non controllare gli indici non cluster (NOINDEX)* se non si desidera controllare gli indici non cluster.  Il database di SQL Server utilizza Microsoft SQL Server Database Consistency Checker (DBCC) per verificare l'integrità logica e fisica degli oggetti nel database.


.. Limitare i controlli e ottenere i blocchi invece di utilizzare uno Snapshot del database interno (TABLOCK)
+
... Selezionare *Limita i controlli e ottieni i blocchi anziché utilizzare una copia Snapshot del database interno (TABLOCK)* per limitare i controlli e ottenere i blocchi anziché utilizzare una copia Snapshot del database interno.




. Nella sezione *Backup del registro*, seleziona *Verifica il backup del registro al completamento* per verificare il backup del registro al completamento.
. Nella sezione *Impostazioni script di verifica*, immettere il percorso e gli argomenti del prescript o del postscript che devono essere eseguiti rispettivamente prima o dopo l'operazione di verifica.
+

NOTE: Il percorso prescripts o postscripts non deve includere unità o condivisioni.  Il percorso dovrebbe essere relativo a SCRIPTS_PATH.





== Fase 10: Riepilogo della revisione

. Rivedi il riepilogo e seleziona *Fine*.

