---
permalink: protect-sco/supported_backup_configs.html 
sidebar: sidebar 
keywords: backup type, preferred nodes, catalog backups, schedules, backup name format, retention, verification 
summary: SnapCenter supporta il backup di diverse configurazioni di database Oracle. 
---
= Configurazioni del database Oracle supportate per i backup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter supporta il backup di diverse configurazioni di database Oracle.

* Oracle autonomo
* Cluster di applicazioni reali Oracle (RAC)
* Oracle Standalone Legacy
* Database contenitore autonomo Oracle (CDB)
* Oracle Data Guard in standby
+
È possibile creare solo backup offline dei database standby di Data Guard.  Il backup con arresto offline, il backup del solo registro di archivio e il backup completo non sono supportati.

* Oracle Active Data Guard standby
+
È possibile creare backup online solo dei database standby di Active Data Guard.  Non sono supportati il backup del solo registro di archivio e il backup completo.

+
Prima di creare un backup del database Data Guard standby o Active Data Guard standby, il processo di ripristino gestito (MRP) viene arrestato e, una volta creato il backup, MRP viene avviato.

* Gestione automatica dell'archiviazione (ASM)
+
** ASM standalone e ASM RAC su disco macchina virtuale (VMDK)
+
Tra tutti i metodi di ripristino supportati per i database Oracle, è possibile eseguire solo il ripristino di tipo connect-and-copy dei database ASM RAC su VMDK.

** ASM standalone e ASM RAC su Raw Device Mapping (RDM) + È possibile eseguire operazioni di backup, ripristino e clonazione su database Oracle su ASM, con o senza ASMLib.
** Driver filtro Oracle ASM (ASMFD)
+
Le operazioni di migrazione e clonazione PDB non sono supportate.

** Oracle Flex ASM




Per le informazioni più recenti sulle versioni Oracle supportate, vedere https://imt.netapp.com/matrix/imt.jsp?components=121071;&solution=1259&isHWU&src=IMT["Strumento matrice di interoperabilità NetApp"^] .
