---
permalink: protect-sco/task_define_a_clone_strategy_for_oracle_databases.html 
sidebar: sidebar 
keywords: backup types, cloning type, clone name, limitations 
summary: 'Definire una strategia prima di clonare il database garantisce il successo dell"operazione.' 
---
= Definire una strategia di clonazione per i database Oracle
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Definire una strategia prima di clonare il database garantisce il successo dell'operazione.



== Tipi di backup supportati per la clonazione

SnapCenter supporta la clonazione di diversi tipi di backup dei database Oracle.

* Backup dei dati online
* Backup completo online
* Backup del montaggio offline
* Backup di arresto offline
* Backup dei database standby di Data Guard e dei database standby di Active Data Guard
* Backup dei dati online, backup completi online, backup di montaggio offline e backup di arresto offline in una configurazione Real Application Clusters (RAC)
* Backup dei dati online, backup completi online, backup di montaggio offline e backup di arresto offline in una configurazione di gestione automatica dell'archiviazione (ASM)
+

IMPORTANT: Le configurazioni SAN non sono supportate se l'opzione user_friendly_names nel file di configurazione multipath è impostata su yes.




NOTE: La clonazione dei backup dei log di archivio non è supportata.



== Tipi di clonazione supportati per i database Oracle

In un ambiente di database Oracle, SnapCenter supporta la clonazione di un backup del database.  È possibile clonare il backup dai sistemi di archiviazione primari e secondari.

SnapCenter Server utilizza la tecnologia NetApp FlexClone per clonare i backup.

È possibile aggiornare un clone eseguendo il comando "Refresh-SmClone".  Questo comando crea un backup del database, elimina il clone esistente e crea un clone con lo stesso nome.


NOTE: L'operazione di aggiornamento del clone può essere eseguita solo utilizzando i comandi UNIX.



== Convenzioni di denominazione dei cloni per i database Oracle

A partire da SnapCenter 3.0, la convenzione di denominazione utilizzata per i cloni dei file system è diversa da quella utilizzata per i cloni dei gruppi di dischi ASM.

* La convenzione di denominazione per i file system SAN o NFS è FileSystemNameofsourcedatabase_CLONESID.
* La convenzione di denominazione per i gruppi di dischi ASM è SC_HASHCODEofDISKGROUP_CLONESID.
+
HASHCODEofDISKGROUP è un numero generato automaticamente (da 2 a 10 cifre) univoco per ciascun gruppo di dischi ASM.





== Limitazioni della clonazione dei database Oracle

Prima di clonare i database, è necessario essere consapevoli dei limiti delle operazioni di clonazione.

* Se si utilizza una versione di Oracle dalla 11.2.0.4 alla 12.1.0.1, l'operazione di clonazione sarà bloccata quando si esegue il comando _renamedg_.  Per risolvere questo problema, è possibile applicare la patch Oracle 19544733.
* La clonazione di database da una LUN direttamente collegata a un host (ad esempio, utilizzando Microsoft iSCSI Initiator su un host Windows) a un VMDK o a una LUN RDM sullo stesso host Windows o su un altro host Windows, o viceversa, non è supportata.
* La directory radice del punto di montaggio del volume non può essere una directory condivisa.
* Se si sposta una LUN contenente un clone in un nuovo volume, il clone non potrà essere eliminato.

