---
permalink: protect-sco/task_refresh_a_clone.html 
sidebar: sidebar 
keywords: refresh clone, clone 
summary: 'È possibile aggiornare il clone eseguendo il comando "Refresh-SmClone".  Questo comando crea un backup del database, elimina il clone esistente e crea un clone con lo stesso nome.' 
---
= Aggiorna un clone
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile aggiornare il clone eseguendo il comando _Refresh-SmClone_.  Questo comando crea un backup del database, elimina il clone esistente e crea un clone con lo stesso nome.


NOTE: Non è possibile aggiornare un clone PDB.

*Cosa ti servirà*

* Crea un backup completo online o un criterio di backup dei dati offline senza abilitare backup pianificati.
* Configurare la notifica e-mail nel criterio solo per gli errori di backup.
* Definire in modo appropriato il conteggio di conservazione per i backup su richiesta per garantire che non vi siano backup indesiderati.
* Assicurarsi che solo un backup completo online o un criterio di backup dei dati offline sia associato al gruppo di risorse identificato per l'operazione di clonazione di aggiornamento.
* Creare un gruppo di risorse con un solo database.
* Se viene creato un cron job per il comando clone refresh, assicurarsi che le pianificazioni SnapCenter e le pianificazioni cron non si sovrappongano per il gruppo di risorse del database.
+
Per un cron job creato per il comando clone refresh, assicurarsi di eseguire Open-SmConnection ogni 24 ore.

* Assicurarsi che il SID del clone sia univoco per un host.
+
Se più operazioni di clonazione di aggiornamento utilizzano lo stesso file di specifica del clone o utilizzano il file di specifica del clone con lo stesso SID del clone, il clone esistente con lo stesso SID sull'host verrà eliminato e quindi verrà creato il clone.

* Assicurarsi che il criterio di backup sia abilitato con protezione secondaria e che il file di specifica del clone sia creato con "`-IncludeSecondaryDetails`" per creare i cloni utilizzando backup secondari.
+
** Se viene specificato il file di specifica del clone primario ma il criterio ha selezionato l'opzione di aggiornamento secondario, il backup verrà creato e l'aggiornamento verrà trasferito al secondario.  Tuttavia, il clone verrà creato dal backup primario.
** Se viene specificato il file di specifica del clone primario e il criterio non ha selezionato l'opzione di aggiornamento secondario, il backup verrà creato sul primario e il clone verrà creato dal primario.




*Passi*

. Avvia una sessione di connessione con il server SnapCenter per un utente specificato: _Open-SmConnection_
. Crea una specifica di clone del database Oracle da un backup specificato: _New-SmOracleCloneSpecification_
+

NOTE: Se il criterio di protezione dei dati secondari è mirror-vault unificato, specificare solo -IncludeSecondaryDetails.  Non è necessario specificare -SecondaryStorageType.

+
Questo comando crea automaticamente un file di specifica del clone del database Oracle per il database di origine specificato e il relativo backup.  È inoltre necessario fornire un SID del database clone in modo che il file di specifiche creato contenga i valori generati automaticamente per il database clone che verrà creato.

+

NOTE: Il file di specifica del clone viene creato in _/var/opt/snapcenter/sco/clone_specs_.

. Eseguire _Refresh-SmClone_.
+
Se l'operazione fallisce con il messaggio di errore "PL-SCO-20032: operazione canExecute non riuscita con errore: PL-SCO-30031: il file di registro redo +SC_2959770772_clmdb/clmdb/redolog/redo01_01.log esiste", specificare un valore più alto per _-WaitToTriggerClone_.

+
Per informazioni dettagliate sui comandi UNIX, vedere https://library.netapp.com/ecm/ecm_download_file/ECMLP3337666["Guida di riferimento ai comandi del software SnapCenter"^] .


