---
permalink: protect-sce/reference_storage_types_supported_by_snapcenter_plug_in_for_microsoft_windows_and_for_microsoft_exchange_server.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for Microsoft Exchange Server 
summary: 'SnapCenter supporta un"ampia gamma di tipi di archiviazione sia su macchine fisiche che su macchine virtuali.  Prima di installare il pacchetto per l"host, è necessario verificare se il supporto è disponibile per il tipo di storage in uso.' 
---
= Tipi di archiviazione supportati dal plug-in SnapCenter per Microsoft Windows e per Microsoft Exchange Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter supporta un'ampia gamma di tipi di archiviazione sia su macchine fisiche che su macchine virtuali.  Prima di installare il pacchetto per l'host, è necessario verificare se il supporto è disponibile per il tipo di storage in uso.

Il supporto per il provisioning e la protezione dei dati SnapCenter è disponibile su Windows Server.  Per le informazioni più recenti sulle versioni supportate, vedere https://imt.netapp.com/matrix/imt.jsp?components=121031;&solution=1259&isHWU&src=IMT[] [Strumento matrice di interoperabilità NetApp ^].

|===
| Macchina | Tipo di archiviazione | Fornitura tramite | Note di supporto 


 a| 
Server fisico
 a| 
LUN connesse a FC
 a| 
Interfaccia utente grafica (GUI) SnapCenter o cmdlet di PowerShell
 a| 



 a| 
Server fisico
 a| 
LUN connesse tramite iSCSI
 a| 
Cmdlet GUI di SnapCenter o PowerShell
 a| 



 a| 
VMware VM
 a| 
LUN RDM connesse tramite un HBA FC o iSCSI
 a| 
Cmdlet di PowerShell
 a| 
Solo compatibilità fisica


NOTE: I VMDK non sono supportati.



 a| 
VMware VM
 a| 
LUN iSCSI collegate direttamente al sistema guest dall'iniziatore iSCSI
 a| 
Cmdlet GUI di SnapCenter o PowerShell
 a| 

NOTE: I VMDK non sono supportati.



 a| 
Macchina virtuale Hyper-V
 a| 
LUN FC virtuali (vFC) connesse tramite uno switch Fibre Channel virtuale
 a| 
Cmdlet GUI di SnapCenter o PowerShell
 a| 
È necessario utilizzare Hyper-V Manager per eseguire il provisioning di LUN Virtual FC (vFC) connesse tramite uno switch Fibre Channel virtuale.


NOTE: I dischi pass-through Hyper-V e il backup dei database su VHD(x) forniti su storage NetApp non sono supportati.



 a| 
Macchina virtuale Hyper-V
 a| 
LUN iSCSI collegate direttamente al sistema guest dall'iniziatore iSCSI
 a| 
Cmdlet GUI di SnapCenter o PowerShell
 a| 

NOTE: I dischi pass-through Hyper-V e il backup dei database su VHD(x) forniti su storage NetApp non sono supportati.

|===