---
permalink: protect-sce/task_create_backup_policies_for_exchange_server_databases.html 
sidebar: sidebar 
keywords: SnapCenter plug-in for Exchange Server 
summary: È possibile creare un criterio di backup per le risorse di Exchange o per i gruppi di risorse prima di utilizzare SnapCenter per eseguire il backup delle risorse di Microsoft Exchange Server oppure è possibile creare un criterio di backup al momento della creazione di un gruppo di risorse o del backup di una singola risorsa. 
---
= Creare criteri di backup per i database di Exchange Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile creare un criterio di backup per le risorse di Exchange o per i gruppi di risorse prima di utilizzare SnapCenter per eseguire il backup delle risorse di Microsoft Exchange Server oppure è possibile creare un criterio di backup al momento della creazione di un gruppo di risorse o del backup di una singola risorsa.

.Prima di iniziare
* Devi aver definito la tua strategia di protezione dei dati.
+
Per maggiori dettagli, vedere le informazioni sulla definizione di una strategia di protezione dei dati per i database di Exchange.

* È necessario prepararsi alla protezione dei dati completando attività quali l'installazione SnapCenter, l'aggiunta di host, l'identificazione delle risorse e la creazione di connessioni al sistema di archiviazione.
* È necessario aver aggiornato (rilevato) le risorse di Exchange Server.
* Se si replicano gli snapshot su un mirror o un vault, l'amministratore SnapCenter deve aver assegnato le macchine virtuali di archiviazione (SVM) sia per i volumi di origine che per quelli di destinazione.
* Se si desidera eseguire gli script di PowerShell in prescript e postscript, è necessario impostare il valore di `usePowershellProcessforScripts` parametro su true nel `web.config` file.
+
Il valore predefinito è falso.

* Esaminare i prerequisiti e le limitazioni specifici SnapMirror ActiveSync. Per informazioni, fare riferimento https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes["Limiti degli oggetti per la sincronizzazione attiva SnapMirror"] .


.Informazioni su questo compito
* Una policy di backup è un insieme di regole che regolano il modo in cui vengono gestiti e conservati i backup, nonché la frequenza con cui viene eseguito il backup della risorsa o del gruppo di risorse.  Inoltre, è possibile specificare le impostazioni dello script.  Specificare le opzioni in un criterio consente di risparmiare tempo quando si desidera riutilizzare il criterio per un altro gruppo di risorse.
* La conservazione completa del backup è specifica di una determinata policy.  Un database o una risorsa che utilizza la policy A con una conservazione del backup completo pari a 4 conserva 4 backup completi e non ha alcun effetto sulla policy B per lo stesso database o risorsa, che potrebbe avere una conservazione pari a 3 per conservare 3 backup completi.
* La conservazione del backup del log è efficace per tutte le policy e si applica a tutti i backup del log per un database o una risorsa.  Pertanto, quando si esegue un backup completo utilizzando il criterio B, l'impostazione di conservazione del registro influisce sui backup del registro creati dal criterio A sullo stesso database o risorsa.  Allo stesso modo, l'impostazione di conservazione dei log per la policy A influisce sui backup dei log creati dalla policy B sullo stesso database.
* SCRIPTS_PATH viene definito utilizzando la chiave PredefinedWindowsScriptsDirectory che si trova nel file SMCoreServiceHost.exe.Config dell'host del plug-in.
+
Se necessario, è possibile modificare questo percorso e riavviare il servizio SMcore.  Per motivi di sicurezza, si consiglia di utilizzare il percorso predefinito.

+
Il valore della chiave può essere visualizzato da Swagger tramite l'API: API /4.7/configsettings

+
È possibile utilizzare l'API GET per visualizzare il valore della chiave.  L'API SET non è supportata.

+
|===


| *Procedura consigliata:* è consigliabile configurare il criterio di conservazione secondario in base al numero complessivo di backup completi e di registro che si desidera conservare.  Quando si configurano criteri di conservazione secondari, tenere presente che quando i database e i log si trovano in volumi diversi, ogni backup può avere tre snapshot e quando i database e i log si trovano nello stesso volume, ogni backup può avere due snapshot. 
|===
* SnapLock
+
** Se è selezionata l'opzione "Conserva le copie di backup per un numero specifico di giorni", il periodo di conservazione SnapLock deve essere inferiore o uguale ai giorni di conservazione indicati.
+
Specificando un periodo di blocco degli snapshot si impedisce l'eliminazione degli snapshot fino alla scadenza del periodo di conservazione. Ciò potrebbe comportare la conservazione di un numero di snapshot maggiore rispetto al conteggio specificato nella policy.

+
Per ONTAP 9.12.1 e versioni precedenti, i cloni creati dagli SnapLock Vault Snapshot erediteranno il tempo di scadenza SnapLock Vault. L'amministratore dell'archiviazione deve pulire manualmente i cloni dopo la scadenza SnapLock .





.Passi
. Nel riquadro di navigazione a sinistra, fare clic su *Impostazioni*.
. Nella pagina Impostazioni, fare clic su *Criteri*.
. Fare clic su *Nuovo*.
. Nella pagina Nome, immettere il nome e i dettagli della policy.
. Nella pagina Tipo di backup e replica, procedere come segue:
+
.. Scegli il tipo di backup:
+
|===
| Se lo desidera... | Fai questo... 


 a| 
Eseguire il backup dei file del database e dei registri delle transazioni richiesti
 a| 
Selezionare *Backup completo e Backup del registro*.

Il backup dei database viene eseguito con il troncamento del log e tutti i log, compresi quelli troncati, vengono sottoposti a backup.


NOTE: Questo è il tipo di backup consigliato.



 a| 
Eseguire il backup dei file del database e dei registri delle transazioni non confermate
 a| 
Selezionare *Backup completo*.

I database vengono sottoposti a backup con troncamento del log, mentre i log troncati non vengono sottoposti a backup.



 a| 
Eseguire il backup di tutti i registri delle transazioni
 a| 
Selezionare *Backup del registro*.

Viene eseguito il backup di tutti i registri delle transazioni sul file system attivo e non avviene alcun troncamento dei registri.

Una directory _scebackupinfo_ viene creata sullo stesso disco del registro live.  Questa directory contiene il puntatore alle modifiche incrementali per il database di Exchange e non è equivalente ai file di registro completi.



 a| 
Eseguire il backup di tutti i file del database e dei registri delle transazioni senza troncare i file del registro delle transazioni
 a| 
Selezionare *Copia backup*.

Viene eseguito il backup di tutti i database e di tutti i log e non viene effettuato alcun troncamento dei log.  In genere questo tipo di backup viene utilizzato per effettuare il reseeding di una replica o per testare o diagnosticare un problema.

|===
+

NOTE: È necessario definire lo spazio necessario per i backup del registro in base alla conservazione completa dei backup e non in base alla conservazione Up-to-the-minute (UTM).

+

NOTE: Creare criteri di vault separati per registri e database quando si gestiscono volumi di Exchange (LUN) e impostare la conservazione per il criterio di registro su un numero doppio per ogni etichetta rispetto al criterio del database, utilizzando le stesse etichette.  Per maggiori informazioni vedere, https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/SnapCenter_for_Exchange_Backups_only_keep_half_the_Snapshots_on_the_Vault_destination_log_volume["I backup SnapCenter per Exchange conservano solo metà degli snapshot sul volume del registro di destinazione del Vault"^]

.. Nella sezione Impostazioni gruppo di disponibilità del database, seleziona un'azione:
+
|===
| Per questo campo... | Fai questo... 


 a| 
Eseguire il backup delle copie attive
 a| 
Selezionare questa opzione per eseguire il backup solo delle copie attive del database selezionato.

Per i gruppi di disponibilità del database (DAG), questa opzione esegue il backup solo delle copie attive di tutti i database nel DAG.

Le copie passive non vengono sottoposte a backup.



 a| 
Copie di backup sui server da selezionare al momento della creazione del processo di backup
 a| 
Selezionare questa opzione per eseguire il backup di tutte le copie dei database sui server selezionati, sia attivi che passivi.

Per i DAG, questa opzione esegue il backup delle copie attive e passive di tutti i database sui server selezionati.

|===
+

NOTE: Nelle configurazioni cluster, i backup vengono conservati in ciascun nodo del cluster in base alle impostazioni di conservazione definite nella policy.  Se il nodo proprietario del cluster cambia, verranno conservati i backup del nodo proprietario precedente.  La conservazione è applicabile solo a livello di nodo.

.. Nella sezione Frequenza di pianificazione, seleziona uno o più tipi di frequenza: *Su richiesta*, *Oraria*, *Giornaliera*, *Settimanale* e *Mensile*.
+

NOTE: È possibile specificare la pianificazione (data di inizio, data di fine) per le operazioni di backup durante la creazione di un gruppo di risorse.  Ciò consente di creare gruppi di risorse che condividono la stessa policy e la stessa frequenza di backup, ma consente di assegnare pianificazioni di backup diverse a ciascuna policy.

+

NOTE: Se hai programmato per le 2:00, la pianificazione non verrà attivata durante l'ora legale (DST).

.. Selezionare l'etichetta Criterio.
+

NOTE: È possibile assegnare etichette SnapMirror agli snapshot primari per la replica remota, consentendo agli snapshot primari di trasferire l'operazione di replica degli snapshot da SnapCenter ai sistemi secondari ONTAP . Questa operazione può essere eseguita senza abilitare l'opzione SnapMirror o SnapVault nella pagina dei criteri.

.. Nella sezione Seleziona opzioni di replicazione secondaria, seleziona una o entrambe le seguenti opzioni di replicazione secondaria:
+
|===
| Per questo campo... | Fai questo... 


 a| 
Aggiorna SnapMirror dopo aver creato uno Snapshot locale
 a| 
Selezionare questa opzione per conservare copie speculari dei set di backup su un altro volume (SnapMirror).

Durante la replicazione secondaria, il tempo di scadenza SnapLock carica il tempo di scadenza SnapLock primario.

Questa opzione dovrebbe essere abilitata per la sincronizzazione attiva SnapMirror .


IMPORTANT: Il criterio solo primario non può essere utilizzato se SnapMirror ActiveSync è configurato per i volumi Exchange ONTAP .  SnapCenter non lo consente.  Dovresti abilitare l'opzione "Mirror".

Facendo clic sul pulsante *Aggiorna* nella pagina Topologia, vengono aggiornati i tempi di scadenza SnapLock secondari e primari recuperati da ONTAP.

Vedere link:../protect-sce/task_view_exchange_backups_in_the_topology_page.html["Visualizza i backup di Exchange nella pagina Topologia"] .



 a| 
Aggiorna SnapVault dopo aver creato uno Snapshot locale
 a| 
Selezionare questa opzione per eseguire la replica del backup da disco a disco.



 a| 
Errore nel conteggio dei tentativi
 a| 
Immettere il numero di tentativi di replica che devono essere eseguiti prima che il processo si interrompa.

|===
+

NOTE: È necessario configurare i criteri di conservazione SnapMirror in ONTAP per l'archiviazione secondaria per evitare di raggiungere il limite massimo di snapshot sull'archiviazione secondaria.



. Nella pagina Conservazione, configura le impostazioni di conservazione.
+
Le opzioni visualizzate dipendono dal tipo di backup e dalla frequenza selezionati in precedenza.

+

NOTE: Il valore massimo di ritenzione è 1018. I backup non riusciranno se la conservazione è impostata su un valore superiore a quello supportato dalla versione ONTAP sottostante.

+

IMPORTANT: Se si prevede di abilitare la replica SnapVault , è necessario impostare il conteggio di conservazione su 2 o su un valore superiore.  Se si imposta il conteggio di conservazione su 1, l'operazione di conservazione potrebbe non riuscire perché il primo Snapshot è lo Snapshot di riferimento per la relazione SnapVault finché uno Snapshot più recente non viene replicato sulla destinazione.

+
.. Nella sezione Impostazioni di conservazione dei backup del registro, seleziona una delle seguenti opzioni:
+
|===
| Se lo desidera... | Fai questo... 


 a| 
Conservare solo un numero specifico di backup del registro
 a| 
Selezionare *Numero di backup completi per i quali vengono conservati i registri* e specificare il numero di backup completi per i quali si desidera un ripristino aggiornato.

La conservazione aggiornata al minuto (UTM) si applica al backup del registro creato tramite backup completo o del registro.  Ad esempio, se le impostazioni di conservazione UTM sono configurate per conservare i backup del registro degli ultimi 5 backup completi, verranno conservati i backup del registro degli ultimi 5 backup completi.

Le cartelle di registro create come parte dei backup completi e dei registri vengono eliminate automaticamente come parte di UTM.  Non è possibile eliminare manualmente le cartelle di registro.  Ad esempio, se l'impostazione di conservazione del backup completo o completo e del registro è impostata su 1 mese e la conservazione UTM è impostata su 10 giorni, la cartella del registro creata come parte di questi backup verrà eliminata come da UTM.  Di conseguenza, saranno presenti solo le cartelle di registro degli ultimi 10 giorni e tutti gli altri backup saranno contrassegnati per il ripristino in un dato momento.

È possibile impostare il valore di conservazione UTM su 0 se non si desidera eseguire un ripristino aggiornato.  Ciò consentirà l'operazione di ripristino in un dato momento.

*Procedura consigliata:* è preferibile che l'impostazione sia uguale all'impostazione per Snapshot totali (backup completi) nella sezione Impostazioni di conservazione dei backup completi.  Ciò garantisce che i file di registro vengano conservati per ogni backup completo.



 a| 
Conservare le copie di backup per un numero specifico di giorni
 a| 
Selezionare l'opzione *Conserva i backup del registro per ultimi* e specificare il numero di giorni per cui conservare le copie di backup del registro.

Vengono conservati i backup del log fino al numero di giorni dei backup completi.



 a| 
Periodo di blocco degli snapshot
 a| 
Selezionare *Periodo di blocco della copia snapshot* e selezionare giorni, mesi o anni.

Il periodo di conservazione SnapLock dovrebbe essere inferiore a 100 anni.

|===
+
Se hai selezionato *Backup del registro* come tipo di backup, i backup del registro vengono conservati come parte delle impostazioni di conservazione aggiornate per i backup completi.

.. Nella sezione Impostazioni di conservazione del backup completo, seleziona una delle seguenti opzioni per i backup su richiesta, quindi selezionane un'altra per i backup completi:
+
|===
| Per questo campo... | Fai questo... 


 a| 
Conserva solo un numero specifico di snapshot
 a| 
Se si desidera specificare il numero di backup completi da conservare, selezionare l'opzione *Numero totale di copie snapshot da conservare* e specificare il numero di snapshot (backup completi) da conservare.

Se il numero di backup completi supera il numero specificato, i backup completi che superano il numero specificato vengono eliminati, partendo dalle copie più vecchie.



 a| 
Conservare i backup completi per un numero specifico di giorni
 a| 
Selezionare l'opzione *Conserva copie snapshot per* e specificare il numero di giorni per cui conservare gli snapshot (backup completi).



 a| 
Periodo di blocco dello snapshot primario
 a| 
Selezionare *Periodo di blocco della copia snapshot primaria* e selezionare giorni, mesi o anni.

Il periodo di conservazione SnapLock dovrebbe essere inferiore a 100 anni.



 a| 
Periodo di blocco dello snapshot secondario
 a| 
Selezionare *Periodo di blocco della copia snapshot secondaria* e selezionare giorni, mesi o anni.

|===
+
Se si dispone di un database con solo backup del log e nessun backup completo su un host in una configurazione DAG, i backup del log vengono conservati nei seguenti modi:

+
*** Per impostazione predefinita, SnapCenter trova il backup completo più vecchio per questo database in tutti gli altri host del DAG ed elimina tutti i backup del registro su questo host eseguiti prima del backup completo.
*** È possibile ignorare il comportamento di conservazione predefinito sopra indicato per un database su un host in un DAG con solo backup del log aggiungendo la chiave *MaxLogBackupOnlyCountWithoutFullBackup* nel file _C:\Program Files\ NetApp\ SnapCenter WebApp\web.config_.
+
 <add key="MaxLogBackupOnlyCountWithoutFullBackup" value="10">
+
Nell'esempio, il valore 10 significa che si conservano fino a 10 backup del log sull'host.





. Nella pagina Script, immettere il percorso e gli argomenti del prescript o del postscript che devono essere eseguiti rispettivamente prima o dopo l'operazione di backup.
+
** Gli argomenti di backup predefiniti includono "`$Database`" e "`$ServerInstance`".
** Gli argomenti di backup PostScript includono "`$Database`", "`$ServerInstance`", "`$BackupName`", "`$LogDirectory`" e "`$LogSnapshot`".
+
È possibile eseguire uno script per aggiornare le trap SNMP, automatizzare gli avvisi, inviare registri e così via.

+

NOTE: Il percorso prescripts o postscripts non deve includere unità o condivisioni.  Il percorso dovrebbe essere relativo a SCRIPTS_PATH.



. Rivedi il riepilogo e poi clicca su *Fine*.

