---
permalink: protect-sce/task_define_a_backup_strategy_for_exchange_server_resources.html 
sidebar: sidebar 
keywords: SnapCenter plug-in for Exchange Server 
summary: 'Definire una strategia di backup prima di creare i processi di backup aiuta a garantire di disporre dei backup necessari per ripristinare correttamente i database.  Il Service Level Agreement (SLA), il Recovery Time Objective (RTO) e il Recovery Point Objective (RPO) determinano in larga misura la strategia di backup.' 
---
= Definire una strategia di backup per le risorse di Exchange Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Definire una strategia di backup prima di creare i processi di backup aiuta a garantire di disporre dei backup necessari per ripristinare correttamente i database.  Il Service Level Agreement (SLA), il Recovery Time Objective (RTO) e il Recovery Point Objective (RPO) determinano in larga misura la strategia di backup.

Un SLA definisce il livello di servizio previsto e affronta molti aspetti correlati al servizio, tra cui la disponibilità e le prestazioni del servizio.  L'RTO è il tempo entro il quale un processo aziendale deve essere ripristinato dopo un'interruzione del servizio.  Un RPO definisce la strategia per l'età dei file che devono essere recuperati dall'archivio di backup affinché le normali operazioni possano riprendere dopo un errore.  SLA, RTO e RPO contribuiscono alla strategia di backup.



== Tipi di backup supportati per il database di Exchange

Per eseguire il backup delle cassette postali di Exchange tramite SnapCenter è necessario scegliere il tipo di risorsa, ad esempio database e gruppi di disponibilità del database (DAG).  La tecnologia snapshot viene sfruttata per creare copie online di sola lettura dei volumi su cui risiedono le risorse.

|===
| Tipo di backup | Descrizione 


 a| 
Backup completo e del registro
 a| 
Esegue il backup dei database e di tutti i registri delle transazioni, compresi i registri troncati.

Una volta completato un backup completo, Exchange Server tronca i registri delle transazioni già salvati nel database.

In genere, dovresti scegliere questa opzione.  Tuttavia, se il tempo di backup è breve, è possibile scegliere di non eseguire un backup del registro delle transazioni con un backup completo.



 a| 
Backup completo
 a| 
Esegue il backup dei database e dei registri delle transazioni.

I registri delle transazioni troncati non vengono sottoposti a backup.



 a| 
Backup del registro
 a| 
Esegue il backup di tutti i registri delle transazioni.

I log troncati che sono già stati salvati nel database non vengono sottoposti a backup.  Se si pianificano backup frequenti del registro delle transazioni tra backup completi del database, è possibile scegliere punti di ripristino granulari.

|===


== Pianificazioni di backup per i plug-in del database

La frequenza del backup (tipo di pianificazione) è specificata nei criteri; una pianificazione del backup è specificata nella configurazione del gruppo di risorse.  Il fattore più critico nella determinazione della frequenza o della pianificazione di un backup è la velocità di modifica della risorsa e l'importanza dei dati.  Potresti eseguire il backup di una risorsa molto utilizzata ogni ora, mentre potresti eseguire il backup di una risorsa raramente utilizzata una volta al giorno.  Altri fattori includono l'importanza della risorsa per la tua organizzazione, il tuo Service Level Agreement (SLA) e il tuo Recover Point Objective (RPO).

Un SLA definisce il livello di servizio previsto e affronta molti aspetti correlati al servizio, tra cui la disponibilità e le prestazioni del servizio.  Un RPO definisce la strategia per l'età dei file che devono essere recuperati dall'archivio di backup affinché le normali operazioni possano riprendere dopo un errore.  L'SLA e l'RPO contribuiscono alla strategia di protezione dei dati.

Anche per una risorsa molto utilizzata, non è necessario eseguire un backup completo più di una o due volte al giorno.  Ad esempio, potrebbero essere sufficienti backup regolari del registro delle transazioni per garantire di disporre dei backup necessari.  Quanto più spesso si esegue il backup dei database, tanto minore sarà il numero di registri delle transazioni che SnapCenter dovrà utilizzare al momento del ripristino, il che può comportare operazioni di ripristino più rapide.

Le pianificazioni dei backup sono composte da due parti, come segue:

* Frequenza di backup
+
La frequenza di backup (la frequenza con cui devono essere eseguiti i backup), denominata _tipo di pianificazione_ per alcuni plug-in, fa parte della configurazione di una policy.  È possibile selezionare la frequenza di backup oraria, giornaliera, settimanale o mensile per la policy.  Se non si seleziona nessuna di queste frequenze, la policy creata sarà una policy solo on-demand.  È possibile accedere alle policy facendo clic su *Impostazioni* > *Policy*.

* Pianificazioni di backup
+
Le pianificazioni dei backup (ovvero quando devono essere eseguiti esattamente) fanno parte della configurazione di un gruppo di risorse.  Ad esempio, se si dispone di un gruppo di risorse con un criterio configurato per backup settimanali, è possibile configurare la pianificazione in modo che il backup venga eseguito ogni giovedì alle 22:00.  È possibile accedere alle pianificazioni dei gruppi di risorse facendo clic su *Risorse* > *Gruppi di risorse*.





== Numero di processi di backup necessari per i database

I fattori che determinano il numero di processi di backup necessari includono la dimensione della risorsa, il numero di volumi utilizzati, la frequenza di modifica della risorsa e il contratto di servizio (SLA).



== Convenzioni di denominazione del backup

È possibile utilizzare la convenzione di denominazione predefinita di Snapshot oppure una convenzione di denominazione personalizzata.  La convenzione di denominazione predefinita per i backup aggiunge un timestamp ai nomi degli snapshot che consente di identificare quando sono state create le copie.

Lo Snapshot utilizza la seguente convenzione di denominazione predefinita:

`resourcegroupname_hostname_timestamp`

Dovresti assegnare nomi logici ai gruppi di risorse di backup, come nell'esempio seguente:

[listing]
----
dts1_mach1x88_03-12-2015_23.17.26
----
In questo esempio, gli elementi della sintassi hanno i seguenti significati:

* _dts1_ è il nome del gruppo di risorse.
* _mach1x88_ è il nome host.
* _03-12-2015_23.17.26_ è la data e l'ora.


In alternativa, è possibile specificare il formato del nome dello snapshot durante la protezione delle risorse o dei gruppi di risorse selezionando *Usa formato nome personalizzato per la copia dello snapshot*.  Ad esempio, customtext_resourcegroup_policy_hostname o resourcegroup_hostname.  Per impostazione predefinita, il suffisso timestamp viene aggiunto al nome dello Snapshot.



== Opzioni di conservazione del backup

È possibile scegliere il numero di giorni per cui conservare le copie di backup oppure specificare il numero di copie di backup che si desidera conservare, fino a un massimo ONTAP di 255 copie.  Ad esempio, la tua organizzazione potrebbe richiedere di conservare 10 giorni di copie di backup o 130 copie di backup.

Durante la creazione di un criterio, è possibile specificare le opzioni di conservazione per il tipo di backup e il tipo di pianificazione.

Se si imposta la replica SnapMirror , il criterio di conservazione viene replicato sul volume di destinazione.

SnapCenter elimina i backup conservati che hanno etichette di conservazione corrispondenti al tipo di pianificazione.  Se il tipo di pianificazione è stato modificato per la risorsa o il gruppo di risorse, i backup con la vecchia etichetta del tipo di pianificazione potrebbero comunque rimanere sul sistema.


NOTE: Per la conservazione a lungo termine delle copie di backup, è consigliabile utilizzare il backup SnapVault .



== Per quanto tempo conservare i backup del registro delle transazioni sul volume di archiviazione di origine per Exchange Server

Il plug-in SnapCenter per Microsoft Exchange Server necessita di backup del registro delle transazioni per eseguire operazioni di ripristino aggiornate al minuto, che ripristinano il database a un orario compreso tra due backup completi.

Ad esempio, se Plug-in per Exchange ha eseguito un backup completo del registro delle transazioni alle 8:00 e un altro backup completo del registro delle transazioni alle 17:00, potrebbe utilizzare l'ultimo backup del registro delle transazioni per ripristinare il database a un orario qualsiasi compreso tra le 8:00 e le 17:00. Se i registri delle transazioni non sono disponibili, Plug-in per Exchange può eseguire solo operazioni di ripristino temporizzato, che ripristinano un database all'orario in cui Plug-in per Exchange ha completato un backup completo.

In genere, sono necessarie operazioni di ripristino aggiornate solo per uno o due giorni.  Per impostazione predefinita, SnapCenter conserva un minimo di due giorni.
