---
permalink: protect-sce/task_define_a_restore_strategy_for_exchange_databases.html 
sidebar: sidebar 
keywords: SnapCenter plug-in for Exchange Server 
summary: Definire una strategia di ripristino per Exchange Server consente di ripristinare correttamente il database. 
---
= Definire una strategia di ripristino per i database di Exchange
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Definire una strategia di ripristino per Exchange Server consente di ripristinare correttamente il database.



== Origini per un'operazione di ripristino in Exchange Server

È possibile ripristinare un database di Exchange Server da una copia di backup su un archivio primario.

È possibile ripristinare i database solo dall'archiviazione primaria.



== Tipi di operazioni di ripristino supportate per Exchange Server

È possibile utilizzare SnapCenter per eseguire diversi tipi di operazioni di ripristino sulle risorse di Exchange.

* Ripristinare all'ultimo minuto
* Ripristina un punto precedente nel tempo




=== Ripristina fino al minuto

In un'operazione di ripristino all'ultimo minuto, i database vengono ripristinati fino al punto di errore.  SnapCenter realizza questo risultato eseguendo la seguente sequenza:

. Ripristina i database dal backup completo del database selezionato.
. Applica tutti i registri delle transazioni sottoposti a backup, nonché tutti i nuovi registri creati dall'ultimo backup.
+
I registri delle transazioni vengono spostati in avanti e applicati a tutti i database selezionati.

+
Al termine di un ripristino, Exchange crea una nuova catena di registri.

+
|===


| *Procedura consigliata:* si consiglia di eseguire un nuovo backup completo e del registro dopo il completamento di un ripristino. 
|===
+
Un'operazione di ripristino aggiornata richiede un set contiguo di registri delle transazioni.

+
Dopo aver eseguito un ripristino aggiornato, il backup utilizzato per il ripristino è disponibile solo per le operazioni di ripristino point-in-time.

+
Se non è necessario mantenere la capacità di ripristino aggiornata per tutti i backup, è possibile configurare la conservazione del backup del registro delle transazioni del sistema tramite i criteri di backup.





=== Ripristina un punto precedente nel tempo

In un'operazione di ripristino point-in-time, i database vengono ripristinati solo a un momento specifico del passato.  Un'operazione di ripristino point-in-time si verifica nelle seguenti situazioni di ripristino:

* Il database viene ripristinato a un orario specificato in un registro delle transazioni sottoposto a backup.
* Il database viene ripristinato e ad esso viene applicato solo un sottoinsieme dei registri delle transazioni sottoposti a backup.

