---
permalink: protect-scw/concept_snapcenter_plug_in_for_microsoft_windows_overview.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for Microsoft Windows 
summary: 'Il plug-in SnapCenter per Microsoft Windows è un componente lato host del software NetApp SnapCenter che consente la gestione della protezione dei dati basata sulle applicazioni delle risorse del file system Microsoft.  Inoltre, fornisce provisioning di storage, coerenza degli snapshot e recupero di spazio per i file system di Windows.  Il plug-in per Windows automatizza le operazioni di backup, ripristino e clonazione del file system nell"ambiente SnapCenter .' 
---
= Panoramica del plug-in SnapCenter per Microsoft Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il plug-in SnapCenter per Microsoft Windows è un componente lato host del software NetApp SnapCenter che consente la gestione della protezione dei dati basata sulle applicazioni delle risorse del file system Microsoft.  Inoltre, fornisce provisioning di storage, coerenza degli snapshot e recupero di spazio per i file system di Windows.  Il plug-in per Windows automatizza le operazioni di backup, ripristino e clonazione del file system nell'ambiente SnapCenter .

Una volta installato il plug-in per Windows, è possibile utilizzare SnapCenter con la tecnologia NetApp SnapMirror per creare copie mirror di set di backup su un altro volume e con la tecnologia NetApp SnapVault per eseguire la replicazione del backup da disco a disco per l'archiviazione o la conformità agli standard.

* Abilita la protezione dei dati basata sulle applicazioni per altri plug-in in esecuzione negli host Windows nell'ambiente SnapCenter
* Automatizza le operazioni di backup, ripristino e clonazione basate sulle applicazioni per i file system Microsoft nel tuo ambiente SnapCenter
* Supporta il provisioning dello storage, la coerenza degli snapshot e il recupero dello spazio per gli host Windows



NOTE: Il plug-in per Windows esegue il provisioning di condivisioni SMB e file system Windows su LUN fisiche e RDM, ma non supporta operazioni di backup per file system Windows su condivisioni SMB.
