---
permalink: protect-scw/reference_sources_and_destinations_of_clones_for_windows_file_systems.html 
sidebar: sidebar 
keywords: snapcenter 
summary: 'È possibile clonare un backup del file system da un archivio primario o secondario.  Puoi anche scegliere la destinazione che supporta le tue esigenze: la posizione di backup originale o una destinazione diversa sullo stesso host o su un host diverso.  La destinazione deve trovarsi sullo stesso volume del backup di origine del clone.' 
---
= Origini e destinazioni dei cloni per i file system di Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile clonare un backup del file system da un archivio primario o secondario.  Puoi anche scegliere la destinazione che supporta le tue esigenze: la posizione di backup originale o una destinazione diversa sullo stesso host o su un host diverso.  La destinazione deve trovarsi sullo stesso volume del backup di origine del clone.

|===
| Destinazione del clone | Descrizione 


 a| 
Originale, fonte, posizione
 a| 
Per impostazione predefinita, SnapCenter memorizza il clone nella stessa posizione e sullo stesso host del backup che viene clonato.



 a| 
Posizione diversa
 a| 
È possibile archiviare il clone in una posizione diversa sullo stesso host o su un host diverso.  L'host deve disporre di una connessione configurata alla macchina virtuale di archiviazione (SVM).

|===
Una volta completata l'operazione di clonazione, è possibile rinominare il clone.
