---
permalink: protect-scw/reference_installation_requirements_for_snapcenter_plug_in_for_microsoft_windows.html 
sidebar: sidebar 
keywords: requirements 
summary: Prima di installare il plug-in per Windows, è necessario conoscere alcuni requisiti di installazione. 
---
= Requisiti di installazione per il plug-in SnapCenter per Microsoft Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di installare il plug-in per Windows, è necessario conoscere alcuni requisiti di installazione.

Prima di iniziare a utilizzare il plug-in per Windows, l'amministratore SnapCenter deve installare e configurare SnapCenter Server ed eseguire le attività preliminari.

* Per installare il plug-in per Windows è necessario disporre dei privilegi di amministratore SnapCenter .
+
Il ruolo di amministratore SnapCenter deve disporre di privilegi di amministratore.

* È necessario aver installato e configurato SnapCenter Server.
* Quando si installa un plug-in su un host Windows, se si specifica una credenziale non integrata o se l'utente appartiene a un utente del gruppo di lavoro locale, è necessario disabilitare UAC sull'host.
* Se si desidera la replica del backup, è necessario configurare SnapMirror e SnapVault .




== Requisiti host per installare il pacchetto plug-in SnapCenter per Windows

Prima di installare il pacchetto di plug-in SnapCenter per Windows, è necessario acquisire familiarità con alcuni requisiti di base di spazio e dimensioni del sistema host.

|===
| Articolo | Requisiti 


 a| 
Sistemi operativi
 a| 
Microsoft Windows

Per le informazioni più recenti sulle versioni supportate, vedere https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT["Strumento matrice di interoperabilità NetApp"^] .

Se si utilizza un cluster Windows, è necessario installare e configurare anche Windows Remote Management (WinRM).



 a| 
RAM minima per il plug-in SnapCenter sull'host
 a| 
1 GB



 a| 
Spazio minimo di installazione e registro per il plug-in SnapCenter sull'host
 a| 
5 GB


NOTE: È necessario allocare spazio su disco sufficiente e monitorare il consumo di spazio di archiviazione da parte della cartella dei registri.  Lo spazio di registro richiesto varia a seconda del numero di entità da proteggere e della frequenza delle operazioni di protezione dei dati.  Se non c'è spazio sufficiente sul disco, i registri per le operazioni eseguite di recente non verranno creati.



 a| 
Pacchetti software richiesti
 a| 
* Pacchetto di hosting ASP.NET Core Runtime 8.0.12 (e tutte le patch 8.0.x successive)
* PowerShell Core 7.4.2


Per le informazioni più recenti sulle versioni supportate, vedere https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT["Strumento matrice di interoperabilità NetApp"^] .

Per informazioni specifiche sulla risoluzione dei problemi di .NET, vedere https://kb.netapp.com/mgmt/SnapCenter/SnapCenter_upgrade_or_install_fails_with_This_KB_is_not_related_to_the_OS["L'aggiornamento o l'installazione SnapCenter non riesce nei sistemi legacy che non dispongono di connettività Internet."]

|===


== Imposta le tue credenziali per il plug-in per Windows

SnapCenter utilizza le credenziali per autenticare gli utenti per le operazioni SnapCenter .  È necessario creare le credenziali per l'installazione dei plug-in di SnapCenter e credenziali aggiuntive per eseguire operazioni di protezione dei dati sui file system di Windows.

*Cosa ti servirà*

* Prima di installare i plug-in è necessario impostare le credenziali di Windows.
* È necessario impostare le credenziali con privilegi di amministratore, inclusi i diritti di amministratore, sull'host remoto.
* Se si impostano credenziali per singoli gruppi di risorse e l'utente non dispone di privilegi di amministratore completi, è necessario assegnare all'utente almeno i privilegi di gruppo di risorse e di backup.


*Passi*

. Nel riquadro di navigazione a sinistra, fare clic su *Impostazioni*.
. Nella pagina Impostazioni, fare clic su *Credenziali*.
. Fare clic su *Nuovo*.
. Nella pagina Credenziali, procedi come segue:
+
|===
| Per questo campo... | Fai questo... 


 a| 
Nome della credenziale
 a| 
Inserisci un nome per le credenziali.



 a| 
Nome utente/Password
 a| 
Inserisci il nome utente e la password utilizzati per l'autenticazione.

** Amministratore di dominio o qualsiasi membro del gruppo di amministratori
+
Specificare l'amministratore di dominio o un membro del gruppo di amministratori sul sistema su cui si sta installando il plug-in SnapCenter . I formati validi per il campo Nome utente sono i seguenti:

+
*** `NetBIOS\UserName`
*** `Domain FQDN\UserName`
*** `UserName@upn`


** Amministratore locale (solo per gruppi di lavoro)
+
Per i sistemi che appartengono a un gruppo di lavoro, specificare l'amministratore locale predefinito sul sistema su cui si sta installando il plug-in SnapCenter . È possibile specificare un account utente locale appartenente al gruppo degli amministratori locali se l'account utente dispone di privilegi elevati o se la funzionalità di controllo degli accessi utente è disabilitata sul sistema host.  Il formato valido per il campo Nome utente è il seguente: `UserName`

+
Non utilizzare virgolette doppie (") o apici inversi (`) nelle password.  Non dovresti usare insieme i simboli minore (<) e punto esclamativo (!) nelle password.  Ad esempio, lessthan<!10, lessthan10<!, backtick`12.





 a| 
Password
 a| 
Inserisci la password utilizzata per l'autenticazione.

|===
. Fare clic su *OK*.
+
Dopo aver completato la configurazione delle credenziali, potresti voler assegnare la manutenzione delle credenziali a un utente o a un gruppo di utenti nella pagina Utente e accesso.





== Configurare gMSA su Windows Server 2016 o versioni successive

Windows Server 2016 o versioni successive consente di creare un account di servizio gestito di gruppo (gMSA) che fornisce la gestione automatizzata delle password degli account di servizio da un account di dominio gestito.

.Prima di iniziare
* Dovresti avere un controller di dominio Windows Server 2016 o versione successiva.
* Dovresti avere un host Windows Server 2016 o versione successiva, che sia membro del dominio.


.Passi
. Crea una chiave radice KDS per generare password univoche per ogni oggetto nel tuo gMSA.
. Per ogni dominio, eseguire il seguente comando dal controller di dominio Windows: Add-KDSRootKey -EffectiveImmediately
. Crea e configura il tuo gMSA:
+
.. Crea un account di gruppo utenti nel seguente formato:
+
 domainName\accountName$
.. Aggiungere oggetti computer al gruppo.
.. Utilizzare il gruppo utenti appena creato per creare il gMSA.
+
Per esempio,

+
 New-ADServiceAccount -name <ServiceAccountName> -DNSHostName <fqdn> -PrincipalsAllowedToRetrieveManagedPassword <group> -ServicePrincipalNames <SPN1,SPN2,…>
.. Correre `Get-ADServiceAccount` comando per verificare l'account di servizio.


. Configurare gMSA sui tuoi host:
+
.. Abilitare il modulo Active Directory per Windows PowerShell sull'host in cui si desidera utilizzare l'account gMSA.
+
Per fare ciò, eseguire il seguente comando da PowerShell:

+
[listing]
----
PS C:\> Get-WindowsFeature AD-Domain-Services

Display Name                           Name                Install State
------------                           ----                -------------
[ ] Active Directory Domain Services   AD-Domain-Services  Available


PS C:\> Install-WindowsFeature AD-DOMAIN-SERVICES

Success Restart Needed Exit Code      Feature Result
------- -------------- ---------      --------------
True    No             Success        {Active Directory Domain Services, Active ...
WARNING: Windows automatic updating is not enabled. To ensure that your newly-installed role or feature is
automatically updated, turn on Windows Update.
----
.. Riavvia il tuo host.
.. Installa gMSA sul tuo host eseguendo il seguente comando dal prompt dei comandi di PowerShell: `Install-AdServiceAccount <gMSA>`
.. Verifica il tuo account gMSA eseguendo il seguente comando: `Test-AdServiceAccount <gMSA>`


. Assegnare i privilegi amministrativi al gMSA configurato sull'host.
. Aggiungere l'host Windows specificando l'account gMSA configurato nel server SnapCenter .
+
SnapCenter Server installerà i plug-in selezionati sull'host e il gMSA specificato verrà utilizzato come account di accesso al servizio durante l'installazione del plug-in.


