---
permalink: protect-scw/task_install_on_multiple_remote_hosts_using_powershell_cmdlets.html 
sidebar: sidebar 
keywords: install, snapcenter 
summary: Se si desidera installare il plug-in SnapCenter per Microsoft Windows su più host contemporaneamente, è possibile farlo utilizzando il cmdlet Install-SmHostPackage di PowerShell. 
---
= Installa il plug-in SnapCenter per Microsoft Windows su più host remoti utilizzando i cmdlet di PowerShell
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si desidera installare il plug-in SnapCenter per Microsoft Windows su più host contemporaneamente, è possibile farlo utilizzando `Install-SmHostPackage` Cmdlet di PowerShell.

È necessario aver effettuato l'accesso a SnapCenter come utente di dominio con diritti di amministratore locale su ciascun host su cui si desidera installare i plug-in.

.Passi
. Avvia PowerShell.
. Sull'host del server SnapCenter , stabilire una sessione utilizzando `Open-SmConnection` cmdlet, quindi immettere le credenziali.
. Aggiungere l'host autonomo o il cluster a SnapCenter utilizzando `Add-SmHost` cmdlet e i parametri richiesti.
+
Le informazioni relative ai parametri che possono essere utilizzati con il cmdlet e le relative descrizioni possono essere ottenute eseguendo _Get-Help command_name_. In alternativa, puoi anche fare riferimento a https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guida di riferimento ai cmdlet del software SnapCenter"^] .

. Installare il plug-in su più host utilizzando `Install-SmHostPackage` cmdlet e i parametri richiesti.
+
Puoi usare il `-skipprecheck` opzione quando hai installato i plug-in manualmente e non vuoi verificare se l'host soddisfa i requisiti per installare il plug-in.


