---
permalink: upgrade/task_configure_snapcenter_to_check_for_available_updates.html 
sidebar: sidebar 
keywords: configure, snapcenter server, updates, software updates 
summary: 'SnapCenter comunica periodicamente con il sito di supporto NetApp per informarti sulla disponibilità di aggiornamenti software.  È anche possibile creare una pianificazione per specificare l"intervallo in cui si desidera ricevere informazioni sugli aggiornamenti disponibili.' 
---
= Configura SnapCenter per verificare la disponibilità di aggiornamenti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter comunica periodicamente con il sito di supporto NetApp per informarti sulla disponibilità di aggiornamenti software.  È anche possibile creare una pianificazione per specificare l'intervallo in cui si desidera ricevere informazioni sugli aggiornamenti disponibili.

.Passi
. Nel riquadro di navigazione a sinistra, fare clic su *Impostazioni*.
. Nella pagina *Impostazioni*, fare clic su *Software*.
+
La pagina Software disponibile mostra i pacchetti plug-in disponibili, le versioni disponibili e il loro stato di installazione.

. Fare clic su *Controlla aggiornamenti* per verificare se sono disponibili versioni più recenti dei pacchetti plug-in.
. Fare clic su *Pianifica aggiornamenti* per creare una pianificazione e specificare l'intervallo in cui si desidera ricevere informazioni sugli aggiornamenti disponibili:
+
.. Selezionare l'intervallo in *Verifica aggiornamenti*.
.. Selezionare le credenziali Windows di SnapCenter Server Admin e fare clic su *OK*.



