---
permalink: upgrade/task_upgrade_snapcenter.html 
sidebar: sidebar 
keywords: upgrade, upgrade snapcenter server, windows 
summary: È possibile utilizzare il file eseguibile del programma di installazione di SnapCenter Server per aggiornare SnapCenter Server. 
---
= Aggiornare il server SnapCenter sull'host Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario aggiornare SnapCenter Server per accedere alle funzionalità e ai miglioramenti più recenti forniti nella versione più recente.

.Prima di iniziare
* Aggiornare l'host del server SnapCenter con gli ultimi aggiornamenti di Windows e assicurarsi che non vi siano riavvii del sistema in sospeso.
* Prima di avviare l'aggiornamento, assicurarsi che non siano in esecuzione altre operazioni.
* Installare ASP.NET Core Runtime 8.0.12 (e tutte le patch 8.0.x successive) Hosting Bundle e PowerShell 7.4.2 o versione successiva.
* Eseguire il backup del database del repository SnapCenter (MySQL) dopo essersi assicurati che non vi siano processi in esecuzione. Si consiglia di effettuare questa operazione prima di aggiornare SnapCenter Server e il plug-in di Exchange.
+
Per informazioni, vederelink:../admin/concept_manage_the_snapcenter_server_repository.html#back-up-the-snapcenter-repository["Eseguire il backup del repository SnapCenter"^] .

* Eseguire il backup di tutti i file di configurazione SnapCenter modificati sull'host del server SnapCenter o sull'host del plug-in.
+
Esempi di file di configurazione SnapCenter : SnapDriveService.exe.config, SMCoreServiceHost.exe.config e così via.

* Se hai installato più versioni del plug-in personalizzato in SnapCenter 5.0, prima di eseguire l'aggiornamento alla versione 6.0 o successiva, dovresti eseguire i cmdlet di PowerShell per rimuovere tutte le versioni precedenti del plug-in personalizzato (tranne quella più recente) dal repository SnapCenter (database NSM).
+
** Correre `Open-SmConnection` e accedi utilizzando le credenziali del ruolo SnapCenterAdmin
** Correre `Remove-SmPluginPackage -PluginName M<plug-in name> -PluginVersion <version number>`
+
Per ulteriori informazioni, consulta  https://kb.netapp.com/data-mgmt/SnapCenter/SC_KBs/SnapCenter_6.0_upgrade_fails_in_nsm_repository_upgrade_SQL_script_8["L'aggiornamento a SnapCenter 6.0 o versione successiva non riesce"] .





.Informazioni su questo compito
* Durante l'aggiornamento, SnapCenter esegue uno script SQL per aggiornare i dati di Exchange nel database NSM, convertendo il DAG e il nome abbreviato dell'host in FQDN. Ciò si applica solo se si utilizza SnapCenter Server con il plug-in Exchange.
* Se hai messo manualmente l'host del server in modalità di manutenzione, dopo l'aggiornamento seleziona *Host* > *Attiva pianificazione* per far uscire l'host del server dalla modalità di manutenzione.
* Per le pianificazioni di backup e verifica esistenti con prescript e postscript abilitati nella policy, le operazioni di backup continueranno a funzionare dopo l'aggiornamento.
+
Nella pagina *Dettagli lavoro*, un messaggio di avviso consiglia al cliente di copiare gli script in SCRIPTS_PATH e di modificare la policy per fornire un percorso relativo a SCRIPTS_PATH.  Per il processo del ciclo di vita del clone, il messaggio di avviso viene visualizzato a livello di sottoprocesso.



.Passi
. Scaricare il pacchetto di installazione di SnapCenter Server dal sito di supporto NetApp .
+
https://mysupport.netapp.com/site/products/all/details/snapcenter/downloads-tab[]

. Creare una copia del file web.config che si trova in C:\Programmi\ NetApp\ SnapCenter WebApp.
. Esportare le pianificazioni host del plug-in SnapCenter dall'Utilità di pianificazione di Windows per ripristinarle se l'aggiornamento non riesce.
+
`md d:\\SCBackup``schtasks /query /xml /TN taskname >> "D:\SCBackup\taskname.xml"`

. Creare il dump del database MySQL di SnapCenter se il backup del repository non è configurato.
+
`md d:\\SCBackup``mysqldump --all-databases --single-transaction --add-drop-database --triggers --routines --events -u root -p > D:\SCBackup\SCRepoBackup.dmp`

+
Quando richiesto, inserisci la password.

. Fare doppio clic sul file .exe scaricato per avviare l'aggiornamento di SnapCenter Server.
+
Dopo aver avviato l'aggiornamento, SnapCenter esegue dei controlli preliminari. Se il sistema non soddisfa i requisiti minimi, SnapCenter mostra messaggi di errore o di avviso. È possibile ignorare gli avvisi e continuare con l'installazione, ma è necessario correggere eventuali errori.

+

NOTE: SnapCenter continua a utilizzare la password del database del repository MySQL Server esistente fornita durante l'installazione della versione precedente di SnapCenter Server.

. Seleziona *Aggiorna*.
+
Se in qualsiasi momento selezioni *Annulla*, SnapCenter interrompe l'aggiornamento. Non ripristinerà lo stato precedente di SnapCenter Server.

+
*Procedura consigliata:* disconnettersi e riconnettersi oppure aprire un nuovo browser per accedere all'interfaccia utente SnapCenter .



.Dopo aver finito
* Se il plug-in viene installato tramite un utente sudo, è necessario copiare le chiavi sha224 disponibili in _C:\ProgramData\ NetApp\ SnapCenter\Package Repository\sc_unix_plugins_checksum.txt_ per aggiornare il file _/etc/sudoers_.
* Dovresti eseguire una nuova individuazione delle risorse sull'host del server.
+
Se SnapCenter visualizza lo stato dell'host del server come arrestato, attendere qualche istante ed eseguire una nuova individuazione. È anche possibile modificare il valore del parametro *HostRefreshInterval* (il valore predefinito è 3600 secondi) impostandolo su un valore superiore a 10 minuti.

* Se l'aggiornamento non riesce, pulire l'installazione non riuscita, reinstallare la versione precedente di SnapCenter e ripristinare il database NSM allo stato in cui si trovava prima.
* Dopo aver aggiornato l'host del server, è necessario aggiornare anche i plug-in prima di aggiungere qualsiasi sistema di archiviazione.

