---
permalink: protect-hana/concept_how_snapcenter_plug_in_for_sap_hana_database_uses_consistency_group_snapshot_copies.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for SAP HANA Database 
summary: 'È possibile utilizzare il plug-in per creare snapshot di gruppi di coerenza per gruppi di risorse.  Un gruppo di coerenza è un contenitore che può ospitare più volumi, in modo da poterli gestire come un"unica entità.  Un gruppo di coerenza è costituito da snapshot simultanei di più volumi, che forniscono copie coerenti di un gruppo di volumi.' 
---
= Come il plug-in SnapCenter per il database SAP HANA utilizza gli snapshot del gruppo di coerenza
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare il plug-in per creare snapshot di gruppi di coerenza per gruppi di risorse.  Un gruppo di coerenza è un contenitore che può ospitare più volumi, in modo da poterli gestire come un'unica entità.  Un gruppo di coerenza è costituito da snapshot simultanei di più volumi, che forniscono copie coerenti di un gruppo di volumi.

È anche possibile specificare il tempo di attesa affinché il controller di archiviazione raggruppi in modo coerente gli snapshot.  Le opzioni di tempo di attesa disponibili sono *Urgente*, *Medio* e *Rilassato*.  È anche possibile abilitare o disabilitare la sincronizzazione Write Anywhere File Layout (WAFL) durante l'operazione Snapshot di gruppo coerente.  La sincronizzazione WAFL migliora le prestazioni di uno Snapshot di gruppo di coerenza.
