---
permalink: protect-hana/concept_snapcenter_plug_in_for_sap_hana_database_overview.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for SAP HANA Database 
summary: Il plug-in SnapCenter per il database SAP HANA è un componente lato host del software NetApp SnapCenter software che consente la gestione della protezione dei dati basata sulle applicazioni dei database SAP HANA.  Il plug-in per il database SAP HANA automatizza il backup, il ripristino e la clonazione dei database SAP HANA nel tuo ambiente SnapCenter . 
---
= Panoramica del plug-in SnapCenter per il database SAP HANA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il plug-in SnapCenter per il database SAP HANA è un componente lato host del software NetApp SnapCenter software che consente la gestione della protezione dei dati basata sulle applicazioni dei database SAP HANA.  Il plug-in per il database SAP HANA automatizza il backup, il ripristino e la clonazione dei database SAP HANA nel tuo ambiente SnapCenter .

SnapCenter supporta contenitori di database singoli e multi-tenant (MDC).  È possibile utilizzare il plug-in per il database SAP HANA sia in ambienti Windows che Linux.  Il plug-in non installato sull'host del database HANA è noto come plug-in host centralizzato. Il plug-in host centralizzato può gestire più database HANA su host diversi.

Una volta installato il plug-in per il database SAP HANA, è possibile utilizzare SnapCenter con la tecnologia NetApp SnapMirror per creare copie mirror dei set di backup su un altro volume.  È inoltre possibile utilizzare il plug-in con la tecnologia NetApp SnapVault per eseguire la replicazione del backup da disco a disco per la conformità agli standard.

Il plug-in per il database SAP HANA supporta la sincronizzazione attiva SnapMirror (inizialmente rilasciata come SnapMirror Business Continuity [SM-BC]), che consente ai servizi aziendali di continuare a funzionare anche in caso di guasto completo del sito, supportando le applicazioni per il failover trasparente tramite una copia secondaria.  Per attivare un failover con SnapMirror ActiveSync non è necessario alcun intervento manuale né scripting aggiuntivo.
