---
permalink: protect-hana/reference_host_requirements_to_install_snapcenter_plug_in_package_for_linux.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: Prima di installare il pacchetto di plug-in SnapCenter per Linux, è necessario acquisire familiarità con alcuni requisiti di base relativi allo spazio e alle dimensioni del sistema host. 
---
= Requisiti host per l'installazione del pacchetto plug-in SnapCenter per Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di installare il pacchetto di plug-in SnapCenter per Linux, è necessario acquisire familiarità con alcuni requisiti di base relativi allo spazio e alle dimensioni del sistema host.

|===
| Articolo | Requisiti 


 a| 
Sistemi operativi
 a| 
* Red Hat Enterprise Linux
* SUSE Linux Enterprise Server (SLES)


Per le informazioni più recenti sulle versioni supportate, vedere https://imt.netapp.com/matrix/imt.jsp?components=121073;&solution=1257&isHWU&src=IMT["Strumento matrice di interoperabilità NetApp"] .



 a| 
RAM minima per il plug-in SnapCenter sull'host
 a| 
1 GB



 a| 
Spazio minimo di installazione e registro per il plug-in SnapCenter sull'host
 a| 
2 GB


NOTE: È necessario allocare spazio su disco sufficiente e monitorare il consumo di spazio di archiviazione da parte della cartella dei registri.  Lo spazio di registro richiesto varia a seconda del numero di entità da proteggere e della frequenza delle operazioni di protezione dei dati.  Se non c'è spazio sufficiente sul disco, i registri per le operazioni eseguite di recente non verranno creati.



 a| 
Pacchetti software richiesti
 a| 
Java 11 Oracle Java e OpenJDK

Se hai aggiornato JAVA alla versione più recente, devi assicurarti che l'opzione JAVA_HOME situata in /var/opt/snapcenter/spl/etc/spl.properties sia impostata sulla versione JAVA corretta e sul percorso corretto.

Per le informazioni più recenti sulle versioni supportate, vedere https://imt.netapp.com/matrix/imt.jsp?components=121073;&solution=1257&isHWU&src=IMT["Strumento matrice di interoperabilità NetApp"] .

|===