---
permalink: protect-hana/reference_prerequisites_for_using_snapcenter_plug_in_for_sap_hana_database.html 
sidebar: sidebar 
keywords: Credentials,SnapCenter Plug-in for SAP HANA Database 
summary: 'Prima di utilizzare il plug-in SnapCenter per il database SAP HANA, l"amministratore SnapCenter deve installare e configurare SnapCenter Server ed eseguire le attività preliminari.' 
---
= Prerequisiti per l'utilizzo del plug-in SnapCenter per il database SAP HANA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di utilizzare il plug-in SnapCenter per il database SAP HANA, l'amministratore SnapCenter deve installare e configurare SnapCenter Server ed eseguire le attività preliminari.

* Installa e configura SnapCenter Server.
* Accedi a SnapCenter Server.
* Configurare l'ambiente SnapCenter aggiungendo connessioni al sistema di archiviazione e creando credenziali, se applicabile.
* Installa Java 11 sul tuo host Linux o Windows.
+
È necessario impostare il percorso Java nella variabile del percorso ambientale della macchina host.

* Se desideri la replica del backup, imposta SnapMirror e SnapVault.
* Installare il client HDBSQL sull'host in cui verrà installato il plug-in per il database SAP HANA.
+
Configurare le chiavi di archivio utente per i nodi SAP HANA che verranno gestiti tramite questo host.

* Per il database SAP HANA 2.0SPS05, se si utilizza un account utente del database SAP HANA, assicurarsi di disporre delle seguenti autorizzazioni per eseguire operazioni di backup, ripristino e clonazione in SnapCenter Server:
+
** Amministratore di backup
** Catalogo letto
** Amministratore del backup del database
** Operatore di recupero database



