---
permalink: protect-hana/task_install_the_snapcenter_plug_in_for_sap_hana_database_on_linux_hosts_using_the_command_line_interface.html 
sidebar: sidebar 
keywords: install, SnapCenter Plug-in for SAP HANA Database 
summary: 'È necessario installare il plug-in SnapCenter per il database SAP HANA utilizzando l"interfaccia utente (UI) SnapCenter .  Se l"ambiente non consente l"installazione remota del plug-in dall"interfaccia utente SnapCenter , è possibile installare il plug-in per il database SAP HANA in modalità console o in modalità silenziosa utilizzando l"interfaccia della riga di comando (CLI1).' 
---
= Installa il plug-in SnapCenter per il database SAP HANA su host Linux utilizzando l'interfaccia della riga di comando
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario installare il plug-in SnapCenter per il database SAP HANA utilizzando l'interfaccia utente (UI) SnapCenter .  Se l'ambiente non consente l'installazione remota del plug-in dall'interfaccia utente SnapCenter , è possibile installare il plug-in per il database SAP HANA in modalità console o in modalità silenziosa utilizzando l'interfaccia della riga di comando (CLI).

.Prima di iniziare
* È necessario installare il plug-in per il database SAP HANA su ciascun host Linux in cui risiede il client HDBSQL.
* L'host Linux su cui si installa il plug-in SnapCenter per il database SAP HANA deve soddisfare i requisiti software, del database e del sistema operativo dipendenti.
+
Lo strumento Interoperability Matrix (IMT) contiene le informazioni più recenti sulle configurazioni supportate.

+
https://imt.netapp.com/matrix/imt.jsp?components=121029;&solution=1259&isHWU&src=IMT[]

* Il plug-in SnapCenter per il database SAP HANA fa parte del pacchetto di plug-in SnapCenter per Linux.  Prima di installare il pacchetto plug-in SnapCenter per Linux, è necessario aver già installato SnapCenter su un host Windows.


.Passi
. Copiare il file di installazione del pacchetto plug-in SnapCenter per Linux (snapcenter_linux_host_plugin.bin) da C:\ProgramData\ NetApp\ SnapCenter\Package Repository all'host in cui si desidera installare il plug-in per il database SAP HANA.
+
È possibile accedere a questo percorso dall'host in cui è installato SnapCenter Server.

. Dal prompt dei comandi, vai alla directory in cui hai copiato il file di installazione.
. Installa il plug-in: `path_to_installation_bin_file/snapcenter_linux_host_plugin.bin -i silent -DPORT=port_number_for_host -DSERVER_IP=server_name_or_ip_address -DSERVER_HTTPS_PORT=port_number_for_server`
+
** -DPORT specifica la porta di comunicazione HTTPS di SMCore.
** -DSERVER_IP specifica l'indirizzo IP del server SnapCenter .
** -DSERVER_HTTPS_PORT specifica la porta HTTPS del server SnapCenter .
** -DUSER_INSTALL_DIR specifica la directory in cui si desidera installare il pacchetto plug-in SnapCenter per Linux.
** DINSTALL_LOG_NAME specifica il nome del file di registro.


+
[listing]
----
/tmp/sc-plugin-installer/snapcenter_linux_host_plugin.bin -i silent  -DPORT=8145 -DSERVER_IP=scserver.domain.com -DSERVER_HTTPS_PORT=8146 -DUSER_INSTALL_DIR=/opt -DINSTALL_LOG_NAME=SnapCenter_Linux_Host_Plugin_Install_2.log -DCHOSEN_FEATURE_LIST=CUSTOM
----
. Modificare il file /<directory di installazione>/ NetApp/snapcenter/scc/etc/SC_SMS_Services.properties, quindi aggiungere il parametro PLUGINS_ENABLED = hana:3.0.
. Aggiungere l'host al server SnapCenter utilizzando il cmdlet Add-Smhost e i parametri richiesti.
+
Le informazioni riguardanti i parametri che possono essere utilizzati con il comando e le relative descrizioni possono essere ottenute eseguendo _Get-Help nome_comando_. In alternativa, puoi anche fare riferimento a https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guida di riferimento ai cmdlet del software SnapCenter"^] .


