---
permalink: protect-hana/task_create_backup_policies_for_sap_hana_databases.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for SAP HANA Database 
summary: Prima di utilizzare SnapCenter per eseguire il backup delle risorse del database SAP HANA, è necessario creare una policy di backup per la risorsa o il gruppo di risorse di cui si desidera eseguire il backup.  Una policy di backup è un insieme di regole che regolano il modo in cui si gestiscono, si pianificano e si conservano i backup. 
---
= Creare policy di backup per i database SAP HANA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di utilizzare SnapCenter per eseguire il backup delle risorse del database SAP HANA, è necessario creare una policy di backup per la risorsa o il gruppo di risorse di cui si desidera eseguire il backup.  Una policy di backup è un insieme di regole che regolano il modo in cui si gestiscono, si pianificano e si conservano i backup.

.Prima di iniziare
* Devi aver definito la tua strategia di backup.
+
Per maggiori dettagli, consultare le informazioni sulla definizione di una strategia di protezione dei dati per i database SAP HANA.

* È necessario prepararsi alla protezione dei dati completando attività quali l'installazione di SnapCenter, l'aggiunta di host, la configurazione delle connessioni al sistema di archiviazione e l'aggiunta di risorse.
* Se si stanno replicando gli snapshot su un mirror o un vault, l'amministratore SnapCenter deve aver assegnato le SVM sia per il volume di origine che per quello di destinazione.
+
Inoltre, è possibile specificare le impostazioni di replica, script e applicazione nel criterio.  Queste opzioni consentono di risparmiare tempo quando si desidera riutilizzare il criterio per un altro gruppo di risorse.

* Esaminare i prerequisiti e le limitazioni specifici SnapMirror ActiveSync.  Per informazioni fare riferimento https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes["Limiti degli oggetti per la sincronizzazione attiva SnapMirror"] .


.Informazioni su questo compito
* Replica del sistema SAP HANA
+
** È possibile proteggere il sistema SAP HANA primario e possono essere eseguite tutte le operazioni di protezione dei dati.
** È possibile proteggere il sistema SAP HANA secondario, ma non è possibile creare backup.
+
Dopo il failover, tutte le operazioni di protezione dei dati possono essere eseguite poiché il sistema SAP HANA secondario diventa il sistema SAP HANA primario.

+
Non è possibile creare un backup per il volume dati SAP HANA, ma SnapCenter continua a proteggere i volumi non dati (NDV).



* SnapLock
+
** Se è selezionata l'opzione "Conserva le copie di backup per un numero specifico di giorni", il periodo di conservazione SnapLock deve essere inferiore o uguale ai giorni di conservazione indicati.
** Specificando un periodo di blocco degli snapshot si impedisce l'eliminazione degli snapshot fino alla scadenza del periodo di conservazione. Ciò potrebbe comportare la conservazione di un numero di snapshot maggiore rispetto al conteggio specificato nella policy.
** Per ONTAP 9.12.1 e versioni precedenti, i cloni creati dagli SnapLock Vault Snapshot come parte del ripristino erediteranno il tempo di scadenza SnapLock Vault. L'amministratore dell'archiviazione deve pulire manualmente i cloni dopo la scadenza SnapLock .




.Passi
. Nel riquadro di navigazione a sinistra, fare clic su *Impostazioni*.
. Nella pagina Impostazioni, fare clic su *Criteri*.
. Fare clic su *Nuovo*.
. Nella pagina Nome, immettere il nome e i dettagli della policy.
. Nella pagina Tipo di policy, procedere come segue:
+
** Scegli il tipo di archiviazione
** Scegli il tipo di backup:
+
|===
| Se lo desidera... | Fai questo... 


 a| 
Crea un backup utilizzando la tecnologia Snapshot
 a| 
Selezionare *Basato su snapshot*.



 a| 
Eseguire un controllo di integrità del database
 a| 
Selezionare *Backup basato su file*.  Viene eseguito il backup solo dei tenant attivi.

|===


. Nella pagina Snapshot e replica, procedere come segue:
+
** Specificare il tipo di pianificazione selezionando *Su richiesta*, *Ora*, *Giornaliera*, *Settimanale* o *Mensile*.
+

NOTE: È possibile specificare la pianificazione (data di inizio, data di fine e frequenza) per l'operazione di backup durante la creazione di un gruppo di risorse.  Ciò consente di creare gruppi di risorse che condividono la stessa policy e la stessa frequenza di backup, ma consente anche di assegnare pianificazioni di backup diverse a ciascuna policy.

+

NOTE: Se hai programmato per le 2:00, la pianificazione non verrà attivata durante l'ora legale (DST).



. Nella pagina Snapshot e replica, specificare le impostazioni di conservazione per il tipo di backup e il tipo di pianificazione selezionati nella pagina Tipo di backup:
+
|===
| Se lo desidera... | Poi... 


 a| 
Conserva un certo numero di snapshot
 a| 
Seleziona *Copie da conservare*, quindi specifica il numero di snapshot che desideri conservare.

Se il numero di Snapshot supera il numero specificato, gli Snapshot più vecchi vengono eliminati per primi.


NOTE: Il valore massimo di ritenzione è 1018. I backup non riusciranno se la conservazione è impostata su un valore superiore a quello supportato dalla versione ONTAP .


IMPORTANT: Per i backup basati su copie Snapshot, è necessario impostare il conteggio di conservazione su 2 o superiore se si prevede di abilitare la replica SnapVault .  Se si imposta il conteggio di conservazione su 1, l'operazione di conservazione potrebbe non riuscire perché il primo Snapshot è lo Snapshot di riferimento per la relazione SnapVault finché uno Snapshot più recente non viene replicato sulla destinazione.


NOTE: Per la replica del sistema SAP HANA, si consiglia di aggiungere tutte le risorse del sistema SAP HANA in un unico gruppo di risorse.  In questo modo si garantisce che venga conservato il numero corretto di backup.


NOTE: Per la replica del sistema SAP HANA, il numero totale di snapshot acquisiti sarà pari al set di conservazione per il gruppo di risorse.  La rimozione dello Snapshot più vecchio si basa sul nodo in cui si trova lo Snapshot più vecchio.  Ad esempio, la conservazione è impostata su 7 per un gruppo di risorse con SAP HANA System Replication primario e SAP HANA System Replication secondario.  È possibile acquisire un massimo di 7 snapshot alla volta, inclusi sia SAP HANA System Replication primario che SAP HANA System Replication secondario.



 a| 
Conserva gli snapshot per un certo numero di giorni
 a| 
Selezionare *Conserva copie per*, quindi specificare il numero di giorni per cui si desidera conservare gli snapshot prima di eliminarli.



 a| 
Periodo di blocco della copia snapshot
 a| 
Selezionare *Periodo di blocco della copia snapshot* e specificare giorni, mesi o anni.

Il periodo di conservazione SnapLock dovrebbe essere inferiore a 100 anni.

|===
. Selezionare un'etichetta Snapshot.
+

NOTE: È possibile assegnare etichette SnapMirror agli snapshot primari per la replica remota, consentendo agli snapshot primari di trasferire l'operazione di replica degli snapshot da SnapCenter ai sistemi secondari ONTAP . Questa operazione può essere eseguita senza abilitare l'opzione SnapMirror o SnapVault nella pagina dei criteri.

. Per i backup basati su copie snapshot, nella sezione Seleziona opzioni di replica secondaria, seleziona una o entrambe le seguenti opzioni di replica secondaria:
+
|===
| Per questo campo... | Fai questo... 


 a| 
*Aggiorna SnapMirror dopo aver creato una copia Snapshot locale*
 a| 
Selezionare questo campo per creare copie mirror dei set di backup su un altro volume (replica SnapMirror ).

Questa opzione dovrebbe essere abilitata per la sincronizzazione attiva SnapMirror .

Se la relazione di protezione in ONTAP è di tipo Mirror e Vault e si seleziona solo questa opzione, lo Snapshot creato sul primario non verrà trasferito alla destinazione, ma verrà elencato nella destinazione.  Se si seleziona questo snapshot dalla destinazione per eseguire un'operazione di ripristino, viene visualizzato il messaggio di errore "La posizione secondaria non è disponibile per il backup con vault/mirroring selezionato".

Durante la replicazione secondaria, il tempo di scadenza SnapLock carica il tempo di scadenza SnapLock primario.

Facendo clic sul pulsante *Aggiorna* nella pagina Topologia, vengono aggiornati i tempi di scadenza SnapLock secondari e primari recuperati da ONTAP.

Vedere link:../protect-hana/task_view_sap_hana_database_backups_and_clones_in_the_topology_page_sap_hana.html["Visualizza i backup e i cloni del database SAP HANA nella pagina Topologia"] .



 a| 
*Aggiorna SnapVault dopo aver creato una copia Snapshot locale*
 a| 
Selezionare questa opzione per eseguire la replica del backup da disco a disco (backup SnapVault ).

Durante la replicazione secondaria, il tempo di scadenza SnapLock carica il tempo di scadenza SnapLock primario.  Facendo clic sul pulsante *Aggiorna* nella pagina Topologia, vengono aggiornati i tempi di scadenza SnapLock secondari e primari recuperati da ONTAP.

Quando SnapLock è configurato solo sul secondario da ONTAP noto come SnapLock Vault, facendo clic sul pulsante *Aggiorna* nella pagina Topologia si aggiorna il periodo di blocco sul secondario recuperato da ONTAP.

Per maggiori informazioni su SnapLock Vault vedere https://docs.netapp.com/us-en/ontap/snaplock/commit-snapshot-copies-worm-concept.html["Eseguire il commit delle copie Snapshot su WORM in una destinazione vault"]

Vedere link:../protect-hana/task_view_sap_hana_database_backups_and_clones_in_the_topology_page_sap_hana.html["Visualizza i backup e i cloni del database SAP HANA nella pagina Topologia"] .



 a| 
*Errore nel conteggio dei nuovi tentativi*
 a| 
Immettere il numero massimo di tentativi di replica consentiti prima che l'operazione venga interrotta.

|===
+

NOTE: È necessario configurare i criteri di conservazione SnapMirror in ONTAP per l'archiviazione secondaria per evitare di raggiungere il limite massimo di snapshot sull'archiviazione secondaria.

. Rivedi il riepilogo e poi clicca su *Fine*.

