= 
:allow-uri-read: 


.Passi
. Avvia una sessione di connessione con SnapCenter Server per un utente specificato utilizzando il cmdlet Open-SmConnection.
+
[listing]
----
Open-smconnection  -SMSbaseurl  https://snapctr.demo.netapp.com:8146
----
+
Viene visualizzata la richiesta di nome utente e password.

. Creare un criterio di backup utilizzando il cmdlet Add-SmPolicy.
+
Questo esempio crea un nuovo criterio di backup con un tipo di backup SQL di FullBackup:

+
[listing]
----
PS C:\> Add-SmPolicy -PolicyName TESTPolicy
-PluginPolicyType SCSQL -PolicyType Backup
-SqlBackupType FullBackup -Verbose
----
+
Questo esempio crea un nuovo criterio di backup con un tipo di backup del file system Windows CrashConsistent:

+
[listing]
----
PS C:\> Add-SmPolicy -PolicyName FileSystemBackupPolicy
-PluginPolicyType SCW -PolicyType Backup
-ScwBackupType CrashConsistent -Verbose
----
. Scopri le risorse host utilizzando il cmdlet Get-SmResources.
+
Questo esempio rileva le risorse per il plug-in Microsoft SQL sull'host specificato:

+
[listing]
----
C:\PS>PS C:\> Get-SmResources -HostName vise-f6.sddev.mycompany.com
-PluginCode SCSQL
----
+
Questo esempio rileva le risorse per i file system Windows sull'host specificato:

+
[listing]
----
C:\PS>PS C:\> Get-SmResources -HostName vise2-f6.sddev.mycompany.com
-PluginCode SCW
----
. Aggiungere un nuovo gruppo di risorse a SnapCenter utilizzando il cmdlet Add-SmResourceGroup.
+
Questo esempio crea un nuovo gruppo di risorse di backup del database SQL con i criteri e le risorse specificati:

+
[listing]
----
PS C:\> Add-SmResourceGroup -ResourceGroupName AccountingResource
-Resources @{"Host"="visef6.org.com";
"Type"="SQL Database";"Names"="vise-f6\PayrollDatabase"}
-Policies "BackupPolicy"
----
+
Questo esempio crea un nuovo gruppo di risorse di backup del file system di Windows con i criteri e le risorse specificati:

+
[listing]
----
PS C:\> Add-SmResourceGroup -ResourceGroupName EngineeringResource
-PluginCode SCW -Resources @{"Host"="WIN-VOK20IKID5I";
"Type"="Windows Filesystem";"Names"="E:\"}
-Policies "EngineeringBackupPolicy"
----
. Avviare un nuovo processo di backup utilizzando il cmdlet New-SmBackup.
+
[listing]
----
PS C:> New-SmBackup -ResourceGroupName PayrollDataset -Policy FinancePolicy
----
. Visualizzare lo stato del processo di backup utilizzando il cmdlet Get-SmBackupReport.
+
Questo esempio visualizza un report riepilogativo di tutti i lavori eseguiti nella data specificata:

+
[listing]
----
PS C:\> Get-SmJobSummaryReport -Date '1/27/2016'
----


Le informazioni relative ai parametri che possono essere utilizzati con il cmdlet e le relative descrizioni possono essere ottenute eseguendo _Get-Help command_name_. In alternativa, puoi anche fare riferimento a https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guida di riferimento ai cmdlet del software SnapCenter"^] .
