= 
:allow-uri-read: 


È necessario creare una connessione alla macchina virtuale di archiviazione (SVM) e delle credenziali prima di utilizzare i cmdlet di PowerShell per eseguire operazioni di protezione dei dati.

.Prima di iniziare
* Dovresti aver preparato l'ambiente PowerShell per eseguire i cmdlet PowerShell.
* Per creare connessioni di archiviazione è necessario disporre delle autorizzazioni necessarie nel ruolo di amministratore dell'infrastruttura.
* È necessario assicurarsi che non siano in corso installazioni di plug-in.
+
Le installazioni di plug-in host non devono essere in corso durante l'aggiunta di una connessione al sistema di storage, poiché la cache host potrebbe non essere aggiornata e lo stato dei database potrebbe essere visualizzato nell'interfaccia utente grafica SnapCenter come "`Non disponibile per il backup`" o "`Non su storage NetApp ".

* I nomi dei sistemi di archiviazione devono essere univoci.
+
SnapCenter non supporta più sistemi di archiviazione con lo stesso nome su cluster diversi.  Ogni sistema di archiviazione supportato da SnapCenter deve avere un nome univoco e un indirizzo IP LIF di gestione univoco.



.Passi
. Avviare una sessione di connessione PowerShell Core utilizzando il cmdlet Open-SmConnection.
+
Questo esempio apre una sessione di PowerShell:

+
[listing]
----
PS C:\> Open-SmConnection
----
. Creare una nuova connessione al sistema di archiviazione utilizzando il cmdlet Add-SmStorageConnection.
+
Questo esempio crea una nuova connessione al sistema di archiviazione:

+
[listing]
----
PS C:\> Add-SmStorageConnection -Storage test_vs1 -Protocol Https
-Timeout 60
----
. Creare una nuova credenziale utilizzando il cmdlet Add-SmCredential.
+
Questo esempio crea una nuova credenziale denominata FinanceAdmin con credenziali Windows:

+
[listing]
----
PS C:> Add-SmCredential -Name FinanceAdmin -AuthMode Windows
-Credential sddev\administrator
----


Le informazioni relative ai parametri che possono essere utilizzati con il cmdlet e le relative descrizioni possono essere ottenute eseguendo _Get-Help command_name_. In alternativa, puoi anche fare riferimento a https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guida di riferimento ai cmdlet del software SnapCenter"^] .
