---
permalink: protect-azure/add-hosts-install-plugin-for-sap-hana.html 
sidebar: sidebar 
keywords: add host, install, install plug-in, SAP HANA 
summary: Aggiungere gli host e quindi installare i pacchetti dei plug-in. 
---
= Aggiungi host e installa il plug-in SnapCenter per il database SAP HANA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario utilizzare la pagina Aggiungi host SnapCenter per aggiungere host e quindi installare i pacchetti plug-in.  I plug-in vengono installati automaticamente sugli host remoti.

.Prima di iniziare
* Devi essere un utente a cui è assegnato un ruolo che dispone delle autorizzazioni di installazione e disinstallazione del plug-in, ad esempio il ruolo di amministratore SnapCenter .
* Quando si installa un plug-in su un host Windows, se si specifica una credenziale non integrata o se l'utente appartiene a un utente di un gruppo di lavoro locale, è necessario disabilitare UAC sull'host.
* Se si esegue l'installazione sull'host centralizzato, assicurarsi che il software client SAP HANA sia installato su tale host e aprire le porte necessarie sull'host del database SAP HANA per eseguire le query SQL HDB in remoto.


.Passi
. Nel riquadro di navigazione a sinistra, fare clic su *Host*.
. Verificare che la scheda *Host gestiti* sia selezionata.
. Fare clic su *Aggiungi*.
. Nella pagina Host, eseguire le seguenti azioni:
+
.. Nel campo Tipo di host, selezionare il tipo di host.
.. Nel campo Nome host, immettere il nome di dominio completo (FQDN) o l'indirizzo IP dell'host.
.. Nel campo Credenziali, inserisci le credenziali che hai creato.


. Nella sezione Seleziona plug-in da installare, seleziona i plug-in da installare.
. (Facoltativo) Fare clic su *Altre opzioni* e specificare i dettagli.
. Fare clic su *Invia*.
. Se il tipo di host è Linux, verificare l'impronta digitale, quindi fare clic su *Conferma e invia*.
+
In una configurazione cluster, è necessario verificare l'impronta digitale di ciascun nodo del cluster.

. Monitorare l'avanzamento dell'installazione.

