---
permalink: protect-azure/create-azure-credential.html 
sidebar: sidebar 
keywords: snapcenter, azure, azure credential 
summary: 'Creare le credenziali di Azure in SnapCenter per accedere all"account Azure NetApp .' 
---
= Creare le credenziali di Azure in SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per accedere all'account Azure NetApp , è necessario creare le credenziali di Azure in SnapCenter .

.Prima di iniziare
* Assicurati di aver creato l'entità servizio in Azure.
* Assicurati di avere a disposizione l'ID tenant, l'ID client e la chiave segreta associati al servizio principale.
+
** L'ID tenant è reperibile nel portale di Azure nella pagina Panoramica per l'ID Entra.
** L'ID client è anche noto come ID applicazione per l'Enterprise App/Service Principal.  Questa informazione è disponibile nel portale di Azure nella pagina Panoramica per l'applicazione aziendale creata per fungere da entità servizio per SnapCenter.
** La chiave segreta del client è anche nota come valore segreto.  È possibile creare questo segreto client nel portale di Azure accedendo a *Registrazioni app* in ID Entra.  Dopo aver selezionato l'app aziendale creata, vai su *Certificati e segreti* e poi su *Nuovo segreto client*.
+

NOTE: È possibile accedere al valore segreto solo al momento della creazione.  Non potrai accedervi in seguito.

** È necessario concedere le autorizzazioni al Service Principal.  Il ruolo di Collaboratore consentirà all'entità servizio di eseguire le azioni richieste in Azure.  Questa operazione può essere eseguita tramite la pagina Controllo accessi (IAM) all'interno della pagina Abbonamento.




.Passi
. Nel riquadro di navigazione a sinistra, fare clic su *Impostazioni*.
. Nella pagina Impostazioni, fare clic su *Credenziali*.
. Fare clic su *Nuovo*.
. Nella pagina Credenziali, specificare le seguenti informazioni necessarie per creare le credenziali.
+
|===
| Per questo campo... | Fai questo... 


 a| 
Nome della credenziale
 a| 
Inserisci un nome per la credenziale.



 a| 
Modalità di autenticazione
 a| 
Selezionare *Credenziali di Azure* dall'elenco a discesa.



 a| 
ID inquilino
 a| 
Inserisci l'ID del tenant.



 a| 
ID cliente
 a| 
Inserisci l'ID cliente.



 a| 
Chiave segreta del cliente
 a| 
Inserisci la chiave segreta del client.

|===
. Fare clic su *OK*.

