---
permalink: protect-azure/create-backup-policies-sap-hana.html 
sidebar: sidebar 
keywords: create policies, SAP HANA, backup policies 
summary: Creare un criterio di backup per la risorsa o il gruppo di risorse di cui si desidera eseguire il backup. 
---
= Creare policy di backup per i database SAP HANA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di utilizzare SnapCenter per eseguire il backup delle risorse del database SAP HANA, è necessario creare una policy di backup per la risorsa o il gruppo di risorse di cui si desidera eseguire il backup.

.Passi
. Nel riquadro di navigazione a sinistra, fare clic su *Impostazioni*.
. Nella pagina Impostazioni, fare clic su *Criteri*.
. Fare clic su *Nuovo*.
. Nella pagina Nome, immettere il nome e la descrizione della policy.
. Nella pagina Tipo di policy, procedere come segue:
+
.. Selezionare * Azure NetApp Files* come tipo di archiviazione.
.. Selezionare *Basato su file* se si desidera eseguire un controllo di integrità del database.
.. Selezionare *Basato su snapshot* se si desidera creare un backup utilizzando la tecnologia Snapshot.


. Nella pagina Snapshot e backup, procedere come segue:
+
.. Selezionare la frequenza del backup pianificato.
.. Specificare le impostazioni di conservazione.
.. Se si desidera abilitare il backup Azure NetApp Files , selezionare *Abilita backup* e specificare le impostazioni di conservazione.


. Rivedi il riepilogo e clicca su *Fine*.

