---
permalink: protect-azure/create-backup-policies-sql.html 
sidebar: sidebar 
keywords: create policies, sql, backup policies 
summary: Creare un criterio di backup per la risorsa o il gruppo di risorse di cui si desidera eseguire il backup. 
---
= Creare criteri di backup per i database di SQL Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile creare un criterio di backup per la risorsa o il gruppo di risorse prima di utilizzare SnapCenter per eseguire il backup delle risorse di SQL Server oppure è possibile creare un criterio di backup al momento della creazione di un gruppo di risorse o del backup di una singola risorsa.

.Passi
. Nel riquadro di navigazione a sinistra, fare clic su *Impostazioni*.
. Nella pagina Impostazioni, fare clic su *Criteri*.
. Fare clic su *Nuovo*.
. Nella pagina Nome, immettere il nome e la descrizione della policy.
. Nella pagina Tipo di policy, procedere come segue:
+
.. Selezionare * Azure NetApp Files* come tipo di archiviazione.
.. Selezionare il tipo di backup.
+
... Selezionare *Backup completo e backup del registro* se si desidera eseguire il backup dei file del database e dei registri delle transazioni.
... Selezionare *Backup completo* se si desidera eseguire il backup solo dei file del database.
... Selezionare *Backup del registro* se si desidera eseguire il backup solo dei registri delle transazioni.
... Selezionare *Copia solo backup* se si desidera eseguire il backup delle risorse utilizzando un'altra applicazione.


.. Nella sezione Impostazioni gruppo di disponibilità, eseguire le seguenti azioni:
+
... Selezionare Backup sulla replica di backup preferita se si desidera eseguire il backup solo sulla replica.
... Selezionare la replica AG primaria o la replica AG secondaria per il backup.
... Selezionare la priorità del backup.




. Nella pagina Snapshot e backup, procedere come segue:
+
.. Selezionare la frequenza del backup pianificato.
.. Specificare le impostazioni di conservazione in base al tipo di backup selezionato.
.. Se si desidera abilitare il backup Azure NetApp Files , selezionare *Abilita backup* e specificare le impostazioni di conservazione.


. Nella pagina Verifica, procedere come segue:
+
.. Nella sezione Esegui verifica per le seguenti pianificazioni di backup, seleziona la frequenza della pianificazione.
.. Nella sezione Opzioni di controllo della coerenza del database, eseguire le seguenti azioni:
+
... Selezionare *Limita la struttura di integrità alla struttura fisica del database (PHYSICAL_ONLY)* per limitare il controllo di integrità alla struttura fisica del database e per rilevare pagine danneggiate, errori di checksum e guasti hardware comuni che hanno un impatto sul database.
... Selezionare *Sopprimi tutti i messaggi informativi (NO_INFOMSGS)* per sopprimere tutti i messaggi informativi.
+
Selezionato per impostazione predefinita.

... Selezionare *Visualizza tutti i messaggi di errore segnalati per oggetto (ALL_ERRORMSGS)* per visualizzare tutti gli errori segnalati per oggetto.
... Selezionare *Non controllare gli indici non cluster (NOINDEX)* se non si desidera controllare gli indici non cluster.
+
Il database di SQL Server utilizza Microsoft SQL Server Database Consistency Checker (DBCC) per verificare l'integrità logica e fisica degli oggetti nel database.

... Selezionare *Limita i controlli e ottieni i blocchi anziché utilizzare una copia Snapshot del database interno (TABLOCK)* per limitare i controlli e ottenere i blocchi anziché utilizzare una copia Snapshot del database interno.


.. Nella sezione *Backup del registro*, seleziona *Verifica il backup del registro al completamento* per verificare il backup del registro al completamento.
.. Nella sezione *Impostazioni script di verifica*, immettere il percorso e gli argomenti del prescript o del postscript che devono essere eseguiti rispettivamente prima o dopo l'operazione di verifica.


. Rivedi il riepilogo e clicca su *Fine*.

