---
permalink: admin/concept_manage_the_storage_system.html 
sidebar: sidebar 
keywords: Manage storage system 
summary: Dopo aver aggiunto il sistema di archiviazione, è possibile modificarne la configurazione e le connessioni oppure eliminarlo. 
---
= Gestire il sistema di archiviazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver aggiunto il sistema di archiviazione, è possibile modificarne la configurazione e le connessioni oppure eliminarlo.



== Modificare la configurazione del sistema di archiviazione

È possibile utilizzare SnapCenter per modificare la configurazione del sistema di archiviazione se si desidera cambiare il nome utente, la password, la piattaforma, la porta, il protocollo, il periodo di timeout, l'indirizzo IP preferito o le opzioni di messaggistica.

*Informazioni su questo compito*

È possibile modificare le connessioni di archiviazione per un singolo utente o per un gruppo.  Se si appartiene a uno o più gruppi con autorizzazione per lo stesso sistema di archiviazione, il nome della connessione di archiviazione viene visualizzato più volte nell'elenco delle connessioni di archiviazione, una volta per ciascun gruppo con autorizzazione per il sistema di archiviazione.

*Passi*

. Nel riquadro di navigazione a sinistra, fare clic su *Sistemi di archiviazione*.
. Nella pagina Sistemi di archiviazione, dal menu a discesa *Tipo*, eseguire una delle seguenti azioni:
+
|===
| Selezionare... | Passi... 


 a| 
SVM ONTAP
 a| 
Per visualizzare tutte le macchine virtuali di archiviazione (SVM) aggiunte e per modificare la configurazione SVM richiesta.

.. Nella pagina Connessioni di archiviazione, fare clic sul nome SVM appropriato.
.. Eseguire una delle seguenti azioni:
+
*** Se l'SVM non fa parte di alcun cluster, nella pagina Modifica sistema di archiviazione, modificare le configurazioni quali nome utente, password, impostazioni EMS e AutoSupport , piattaforma, protocollo, porta, timeout e IP preferito.
*** Se l'SVM fa parte di un cluster, nella pagina Modifica sistema di archiviazione, seleziona *Gestisci SVM in modo indipendente* e modifica le configurazioni quali nome utente, password, impostazioni EMS e AutoSupport , piattaforma, protocollo, porta, timeout e IP preferito.
+
Dopo aver modificato l'SVM in modo che venga gestito in modo indipendente, se si decide di gestirlo tramite cluster, è necessario eliminare l'SVM e quindi fare clic su *Riscopri*.  L'SVM verrà aggiunto al cluster ONTAP .

+

NOTE: Quando la password di un sistema di archiviazione viene aggiornata nell'interfaccia utente grafica SnapCenter , è necessario riavviare i servizi SMCore del rispettivo plug-in o dell'host del server, poiché la password aggiornata non viene visualizzata in SMCore e i processi di backup non riusciranno con un errore di credenziale errata.







 a| 
Cluster ONTAP
 a| 
Per visualizzare tutti i cluster aggiunti e modificare la configurazione del cluster richiesta.

.. Nella pagina Connessioni di archiviazione, fare clic sul nome del cluster.
.. Nella pagina Modifica sistema di archiviazione, fare clic sull'icona di modifica accanto a Nome utente e modificare il nome utente e la password.
.. Selezionare o deselezionare le impostazioni EMS e AutoSupport .
.. Fare clic su *Altre opzioni* e modificare altre configurazioni quali piattaforma, protocollo, porta, timeout e IP preferito.


|===
. Fare clic su *Invia*.




== Elimina il sistema di archiviazione

È possibile utilizzare SnapCenter per eliminare qualsiasi sistema di archiviazione inutilizzato.

*Informazioni su questo compito*

È possibile eliminare le connessioni di archiviazione per un singolo utente o per un gruppo.  Se si appartiene a uno o più gruppi con autorizzazione per lo stesso sistema di archiviazione, il nome del sistema di archiviazione viene visualizzato più volte nell'elenco delle connessioni di archiviazione, una volta per ciascun gruppo con autorizzazione per il sistema di archiviazione.


IMPORTANT: Quando si elimina un sistema di archiviazione, tutte le operazioni eseguite su tale sistema di archiviazione falliranno.

*Passi*

. Nel riquadro di navigazione a sinistra, fare clic su *Sistemi di archiviazione*.
. Nella pagina Sistemi di archiviazione, dal menu a discesa *Tipo*, selezionare * ONTAP SVM* o * ONTAP Cluster*.
. Nella pagina Connessioni di archiviazione, seleziona la casella di controllo accanto all'SVM o al cluster che desideri eliminare.
+

NOTE: Non è possibile selezionare l'SVM che fa parte di un cluster.

. Fare clic su *Elimina*.
. Nella pagina Elimina impostazioni di connessione al sistema di archiviazione, fare clic su *OK*.
+

NOTE: Se un SVM viene eliminato dal cluster ONTAP tramite l'interfaccia utente grafica ONTAP , nell'interfaccia utente grafica SnapCenter fare clic su *Riscopri* per aggiornare l'elenco SVM.





== Supporto API REST

Per impostazione predefinita, tutte le connessioni dei sistemi ASA, AFF o FAS a ONTAP passeranno tramite ZAPI.  L'API REST può essere abilitata per versioni specifiche ONTAP .

SnapCenter sfrutta le API REST per eseguire tutte le operazioni sui sistemi ASA r2, che non supportano le ZAPI.

È possibile modificare le chiavi di configurazione nei seguenti file di configurazione:

* IsRestEnabledForStorageConnection
+
Il valore predefinito è falso.

* MinOntapVersionToUseREST
+
Il valore predefinito è 9.13.1.



.Abilita la connessione tramite REST API
. Impostare IsRestEnabledForStorageConnection su true.
. Aggiungere la chiave in SMCoreServiceHost.dll.config e SnapDriveService.dll.config sia sul server che sugli host plug-in di Windows.
+
_<aggiungi chiave="IsRestEnabledForStorageConnection" valore="true" />_



.Limita la connessione tramite REST API a una versione specifica di ONTAP
. Impostare il parametro di configurazione MinOntapVersionToUseREST su true.
. Aggiungere la chiave in SMCoreServiceHost.dll.config e SnapDriveService.dll.config sia sul server che sugli host plug-in di Windows.
+
_<aggiungi chiave="MinOntapVersionToUseREST" valore="9.13.1" />_

. Riavviare il servizio per SmCore sul server e il servizio plug-in e SnapDrive sulla macchina plug-in.

