---
permalink: protect-postgresql/configure-gMSA-on-windows-server-2012-or-later.html 
sidebar: sidebar 
keywords:  
summary: 'Windows Server 2016 o versioni successive consente di creare un account di servizio gestito di gruppo \(gMSA\) che fornisce la gestione automatizzata delle password degli account di servizio da un account di dominio gestito.' 
---
= Configurare gMSA su Windows Server 2016 o versioni successive
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Windows Server 2016 o versioni successive consente di creare un account di servizio gestito di gruppo (gMSA) che fornisce la gestione automatizzata delle password degli account di servizio da un account di dominio gestito.

.Prima di iniziare
* Dovresti avere un controller di dominio Windows Server 2016 o versione successiva.
* Dovresti avere un host Windows Server 2016 o versione successiva, che sia membro del dominio.


.Passi
. Crea una chiave radice KDS per generare password univoche per ogni oggetto nel tuo gMSA.
. Per ogni dominio, eseguire il seguente comando dal controller di dominio Windows: Add-KDSRootKey -EffectiveImmediately
. Crea e configura il tuo gMSA:
+
.. Crea un account di gruppo utenti nel seguente formato:
+
 domainName\accountName$
.. Aggiungere oggetti computer al gruppo.
.. Utilizzare il gruppo utenti appena creato per creare il gMSA.
+
Per esempio,

+
 New-ADServiceAccount -name <ServiceAccountName> -DNSHostName <fqdn> -PrincipalsAllowedToRetrieveManagedPassword <group> -ServicePrincipalNames <SPN1,SPN2,…>
.. Correre `Get-ADServiceAccount` comando per verificare l'account di servizio.


. Configurare gMSA sui tuoi host:
+
.. Abilitare il modulo Active Directory per Windows PowerShell sull'host in cui si desidera utilizzare l'account gMSA.
+
Per fare ciò, eseguire il seguente comando da PowerShell:

+
[listing]
----
PS C:\> Get-WindowsFeature AD-Domain-Services

Display Name                           Name                Install State
------------                           ----                -------------
[ ] Active Directory Domain Services   AD-Domain-Services  Available


PS C:\> Install-WindowsFeature AD-DOMAIN-SERVICES

Success Restart Needed Exit Code      Feature Result
------- -------------- ---------      --------------
True    No             Success        {Active Directory Domain Services, Active ...
WARNING: Windows automatic updating is not enabled. To ensure that your newly-installed role or feature is
automatically updated, turn on Windows Update.
----
.. Riavvia il tuo host.
.. Installa gMSA sul tuo host eseguendo il seguente comando dal prompt dei comandi di PowerShell: `Install-AdServiceAccount <gMSA>`
.. Verifica il tuo account gMSA eseguendo il seguente comando: `Test-AdServiceAccount <gMSA>`


. Assegnare i privilegi amministrativi al gMSA configurato sull'host.
. Aggiungere l'host Windows specificando l'account gMSA configurato nel server SnapCenter .
+
SnapCenter Server installerà i plug-in selezionati sull'host e il gMSA specificato verrà utilizzato come account di accesso al servizio durante l'installazione del plug-in.


