---
permalink: protect-postgresql/host-requirements-to-install-snapcenter-plug-in-package-for-windows-postgresql.html 
sidebar: sidebar 
keywords: postgresql 
summary: Prima di installare il pacchetto di plug-in SnapCenter per Windows, è necessario acquisire familiarità con alcuni requisiti di base di spazio e dimensioni del sistema host. 
---
= Requisiti host per installare il pacchetto plug-in SnapCenter per Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di installare il pacchetto di plug-in SnapCenter per Windows, è necessario acquisire familiarità con alcuni requisiti di base di spazio e dimensioni del sistema host.

|===
| Articolo | Requisiti 


 a| 
Sistemi operativi
 a| 
Microsoft Windows

Per le informazioni più recenti sulle versioni supportate, vedere https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT["Strumento matrice di interoperabilità NetApp"^] .



 a| 
RAM minima per il plug-in SnapCenter sull'host
 a| 
1 GB



 a| 
Spazio minimo di installazione e registro per il plug-in SnapCenter sull'host
 a| 
5 GB


NOTE: È necessario allocare spazio su disco sufficiente e monitorare il consumo di spazio di archiviazione da parte della cartella dei registri.  Lo spazio di registro richiesto varia a seconda del numero di entità da proteggere e della frequenza delle operazioni di protezione dei dati.  Se non c'è spazio sufficiente sul disco, i registri per le operazioni eseguite di recente non verranno creati.



 a| 
Pacchetti software richiesti
 a| 
* Pacchetto di hosting ASP.NET Core Runtime 8.0.12 (e tutte le patch 8.0.x successive)
* PowerShell Core 7.4.2


Per le informazioni più recenti sulle versioni supportate, vedere https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT["Strumento matrice di interoperabilità NetApp"^] .

Per informazioni specifiche sulla risoluzione dei problemi di .NET, vedere https://kb.netapp.com/mgmt/SnapCenter/SnapCenter_upgrade_or_install_fails_with_This_KB_is_not_related_to_the_OS["L'aggiornamento o l'installazione SnapCenter non riesce nei sistemi legacy che non dispongono di connettività Internet."]

|===