---
permalink: protect-postgresql/set-up-credentials-for-snapcenter-plug-in-for-postgresql.html 
sidebar: sidebar 
keywords: credentials, SnapCenter Plug-in for postgresql 
summary: 'SnapCenter utilizza le credenziali per autenticare gli utenti per le operazioni SnapCenter .  È necessario creare credenziali per l"installazione dei plug-in SnapCenter e credenziali aggiuntive per eseguire operazioni di protezione dei dati su cluster o file system Windows.' 
---
= Imposta le credenziali per il plug-in SnapCenter per PostgreSQL
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter utilizza le credenziali per autenticare gli utenti per le operazioni SnapCenter .  È necessario creare credenziali per l'installazione dei plug-in SnapCenter e credenziali aggiuntive per eseguire operazioni di protezione dei dati su cluster o file system Windows.

.Informazioni su questo compito
* Host Linux
+
È necessario impostare le credenziali per installare i plug-in sugli host Linux.

+
Per installare e avviare il processo del plug-in, è necessario impostare le credenziali per l'utente root o per un utente non root dotato di privilegi sudo.

+
|===


| *Procedura consigliata:* Sebbene sia consentito creare credenziali per Linux dopo aver distribuito gli host e installato i plug-in, la procedura consigliata è quella di creare le credenziali dopo aver aggiunto le SVM, prima di distribuire gli host e installare i plug-in. 
|===
* Host Windows
+
Prima di installare i plug-in è necessario impostare le credenziali di Windows.

+
È necessario impostare le credenziali con privilegi di amministratore, inclusi i diritti di amministratore sull'host remoto.



Se si impostano le credenziali per singoli gruppi di risorse e il nome utente non dispone di privilegi di amministratore completi, è necessario assegnare al nome utente almeno i privilegi di gruppo di risorse e di backup.

.Passi
. Nel riquadro di navigazione a sinistra, fare clic su *Impostazioni*.
. Nella pagina Impostazioni, fare clic su *Credenziali*.
. Fare clic su *Nuovo*.
. Nella pagina Credenziali, specificare le informazioni richieste per la configurazione delle credenziali:
+
|===
| Per questo campo... | Fai questo... 


 a| 
Nome della credenziale
 a| 
Inserisci un nome per le credenziali.



 a| 
Nome utente
 a| 
Immettere il nome utente e la password da utilizzare per l'autenticazione.

** Amministratore di dominio o qualsiasi membro del gruppo di amministratori
+
Specificare l'amministratore di dominio o un membro del gruppo di amministratori sul sistema su cui si sta installando il plug-in SnapCenter . I formati validi per il campo Nome utente sono:

+
*** _NetBIOS\NomeUtente_
*** _FQDN dominio\Nome utente_


** Amministratore locale (solo per gruppi di lavoro)
+
Per i sistemi che appartengono a un gruppo di lavoro, specificare l'amministratore locale predefinito sul sistema su cui si sta installando il plug-in SnapCenter . È possibile specificare un account utente locale appartenente al gruppo degli amministratori locali se l'account utente dispone di privilegi elevati o se la funzionalità di controllo degli accessi utente è disabilitata sul sistema host.  Il formato valido per il campo Nome utente è: _UserName_

+
Non utilizzare virgolette doppie (") o apici inversi (`) nelle password.  Non dovresti usare insieme i simboli minore (<) e punto esclamativo (!) nelle password.  Ad esempio, lessthan<!10, lessthan10<!, backtick`12.





 a| 
Password
 a| 
Inserisci la password utilizzata per l'autenticazione.



 a| 
Modalità di autenticazione
 a| 
Seleziona la modalità di autenticazione che desideri utilizzare.



 a| 
Utilizzare i privilegi sudo
 a| 
Selezionare la casella di controllo *Usa privilegi sudo* se si stanno creando credenziali per un utente non root.


NOTE: Applicabile solo agli utenti Linux.

|===
. Fare clic su *OK*.


Dopo aver completato la configurazione delle credenziali, potresti voler assegnare la manutenzione delle credenziali a un utente o a un gruppo di utenti nella pagina Utente e accesso.
