---
permalink: protect-postgresql/snapcenter-plug-in-for-postgresql-overview.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for PostgreSQL 
summary: Il plug-in SnapCenter per PostgreSQL è un componente lato host del software NetApp SnapCenter software che consente la gestione della protezione dei dati basata sulle applicazioni dei cluster PostgreSQL.  Il plug-in per il cluster PostgreSQL automatizza il backup, il ripristino e la clonazione dei cluster PostgreSQL nel tuo ambiente SnapCenter . 
---
= Panoramica del plug-in SnapCenter per PostgreSQL
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il plug-in SnapCenter per cluster PostgreSQL è un componente lato host del software NetApp SnapCenter software che consente la gestione della protezione dei dati basata sulle applicazioni dei cluster PostgreSQL.  Il plug-in per il cluster PostgreSQL automatizza il backup, il ripristino e la clonazione dei cluster PostgreSQL nel tuo ambiente SnapCenter .

SnapCenter supporta configurazioni PostgreSQL a cluster singolo e multi-cluster.  È possibile utilizzare il plug-in per i cluster PostgreSQL sia in ambienti Linux che Windows.  Negli ambienti Windows, PostgreSQL sarà supportato come risorsa manuale.

Una volta installato il plug-in per il cluster PostgreSQL, è possibile utilizzare SnapCenter con la tecnologia NetApp SnapMirror per creare copie mirror dei set di backup su un altro volume.  È inoltre possibile utilizzare il plug-in con la tecnologia NetApp SnapVault per eseguire la replicazione del backup da disco a disco per la conformità agli standard.

Il plug-in SnapCenter per PostgreSQL supporta NFS e SAN su layout di archiviazione ONTAP e Azure NetApp File.

Sono supportati i layout di archiviazione virtuale VMDK, vVol e RDM.
