---
permalink: install/concept_svm_connections_and_credentials.html 
sidebar: sidebar 
keywords: storage, connection, credentials 
summary: Prima di eseguire operazioni di protezione dei dati, è necessario configurare le connessioni di archiviazione e aggiungere le credenziali che verranno utilizzate da SnapCenter Server e dai plug-in SnapCenter . 
---
= Connessioni di archiviazione e credenziali
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di eseguire operazioni di protezione dei dati, è necessario configurare le connessioni di archiviazione e aggiungere le credenziali che verranno utilizzate da SnapCenter Server e dai plug-in SnapCenter .



== Connessioni di archiviazione

Le connessioni di archiviazione consentono al server SnapCenter e ai plug-in SnapCenter di accedere all'archiviazione ONTAP .  L'impostazione di queste connessioni comporta anche la configurazione delle funzionalità AutoSupport ed Event Management System (EMS).



== Credenziali

* Amministratore di dominio o qualsiasi membro del gruppo di amministratori
+
Specificare l'amministratore di dominio o un membro del gruppo di amministratori sul sistema su cui si sta installando il plug-in SnapCenter . I formati validi per il campo Nome utente sono:

+
** _NetBIOS\NomeUtente_
** _FQDN dominio\Nome utente_
** _NomeUtente@upn_


* Amministratore locale (solo per gruppi di lavoro)
+
Per i sistemi che appartengono a un gruppo di lavoro, specificare l'amministratore locale predefinito sul sistema su cui si sta installando il plug-in SnapCenter . È possibile specificare un account utente locale appartenente al gruppo degli amministratori locali se l'account utente dispone di privilegi elevati o se la funzionalità di controllo degli accessi utente è disabilitata sul sistema host.

+
Il formato valido per il campo Nome utente è: _UserName_

* Credenziali per singoli gruppi di risorse
+
Se si impostano le credenziali per singoli gruppi di risorse e il nome utente non dispone di privilegi di amministratore completi, è necessario assegnare al nome utente almeno i privilegi di gruppo di risorse e di backup.


