---
permalink: install/configure_two_way_ssl_linux.html 
sidebar: sidebar 
keywords: security,two-way ssl,configure two-way ssl, linux host 
summary: 'È necessario configurare la comunicazione SSL bidirezionale per proteggere la comunicazione reciproca tra SnapCenter Server sull"host Linux e i plug-in.' 
---
= Configurare la comunicazione SSL bidirezionale sull'host Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario configurare la comunicazione SSL bidirezionale per proteggere la comunicazione reciproca tra SnapCenter Server sull'host Linux e i plug-in.

.Prima di iniziare
* Dovresti aver configurato il certificato CA per l'host Linux.
* È necessario abilitare la comunicazione SSL bidirezionale su tutti gli host del plug-in e sul server SnapCenter .


.Passi
. Copia *certificate.pem* in _/etc/pki/ca-trust/source/anchors/_.
. Aggiungi i certificati all'elenco di attendibilità del tuo host Linux.
+
** `cp root-ca.pem /etc/pki/ca-trust/source/anchors/`
** `cp certificate.pem /etc/pki/ca-trust/source/anchors/`
** `update-ca-trust extract`


. Verificare se i certificati sono stati aggiunti all'elenco di attendibilità.
`trust list | grep "<CN of your certificate>"`
. Aggiornare *ssl_certificate* e *ssl_certificate_key* nel file *nginx* SnapCenter e riavviare.
+
** `vim /etc/nginx/conf.d/snapcenter.conf`
** `systemctl restart nginx`


. Aggiorna il collegamento all'interfaccia utente grafica di SnapCenter Server.
. Aggiornare i valori delle seguenti chiavi in ​​* SnapManager.Web.UI.dll.config* situato in _ /<percorso di installazione>/ NetApp/snapcenter/SnapManagerWeb_ e *SMCoreServiceHost.dll.config* situato in _/<percorso di installazione>/ NetApp/snapcenter/SMCore_.
+
** <add key="SERVICE_CERTIFICATE_PATH" value="<percorso del certificato.pfx>" />
** <add key="SERVICE_CERTIFICATE_PASSWORD" value="<password>"/>


. Riavviare i seguenti servizi.
+
** `systemctl restart smcore.service`
** `systemctl restart snapmanagerweb.service`


. Verificare che il certificato sia collegato alla porta web SnapManager .
`openssl s_client -connect localhost:8146 -brief`
. Verificare che il certificato sia collegato alla porta smcore.
`openssl s_client -connect localhost:8145 -brief`
. Gestisci la password per l'archivio chiavi e l'alias SPL.
+
.. Recupera la password predefinita del keystore SPL assegnata alla chiave *SPL_KEYSTORE_PASS* nel file delle proprietà SPL.
.. Cambia la password del keystore.
`keytool -storepasswd -keystore keystore.jks`
.. Cambia la password per tutti gli alias delle voci della chiave privata.
`keytool -keypasswd -alias "<alias_name>" -keystore keystore.jks`
.. Aggiornare la stessa password per la chiave *SPL_KEYSTORE_PASS* in _spl.properties_.
.. Riavviare il servizio.


. Sull'host Linux del plug-in, aggiungere i certificati radice e intermedi nel keystore del plug-in SPL.
+
** `keytool -import -trustcacerts -alias <any preferred alias name> -file <path of root-ca.pem> -keystore <path of keystore.jks mentioned in spl.properties file>`
** `keytool -importkeystore -srckeystore <path of certificate.pfx> -srcstoretype pkcs12 -destkeystore <path of keystore.jks mentioned in spl.properties file> -deststoretype JKS`
+
... Controllare le voci in keystore.jks.
`keytool -list -v -keystore <path to keystore.jks>`
... Se necessario, rinominare qualsiasi alias.
`keytool -changealias -alias "old-alias" -destalias "new-alias" -keypass keypass -keystore </path/to/keystore> -storepass storepas`




. Aggiornare il valore di *SPL_CERTIFICATE_ALIAS* nel file _spl.properties_ con l'alias di *certificate.pfx* memorizzato in _keystore.jks_ e riavviare il servizio SPL: `systemctl restart spl`
. Verificare che il certificato sia collegato alla porta smcore.
`openssl s_client -connect localhost:8145 -brief`

