---
permalink: install/install_snapcenter_server_linux.html 
sidebar: sidebar 
keywords: install, snapcenter software, install, linux host 
summary: 'È possibile installare SnapCenter Server sull"host Linux.' 
---
= Installa SnapCenter Server sull'host Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eseguire il file eseguibile di installazione di SnapCenter Server per installare SnapCenter Server.

.Prima di iniziare
* Se si desidera installare SnapCenter Server utilizzando un utente non root che non dispone di privilegi sufficienti per installare SnapCenter, ottenere il file di checksum sudoers dal sito di supporto NetApp .  Dovresti usare un file di checksum appropriato in base alla versione di Linux.
* Se il pacchetto sudo non è disponibile in SUSE Linux, installarlo per evitare errori di autenticazione.
* Per SUSE Linux, configurare il nome host per evitare errori di installazione.
* Controlla lo stato sicuro di Linux eseguendo il comando `sestatus` .  Se lo stato _SELinux_ è "abilitato" e la _modalità corrente_ è "enforcing", procedere come segue:
+
** Eseguire il comando: `sudo semanage port -a -t http_port_t -p tcp <WEBAPP_EXTERNAL_PORT_>`
+
Il valore predefinito di _WEBAPP_EXTERNAL_PORT_ è 8146

** Se il firewall blocca la porta, eseguire `sudo firewall-cmd --add-port <WEBAPP_EXTERNAL_PORT_>/tcp`
+
Il valore predefinito di _WEBAPP_EXTERNAL_PORT_ è 8146

** Esegui i seguenti comandi dalla directory in cui hai i permessi di lettura e scrittura:
+
*** `sudo ausearch -c 'nginx' --raw | audit2allow -M my-nginx`
+
Se il comando restituisce "niente da fare", eseguire nuovamente il comando dopo aver installato SnapCenter Server.

*** Se il comando crea _my-nginx.pp_, eseguire il comando per rendere attivo il pacchetto di policy: `sudo semodule -i my-nginx.pp`


** Il percorso utilizzato per la directory PID di MySQL è _/var/opt/mysqld_.  Eseguire i seguenti comandi per impostare le autorizzazioni per l'installazione di MySQL.
+
*** `mkdir /var/opt/mysqld`
*** `sudo semanage fcontext -a -t mysqld_var_run_t "/var/opt/mysqld(/.*)?"`
*** `sudo restorecon -Rv /var/opt/mysqld`


** Il percorso utilizzato per la directory dei dati MySQL è _/INSTALL_DIR/ NetApp/snapcenter/SnapManagerWeb/Repository/MySQL/_.  Eseguire i seguenti comandi per impostare le autorizzazioni per la directory dei dati MySQL.
+
*** `mkdir -p /INSTALL_DIR/NetApp/snapcenter/SnapManagerWeb/Repository/MySQL`
*** `sudo semanage fcontext -a -t mysqld_db_t "/INSTALL_DIR/NetApp/snapcenter/SnapManagerWeb/Repository/MySQL(/.*)?"`
*** `sudo restorecon -Rv /INSTALL_DIR/NetApp/snapcenter/SnapManagerWeb/Repository/MySQL`






.Informazioni su questo compito
* Quando SnapCenter Server viene installato sull'host Linux, vengono installati servizi di terze parti come MySQL, RabbitMq, Errlang.  Non dovresti disinstallarli.
* Il server SnapCenter installato sull'host Linux non supporta:
+
** Alta disponibilità
** Plug-in di Windows
** Active Directory (supporta solo gli utenti locali, sia root che non root con credenziali)
** Autenticazione basata su chiave per accedere a SnapCenter


* Durante l'installazione del runtime .NET, se l'installazione non riesce a risolvere le dipendenze della libreria _libicu_, installare _libicu_ eseguendo il comando: `yum install -y libicu`
* Se l'installazione di SnapCenter Server non riesce a causa della non disponibilità di _Perl_, installare _Perl_ eseguendo il comando: `yum install -y perl`


.Passi
. Scarica quanto segue da https://mysupport.netapp.com/site/products/all/details/snapcenter/downloads-tab["Sito di supporto NetApp"^] nella directory _/home_.
+
** Pacchetto di installazione di SnapCenter Server - *snapcenter-linux-server-(el8/el9/sles15).bin*
** File della chiave pubblica - *snapcenter_public_key.pub*
** File di firma rispettivo - *snapcenter-linux-server-(el8/el9/sles15).bin.sig*


. Convalidare il file della firma.
`$openssl dgst -sha256 -verify snapcenter_public_key.pub -signature <path to signature file> <path to bin file>`
. Per l'installazione da parte di utenti non root, aggiungere il contenuto visudo specificato in *snapcenter_server_checksum_(el8/el9/sles15).txt* disponibile insieme al programma di installazione .bin.
. Assegnare l'autorizzazione di esecuzione per il programma di installazione .bin.
`chmod +x snapcenter-linux-server-(el8/el9/sles15).bin`
. Eseguire una delle azioni per installare SnapCenter Server.
+
|===
| Se vuoi esibirti... | Fai questo... 


 a| 
Installazione interattiva
 a| 
`./snapcenter-linux-server-(el8/el9/sles15).bin`

Ti verrà chiesto di inserire i seguenti dettagli:

** Porta esterna dell'applicazione web utilizzata per accedere a SnapCenter Server al di fuori dell'host Linux.  Il valore predefinito è 8146.
** L'utente di SnapCenter Server che installerà SnapCenter Server.
** La directory di installazione in cui verranno installati i pacchetti.




 a| 
Installazione non interattiva
 a| 
`sudo ./snapcenter-linux-server-(el8/el9/sles15).bin -i silent -DWEBAPP_EXTERNAL_PORT=<port> -DWEBAPP_INTERNAL_PORT=<port> -DSMCORE_PORT=<port> -DSCHEDULER_PORT=<port>  -DSNAPCENTER_SERVER_USER=<user> -DUSER_INSTALL_DIR=<dir> -DINSTALL_LOG_NAME=<filename>`

Esempio: sudo ./snapcenter_linux_server.bin -i silent -DWEBAPP_EXTERNAL_PORT=8146 -DSNAPCENTER_SERVER_USER=root -DUSER_INSTALL_DIR=/opt -DINSTALL_LOG_NAME=InstallerLog.log

I registri verranno archiviati in _/var/opt/snapcenter/logs_.

Parametri da passare per l'installazione di SnapCenter Server:

** DWEBAPP_EXTERNAL_PORT: porta esterna dell'applicazione Web utilizzata per accedere a SnapCenter Server al di fuori dell'host Linux.  Il valore predefinito è 8146.
** DWEBAPP_INTERNAL_PORT: porta interna della Webapp utilizzata per accedere a SnapCenter Server nell'host Linux.  Il valore predefinito è 8147.
** DSMCORE_PORT: porta SMCore su cui sono in esecuzione i servizi smcore.  Il valore predefinito è 8145.
** DSCHEDULER_PORT: Porta dello scheduler su cui sono in esecuzione i servizi dello scheduler.  Il valore predefinito è 8154.
** DSNAPCENTER_SERVER_USER: utente di SnapCenter Server che installerà SnapCenter Server.  Per _DSNAPCENTER_SERVER_USER_, l'impostazione predefinita è l'utente che esegue il programma di installazione.
** DUSER_INSTALL_DIR: Directory di installazione in cui verranno installati i pacchetti.  Per _DUSER_INSTALL_DIR_, la directory di installazione predefinita è _/opt_.
** DINSTALL_LOG_NAME: Nome del file di registro in cui verranno archiviati i registri di installazione.  Questo è un parametro facoltativo e se specificato non verrà visualizzato alcun registro sulla console. Se non si specifica questo parametro, i registri verranno visualizzati sulla console e archiviati anche nel file di registro predefinito.
** DSELINUX: se lo _stato SELinux_ è "abilitato", la _modalità corrente_ è "enforcing" e sono stati eseguiti i comandi menzionati nella sezione Prima di iniziare, è necessario specificare questo parametro e assegnare il valore 1.  Il valore predefinito è 0.
** DUPGRADE: Il valore predefinito è 0.  Specificare questo parametro e il suo valore come un numero intero diverso da 0 per aggiornare SnapCenter Server.


|===


.Cosa succederà ora?
* Se lo stato _SELinux_ è "abilitato" e la _modalità corrente_ è "enforcing", il servizio *nginx* non riesce ad avviarsi.  Dovresti eseguire i seguenti comandi:
+
.. Vai alla directory home.
.. Eseguire il comando: `journalctl -x|grep nginx` .
.. Se la porta interna della Webapp (8147) non è autorizzata all'ascolto, eseguire i seguenti comandi:
+
*** `ausearch -c 'nginx' --raw | audit2allow -M my-nginx`
*** `semodule -i my-nginx.pp`


.. Correre `setsebool -P httpd_can_network_connect on`






== Funzionalità abilitate sull'host Linux durante l'installazione

SnapCenter Server installa i seguenti pacchetti software che possono aiutare nella risoluzione dei problemi e nella manutenzione del sistema host.

* Rabbitmq
* Erlang

