---
permalink: install/reference_provision_storage_using_powershell_cmdlets.html 
sidebar: sidebar 
keywords: Provision storage, snapcenter 
summary: 'Se non si desidera utilizzare l"interfaccia utente grafica SnapCenter per eseguire attività di provisioning host e recupero spazio, è possibile utilizzare i cmdlet di PowerShell forniti dal plug-in SnapCenter per Microsoft Windows.  È possibile utilizzare i cmdlet direttamente oppure aggiungerli agli script.' 
---
= Fornire l'archiviazione utilizzando i cmdlet di PowerShell
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se non si desidera utilizzare l'interfaccia utente grafica SnapCenter per eseguire attività di provisioning host e recupero spazio, è possibile utilizzare i cmdlet di PowerShell.  È possibile utilizzare i cmdlet direttamente oppure aggiungerli agli script.

Se si eseguono i cmdlet su un host plug-in remoto, è necessario eseguire il cmdlet SnapCenter Open-SMConnection per aprire una connessione al server SnapCenter .

Le informazioni relative ai parametri che possono essere utilizzati con il cmdlet e le relative descrizioni possono essere ottenute eseguendo _Get-Help command_name_. In alternativa, puoi anche fare riferimento a https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["Guida di riferimento ai cmdlet del software SnapCenter"^] .

Se i cmdlet di SnapCenter PowerShell non funzionano correttamente a causa della rimozione di SnapDrive per Windows dal server, fare riferimento a https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/SnapCenter_cmdlets_broken_when_SnapDrive_for_Windows_is_uninstalled["I cmdlet SnapCenter non funzionano quando SnapDrive per Windows viene disinstallato"^] .
