---
permalink: install/task_enable_two_way_ssl.html 
sidebar: sidebar 
keywords: security,disable two-way SSL,enable two-way SSL, windows host 
summary: 'È possibile abilitare la comunicazione SSL bidirezionale per proteggere la comunicazione reciproca tra SnapCenter Server sull"host Windows e i plug-in utilizzando i comandi di PowerShell.' 
---
= Abilita la comunicazione SSL bidirezionale sull'host Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile abilitare la comunicazione SSL bidirezionale per proteggere la comunicazione reciproca tra SnapCenter Server sull'host Windows e i plug-in utilizzando i comandi di PowerShell.

*Prima di iniziare*

Eseguire prima i comandi per tutti i plug-in e per l'agente SMCore e poi per il server.

*Passi*

. Per abilitare la comunicazione SSL bidirezionale, eseguire i seguenti comandi sul server SnapCenter per i plug-in, il server e per ciascuno degli agenti per i quali è richiesta la comunicazione SSL bidirezionale.
+
`> Set-SmConfigSettings -Agent -configSettings @{"EnableTwoWaySSL"="true"} -HostName <Plugin_HostName>`

+
`> Set-SmConfigSettings -Agent -configSettings @{"EnableTwoWaySSL"="true"} -HostName localhost`

+
`> Set-SmConfigSettings -Server -configSettings @{"EnableTwoWaySSL"="true"}`

. Eseguire l'operazione di riciclo del pool di applicazioni IIS SnapCenter utilizzando il seguente comando.
`> Restart-WebAppPool -Name "SnapCenter"`
. Per i plug-in di Windows, riavviare il servizio SMCore eseguendo il seguente comando PowerShell:
+
`> Restart-Service -Name SnapManagerCoreService`





== Disabilita la comunicazione SSL bidirezionale

È possibile disattivare la comunicazione SSL bidirezionale utilizzando i comandi di PowerShell.

*Informazioni su questo compito*

* Eseguire prima i comandi per tutti i plug-in e per l'agente SMCore e poi per il server.
* Quando si disabilita la comunicazione SSL bidirezionale, il certificato CA e la sua configurazione non vengono rimossi.
* Per aggiungere un nuovo host a SnapCenter Server, è necessario disattivare l'SSL bidirezionale per tutti gli host del plug-in.
* NLB e F5 non sono supportati.


*Passi*

. Per disattivare la comunicazione SSL bidirezionale, eseguire i seguenti comandi su SnapCenter Server per tutti gli host del plug-in e per l'host SnapCenter .
+
`> Set-SmConfigSettings -Agent -configSettings @{"EnableTwoWaySSL"="false"} -HostName <Agent_HostName>`

+
`> Set-SmConfigSettings -Agent -configSettings @{"EnableTwoWaySSL"="false"} -HostName localhost`

+
`> Set-SmConfigSettings -Server -configSettings @{"EnableTwoWaySSL"="false"}`

. Eseguire l'operazione di riciclo del pool di applicazioni IIS SnapCenter utilizzando il seguente comando.
`> Restart-WebAppPool -Name "SnapCenter"`
. Per i plug-in di Windows, riavviare il servizio SMCore eseguendo il seguente comando PowerShell:
+
`> Restart-Service -Name SnapManagerCoreService`


