---
permalink: install/task_configure_iis_application_pools_to_enable_active_directory_read_permissions.html 
sidebar: sidebar 
keywords: IIS application pool, active directory, enable 
summary: 'È possibile configurare Internet Information Services \(IIS\) sul server Windows per creare un account Application Pool personalizzato quando è necessario abilitare le autorizzazioni di lettura di Active Directory per SnapCenter.' 
---
= Configurare i pool di applicazioni IIS per abilitare le autorizzazioni di lettura di Active Directory
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile configurare Internet Information Services (IIS) sul server Windows per creare un account Application Pool personalizzato quando è necessario abilitare le autorizzazioni di lettura di Active Directory per SnapCenter.

*Passi*

. Aprire Gestione IIS sul server Windows in cui è installato SnapCenter .
. Nel riquadro di navigazione a sinistra, fare clic su *Pool di applicazioni*.
. Selezionare SnapCenter nell'elenco Pool di applicazioni, quindi fare clic su *Impostazioni avanzate* nel riquadro Azioni.
. Selezionare Identità, quindi fare clic su *...* per modificare l'identità del pool di applicazioni SnapCenter .
. Nel campo Account personalizzato, immettere il nome di un account utente di dominio o di un amministratore di dominio con autorizzazione di lettura di Active Directory.
. Fare clic su OK.
+
L'account personalizzato sostituisce l'account ApplicationPoolIdentity integrato per il pool di applicazioni SnapCenter .


