---
permalink: install/task_configure_CA_certificate_with_snapcenter_site.html 
sidebar: sidebar 
keywords: SnapCenter, configure, CA certificate 
summary: 'È necessario configurare il certificato CA con il sito SnapCenter sull"host Windows.' 
---
= Configurare il certificato CA con il sito SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario configurare il certificato CA con il sito SnapCenter sull'host Windows.

*Passi*

. Aprire Gestione IIS sul server Windows in cui è installato SnapCenter .
. Nel riquadro di navigazione a sinistra, fare clic su *Connessioni*.
. Espandi il nome del server e *Siti*.
. Seleziona il sito web SnapCenter su cui desideri installare il certificato SSL.
. Vai su *Azioni* > *Modifica sito*, fai clic su *Associazioni*.
. Nella pagina Binding, seleziona *binding per https*.
. Fare clic su *Modifica*.
. Dall'elenco a discesa Certificato SSL, seleziona il Certificato SSL importato di recente.
. Fare clic su *OK*.
+

NOTE: Il sito SnapCenter Scheduler (porta predefinita: 8154, HTTPS) è configurato con certificato autofirmato.  Questa porta comunica all'interno dell'host del server SnapCenter e non è obbligatorio configurarla con un certificato CA.  Tuttavia, se l'ambiente richiede l'utilizzo di un certificato CA, ripetere i passaggi da 5 a 9 utilizzando il sito SnapCenter Scheduler.




NOTE: Se il certificato CA distribuito di recente non è elencato nel menu a discesa, verificare se il certificato CA è associato alla chiave privata.


IMPORTANT: Assicurarsi che il certificato venga aggiunto utilizzando il seguente percorso: *Console Root > Certificati – Computer locale > Autorità di certificazione radice attendibili > Certificati*.
