---
permalink: install/task_install_the_snapcenter_server_using_the_install_wizard.html 
sidebar: sidebar 
keywords: install, snapcenter software, install wizard, features enabled 
summary: È possibile eseguire il file eseguibile di installazione di SnapCenter Server per installare SnapCenter Server. 
---
= Installa SnapCenter Server sull'host Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eseguire il file eseguibile di installazione di SnapCenter Server per installare SnapCenter Server.

Facoltativamente, è possibile eseguire diverse procedure di installazione e configurazione utilizzando i cmdlet di PowerShell.  Dovresti utilizzare PowerShell 7.4.2 o versione successiva.


NOTE: L'installazione silenziosa di SnapCenter Server dalla riga di comando non è supportata.

.Prima di iniziare
* L'host del server SnapCenter deve essere aggiornato con gli aggiornamenti di Windows e non deve esserci alcun riavvio del sistema in sospeso.
* Dovresti assicurarti che MySQL Server non sia installato sull'host in cui intendi installare SnapCenter Server.
* Avresti dovuto abilitare il debug di Windows Installer.
+
Per informazioni sull'abilitazione, consultare il sito Web Microsoft https://support.microsoft.com/kb/223300["Registrazione del programma di installazione di Windows"^] .

+

NOTE: Non installare SnapCenter Server su un host che dispone di Microsoft Exchange Server, Active Directory o Domain Name Server.



.Passi
. Scarica il pacchetto di installazione di SnapCenter Server da https://mysupport.netapp.com/site/products/all/details/snapcenter/downloads-tab["Sito di supporto NetApp"^] .
. Avviare l'installazione di SnapCenter Server facendo doppio clic sul file .exe scaricato.
+
Dopo aver avviato l'installazione, vengono eseguiti tutti i controlli preliminari e, se i requisiti minimi non vengono soddisfatti, vengono visualizzati messaggi di errore o di avviso appropriati.

+
È possibile ignorare i messaggi di avviso e procedere con l'installazione; tuttavia, gli errori dovrebbero essere corretti.

. Rivedere i valori precompilati richiesti per l'installazione di SnapCenter Server e modificarli se necessario.
+
Non è necessario specificare la password per il database del repository di MySQL Server.  Durante l'installazione SnapCenter Server la password viene generata automaticamente.

+

NOTE: Il carattere speciale "`%`" is not supported in the custom path for the repository database. If you include "` %`" nel percorso, l'installazione fallisce.

. Fare clic su *Installa ora*.
+
Se sono stati specificati valori non validi, verranno visualizzati i messaggi di errore appropriati.  Dovresti reinserire i valori e poi avviare l'installazione.

+

NOTE: Facendo clic sul pulsante *Annulla*, il passaggio in esecuzione verrà completato e verrà avviata l'operazione di rollback.  Il server SnapCenter verrà completamente rimosso dall'host.

+
Tuttavia, se si fa clic su *Annulla* quando sono in corso le operazioni "Riavvio del sito di SnapCenter Server" o "In attesa dell'avvio di SnapCenter Server", l'installazione procederà senza annullare l'operazione.

+
I file di registro vengono sempre elencati (dal più vecchio) nella cartella %temp% dell'utente amministratore.  Se si desidera reindirizzare le posizioni dei registri, avviare l'installazione di SnapCenter Server dal prompt dei comandi eseguendo:``C:\installer_location\installer_name.exe /log"C:\"``





== Funzionalità abilitate sull'host Windows durante l'installazione

Il programma di installazione di SnapCenter Server abilita le funzionalità e i ruoli di Windows sull'host Windows durante l'installazione.  Potrebbero essere utili per la risoluzione dei problemi e la manutenzione del sistema host.

|===
| Categoria | Caratteristica 


 a| 
Server Web
 a| 
* Servizi di informazione Internet
* Servizi del World Wide Web
* Funzionalità HTTP comuni
+
** Documento predefinito
** Esplorazione delle directory
** Errori HTTP
** Reindirizzamento HTTP
** Contenuto statico
** Pubblicazione WebDAV


* Salute e diagnostica
+
** Registrazione personalizzata
** Registrazione HTTP
** Strumenti di registrazione
** Monitor delle richieste
** Tracciamento


* Caratteristiche delle prestazioni
+
** Compressione dei contenuti statici


* Sicurezza
+
** Sicurezza IP
** Autenticazione di base
** Supporto centralizzato per certificati SSL
** Autenticazione del mapping del certificato client
** Autenticazione del mapping dei certificati client IIS
** Restrizioni IP e dominio
** Filtraggio delle richieste
** Autorizzazione URL
** Autenticazione di Windows


* Funzionalità di sviluppo delle applicazioni
+
** Estensibilità .NET 4.5
** Inizializzazione dell'applicazione
** Pacchetto di hosting ASP.NET Core Runtime 8.0.12 (e tutte le patch 8.0.x successive)
** Inclusioni lato server
** Protocollo WebSocket


* Strumenti di gestione
+
** Console di gestione IIS






 a| 
Script e strumenti di gestione IIS
 a| 
* Servizio di gestione IIS
* Strumenti di gestione web




 a| 
+.NET Framework 8.0.12 Funzionalità+
 a| 
* Pacchetto di hosting ASP.NET Core Runtime 8.0.12 (e tutte le patch 8.0.x successive)
* Attivazione HTTP di Windows Communication Foundation (WCF)45
+
** Attivazione TCP
** Attivazione HTTP




Per informazioni specifiche sulla risoluzione dei problemi di .NET, vedere https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/SnapCenter_upgrade_or_install_fails_with_%22This_KB_is_not_related_to_the_OS%22["L'aggiornamento o l'installazione SnapCenter non riesce per i sistemi legacy che non dispongono di connettività Internet"^] .



 a| 
Servizio di attivazione dei processi di Windows
 a| 
Modello di processo



 a| 
API di configurazione
 a| 
Tutto

|===