---
permalink: install/task_reclaim_space_on_the_storage_system.html 
sidebar: sidebar 
keywords: space, storage system, reclaim 
summary: 'Sebbene NTFS tenga traccia dello spazio disponibile su una LUN quando i file vengono eliminati o modificati, non segnala le nuove informazioni al sistema di archiviazione.  È possibile eseguire il cmdlet PowerShell per il recupero dello spazio sull"host Plug-in per Windows per garantire che i blocchi appena liberati vengano contrassegnati come disponibili nell"archiviazione.' 
---
= Recuperare spazio sul sistema di archiviazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sebbene NTFS tenga traccia dello spazio disponibile su una LUN quando i file vengono eliminati o modificati, non segnala le nuove informazioni al sistema di archiviazione.  È possibile eseguire il cmdlet PowerShell per il recupero dello spazio sull'host Plug-in per Windows per garantire che i blocchi appena liberati vengano contrassegnati come disponibili nell'archiviazione.

Se si esegue il cmdlet su un host plug-in remoto, è necessario aver eseguito il cmdlet SnapCenterOpen-SMConnection per aprire una connessione al server SnapCenter .

.Prima di iniziare
* Prima di eseguire un'operazione di ripristino, è necessario assicurarsi che il processo di recupero dello spazio sia stato completato.
* Se il LUN è condiviso dagli host in un cluster di failover di Windows Server, è necessario eseguire il recupero dello spazio sull'host proprietario del gruppo di cluster.
* Per prestazioni di archiviazione ottimali, è opportuno effettuare il recupero dello spazio il più spesso possibile.
+
È necessario assicurarsi che l'intero file system NTFS sia stato scansionato.



*Informazioni su questo compito*

* Il recupero dello spazio è un'operazione che richiede molto tempo e impegna molta CPU, quindi in genere è meglio eseguirla quando l'utilizzo del sistema di archiviazione e dell'host Windows è basso.
* Il recupero dello spazio recupera quasi tutto lo spazio disponibile, ma non il 100%.
* Non eseguire la deframmentazione del disco contemporaneamente al recupero dello spazio.
+
Ciò potrebbe rallentare il processo di bonifica.



*Fare un passo*

Dal prompt dei comandi di PowerShell del server applicativo, immettere il seguente comando:

`Invoke-SdHostVolumeSpaceReclaim -Path drive_path`

drive_path è il percorso dell'unità mappato al LUN.
