---
permalink: protect-scu/task_determine_whether_unix_file_systems_are_available_for_backup.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for UNIX file systems, discovery,file systems, UNIX, Unix file systems 
summary: 'Dopo aver installato il plug-in per i file system Unix, i file system sull"host vengono automaticamente rilevati e visualizzati nella pagina Risorse.' 
---
= Scopri i file system UNIX disponibili per il backup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver installato il plug-in, tutti i file system presenti su quell'host vengono automaticamente rilevati e visualizzati nella pagina Risorse.  È possibile aggiungere questi file system ai gruppi di risorse per eseguire operazioni di protezione dei dati.

.Prima di iniziare
* È necessario aver completato attività quali l'installazione di SnapCenter Server, l'aggiunta di host e la creazione di connessioni al sistema di archiviazione.
* Se i file system risiedono su un disco di macchina virtuale (VMDK) o su un mapping di dispositivi raw (RDM), è necessario distribuire il SnapCenter Plug-in for VMware vSphere e registrare il plug-in con SnapCenter.
+
Per ulteriori informazioni, vedere  https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_deploy_snapcenter_plug-in_for_vmware_vsphere.html["Distribuisci il SnapCenter Plug-in for VMware vSphere"^] .



.Passi
. Nel riquadro di navigazione a sinistra, fare clic su *Risorse*, quindi selezionare il plug-in appropriato dall'elenco.
. Nella pagina Risorse, seleziona *Percorso* dall'elenco Visualizza.
. Fare clic su *Aggiorna risorse*.
+
I file system vengono visualizzati insieme a informazioni quali tipo, nome host, gruppi di risorse e policy associati e stato.


