---
permalink: protect-db2/create-backup-policies-for-ibm-db2.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for IBM Db2 
summary: Prima di utilizzare SnapCenter per eseguire il backup delle risorse del database IBM Db2, è necessario creare una policy di backup per la risorsa o il gruppo di risorse di cui si desidera eseguire il backup.  Una policy di backup è un insieme di regole che regolano il modo in cui si gestiscono, si pianificano e si conservano i backup. 
---
= Creare policy di backup per IBM Db2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di utilizzare SnapCenter per eseguire il backup delle risorse IBM Db2, è necessario creare una policy di backup per la risorsa o il gruppo di risorse di cui si desidera eseguire il backup.  Una policy di backup è un insieme di regole che regolano il modo in cui si gestiscono, si pianificano e si conservano i backup.

.Prima di iniziare
* Devi aver definito la tua strategia di backup.
+
Per maggiori dettagli, consultare le informazioni sulla definizione di una strategia di protezione dei dati per i database IBM Db2.

* È necessario prepararsi alla protezione dei dati completando attività quali l'installazione di SnapCenter, l'aggiunta di host, la configurazione delle connessioni al sistema di archiviazione e l'aggiunta di risorse.
* Se si stanno replicando snapshot su un mirror o un vault, l'amministratore SnapCenter deve aver assegnato le SVM sia per il volume di origine che per quello di destinazione.
+
Inoltre, è possibile specificare le impostazioni di replica, script e applicazione nel criterio.  Queste opzioni consentono di risparmiare tempo quando si desidera riutilizzare il criterio per un altro gruppo di risorse.



.Informazioni su questo compito
* SnapLock
+
** Se è selezionata l'opzione "Conserva le copie di backup per un numero specifico di giorni", il periodo di conservazione SnapLock deve essere inferiore o uguale ai giorni di conservazione indicati.
** Specificando un periodo di blocco degli snapshot si impedisce l'eliminazione degli snapshot fino alla scadenza del periodo di conservazione.  Ciò potrebbe comportare la conservazione di un numero di snapshot maggiore rispetto al conteggio specificato nella policy.
** Per ONTAP 9.12.1 e versioni precedenti, i cloni creati dagli snapshot SnapLock Vault come parte del ripristino erediteranno il tempo di scadenza SnapLock Vault. L'amministratore dell'archiviazione deve pulire manualmente i cloni dopo la scadenza SnapLock .




.Passi
. Nel riquadro di navigazione a sinistra, fare clic su *Impostazioni*.
. Nella pagina Impostazioni, fare clic su *Criteri*.
. Fare clic su *Nuovo*.
. Nella pagina Nome, immettere il nome e i dettagli della policy.
. Nella pagina Tipo di policy, procedere come segue:
+
.. Seleziona il tipo di archiviazione.
.. Nella sezione *Impostazioni di backup personalizzate*, specificare eventuali impostazioni di backup specifiche che devono essere trasmesse al plug-in in formato chiave-valore.
+
È possibile fornire più valori-chiave da passare al plug-in.



. Nella pagina Snapshot e replica, eseguire le seguenti azioni.
+
.. Specificare la frequenza di programmazione selezionando *Su richiesta*, *Ogni ora*, *Giornaliera*, *Settimanale* o *Mensile*.
+

NOTE: È possibile specificare la pianificazione (data di inizio, data di fine e frequenza) per l'operazione di backup durante la creazione di un gruppo di risorse.  Ciò consente di creare gruppi di risorse che condividono la stessa policy e la stessa frequenza di backup, ma consente anche di assegnare pianificazioni di backup diverse a ciascuna policy.

+

NOTE: Se hai programmato per le 2:00, la pianificazione non verrà attivata durante l'ora legale (DST).

.. Nella sezione Impostazioni snapshot, eseguire le seguenti azioni:
+
|===
| Se lo desidera... | Poi... 


 a| 
Conserva un certo numero di istantanee
 a| 
Selezionare *Copie da conservare*, quindi specificare il numero di snapshot che si desidera conservare.

Se il numero di snapshot supera il numero specificato, gli snapshot vengono eliminati partendo dalle copie più vecchie.



 a| 
Conserva gli snapshot per un certo numero di giorni
 a| 
Selezionare *Conserva copie per*, quindi specificare il numero di giorni per cui si desidera conservare gli snapshot prima di eliminarli.



 a| 
Periodo di blocco della copia snapshot
 a| 
Selezionare *Periodo di blocco della copia snapshot* e specificare giorni, mesi o anni.

Il periodo di conservazione di Snaplock dovrebbe essere inferiore a 100 anni.

|===
+

IMPORTANT: Per i backup basati su copie Snapshot, è necessario impostare il conteggio di conservazione su 2 o superiore se si prevede di abilitare la replica SnapVault .  Se si imposta il conteggio di conservazione su 1, l'operazione di conservazione potrebbe non riuscire perché il primo snapshot è lo snapshot di riferimento per la relazione SnapVault finché uno snapshot più recente non viene replicato sulla destinazione.

.. Specificare l'etichetta della policy.
+
È possibile assegnare etichette SnapMirror agli snapshot primari per la replica remota, consentendo agli snapshot primari di trasferire l'operazione di replica degli snapshot da SnapCenter ai sistemi secondari ONTAP . Questa operazione può essere eseguita senza abilitare l'opzione SnapMirror o SnapVault nella pagina dei criteri.



. Nella sezione Seleziona opzioni di replicazione secondaria, seleziona una o entrambe le seguenti opzioni di replicazione secondaria:
+
|===
| Per questo campo... | Fai questo... 


 a| 
Aggiorna SnapMirror dopo aver creato una copia Snapshot locale
 a| 
Selezionare questo campo per creare copie mirror dei set di backup su un altro volume (replica SnapMirror ).

Questa opzione dovrebbe essere abilitata per la sincronizzazione attiva SnapMirror .



 a| 
Aggiorna SnapVault dopo aver creato una copia Snapshot locale
 a| 
Selezionare questa opzione per eseguire la replica del backup da disco a disco (backup SnapVault ).



 a| 
Errore nel conteggio dei tentativi
 a| 
Immettere il numero massimo di tentativi di replica consentiti prima che l'operazione venga interrotta.

|===
+

NOTE: È necessario configurare i criteri di conservazione SnapMirror in ONTAP per l'archiviazione secondaria per evitare di raggiungere il limite massimo di snapshot sull'archiviazione secondaria.

. Rivedi il riepilogo e poi clicca su *Fine*.

