---
permalink: protect-db2/how-snapcenter-plug-in-for-ibm-db2-uses-consistency-group-snapshot-copies.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for IBM Db2 
summary: 'È possibile utilizzare il plug-in per creare snapshot di gruppi di coerenza per i gruppi di risorse.  Un gruppo di coerenza è un contenitore che può ospitare più volumi, in modo da poterli gestire come un"unica entità.  Un gruppo di coerenza è costituito da snapshot simultanei di più volumi, che forniscono copie coerenti di un gruppo di volumi.' 
---
= Come il plug-in SnapCenter per IBM Db2 utilizza gli snapshot del gruppo di coerenza
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare il plug-in per creare snapshot di gruppi di coerenza per i gruppi di risorse.  Un gruppo di coerenza è un contenitore che può ospitare più volumi, in modo da poterli gestire come un'unica entità.  Un gruppo di coerenza è costituito da snapshot simultanei di più volumi, che forniscono copie coerenti di un gruppo di volumi.

È anche possibile specificare il tempo di attesa affinché il controller di archiviazione raggruppi in modo coerente gli snapshot.  Le opzioni di tempo di attesa disponibili sono *Urgente*, *Medio* e *Rilassato*.  È anche possibile abilitare o disabilitare la sincronizzazione Write Anywhere File Layout (WAFL) durante l'operazione di snapshot di gruppo coerente.  La sincronizzazione WAFL migliora le prestazioni di uno snapshot del gruppo di coerenza.
