---
permalink: protect-nsp/host_requirements_for_installing_the_snapcenter_plug_in_package_for_linux.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: 'Prima di installare il pacchetto plug-in SnapCenter per Linux, è necessario assicurarsi che l"host soddisfi i requisiti.' 
---
= Requisiti host per l'installazione del pacchetto plug-in SnapCenter per Linux e AIX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di installare il pacchetto plug-in SnapCenter per Linux o AIX, è necessario assicurarsi che l'host soddisfi i requisiti.


NOTE: Su AIX sono supportate le applicazioni di archiviazione e Oracle.

|===
| Articolo | Requisiti 


 a| 
Sistemi operativi
 a| 
* Red Hat Enterprise Linux
* Oracle Linux
* SUSE Linux Enterprise Server (SLES)




 a| 
RAM minima per il plug-in SnapCenter sull'host
 a| 
1 GB



 a| 
Spazio minimo di installazione e registro per il plug-in SnapCenter sull'host
 a| 
2 GB


NOTE: È necessario allocare spazio su disco sufficiente e monitorare il consumo di spazio di archiviazione da parte della cartella dei registri.  Lo spazio di registro richiesto varia a seconda del numero di entità da proteggere e della frequenza delle operazioni di protezione dei dati.  Se non c'è spazio sufficiente sul disco, i registri per le operazioni eseguite di recente non verranno creati.



 a| 
Pacchetti software richiesti
 a| 
Java 11 Oracle Java o OpenJDK

Se hai aggiornato JAVA alla versione più recente, devi assicurarti che l'opzione JAVA_HOME situata in /var/opt/snapcenter/spl/etc/spl.properties sia impostata sulla versione JAVA corretta e sul percorso corretto.

|===
Per le informazioni più recenti sulle versioni supportate, vedere https://imt.netapp.com/matrix/imt.jsp?components=121073;&solution=1257&isHWU&src=IMT["Strumento matrice di interoperabilità NetApp"]
