---
permalink: protect-nsp/netapp_supported_plugins_overview.html 
sidebar: sidebar 
keywords: NetApp supported plug-ins, MongoDB, ORASCPM, Oracle Applications, SAP ASE, SAP MaxDB, Storage plug-in 
summary: È possibile sviluppare plug-in supportati da NetApp per le applicazioni in uso e quindi utilizzare SnapCenter per eseguire il backup, il ripristino o la clonazione di tali applicazioni.  Analogamente ad altri plug-in SnapCenter , i plug-in supportati NetApp fungono da componenti lato host del software NetApp SnapCenter , consentendo la protezione dei dati e la gestione delle risorse in base alle applicazioni. 
---
= Panoramica dei plug-in supportati da NetApp
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare i plug-in supportati da NetApp , come MongoDB, ORASCPM (Oracle Applications), SAP ASE, SAP MaxDB e il plug-in Storage per le applicazioni in uso, quindi utilizzare SnapCenter per eseguire il backup, il ripristino o la clonazione di tali applicazioni.  I plug-in supportati NetApp fungono da componenti lato host del software NetApp SnapCenter , consentendo la protezione dei dati e la gestione delle risorse in base alle applicazioni.

Quando sono installati i plug-in supportati NetApp , è possibile utilizzare SnapCenter con la tecnologia NetApp SnapMirror per creare copie mirror di set di backup su un altro volume e utilizzare la tecnologia NetApp SnapVault per eseguire la replica del backup da disco a disco.  I plug-in supportati da NetApp possono essere utilizzati sia in ambienti Windows che Linux.


NOTE: SnapCenterCLI non supporta i comandi dei plug-in supportati NetApp .

NetApp fornisce il plug-in Storage per eseguire operazioni di protezione dei dati del volume di dati sullo storage ONTAP utilizzando il framework plug-in integrato in SnapCenter.

È possibile installare i plug-in supportati da NetApp dalla pagina Aggiungi host.

link:add_hosts_and_install_plug_in_packages_on_remote_hosts.html["Aggiungere host e installare pacchetti plug-in su host remoti."^]


NOTE: La politica di supporto SnapCenter coprirà il supporto per il framework dei plug-in, il motore principale e le API associate.  Il supporto non coprirà il codice sorgente del plug-in e gli script associati creati sul framework del plug-in.
