---
permalink: protect-nsp/prerequisites_to_adding_hosts_and_installing_netapp_supported_plugins.html 
sidebar: sidebar 
keywords: credentials 
summary: Prima di aggiungere un host e installare i pacchetti plug-in, è necessario soddisfare tutti i requisiti.  I plug-in supportati da NetApp possono essere utilizzati in ambienti Windows, Linux o AIX. 
---
= Prerequisiti per l'aggiunta di host e l'installazione del pacchetto Plug-in per Windows, Linux o AIX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di aggiungere un host e installare i pacchetti plug-in, è necessario soddisfare tutti i requisiti.  I plug-in supportati NetApp sono supportati negli ambienti Windows, Linux e AIX.


NOTE: Su AIX sono supportate le applicazioni di archiviazione e Oracle.

* È necessario aver installato Java 11 sul proprio host Linux, Windows o AIX.
+

NOTE: IBM Java non è supportato su host Windows e Linux.

* Quando si installa un plug-in su un host Windows, se si specifica una credenziale non integrata o se l'utente appartiene a un utente di un gruppo di lavoro locale, è necessario disabilitare UAC sull'host.
* I plug-in supportati da NetApp , come MongoDB, ORASCPM, Oracle Applications, SAP ASE, SAP MaxDB e il plug-in Storage, devono essere disponibili sull'host client da cui viene eseguita l'operazione di aggiunta host.




== Generale

Se si utilizza iSCSI, il servizio iSCSI deve essere in esecuzione.



== Host Windows

* È necessario disporre di un utente di dominio con privilegi di amministratore locale e autorizzazioni di accesso locale sull'host remoto.
* Se si gestiscono i nodi del cluster in SnapCenter, è necessario disporre di un utente con privilegi amministrativi per tutti i nodi del cluster.
* È necessario selezionare manualmente il plug-in SnapCenter per Microsoft Windows.
+
http://www.java.com/en/download/manual.jsp["Scarica JAVA per Windows"]





== Host Linux e AIX


NOTE: Su AIX sono supportate le applicazioni di archiviazione e Oracle.

* È necessario aver abilitato la connessione SSH basata su password per l'utente root o non root.
* Devi aver installato Java 11 sul tuo host Linux.
+
Se si utilizza Windows Server 2019 o Windows Server 2016 per l'host SnapCenter Server, è necessario installare Java 11.  Lo strumento Interoperability Matrix (IMT) contiene le informazioni più recenti sui requisiti.

+
http://www.java.com/en/download/manual.jsp["Scarica JAVA per Linux"]

+
https://developer.ibm.com/languages/java/semeru-runtimes/downloads/?license=IBM["Scarica JAVA per AIX"]

+
https://imt.netapp.com/matrix/imt.jsp?components=117018;&solution=1259&isHWU&src=IMT["Strumento matrice di interoperabilità NetApp"]

* È necessario configurare i privilegi sudo per l'utente non root per consentire l'accesso a più percorsi.  Aggiungere le seguenti righe al file /etc/sudoers utilizzando l'utilità Linux visudo.
+

NOTE: Assicurati di utilizzare la versione 1.8.7 o successiva di Sudo.

+
[listing, subs="+quotes"]
----
Cmnd_Alias HPPLCMD = sha224:checksum_value== /home/_LINUX_USER_/.sc_netapp/snapcenter_linux_host_plugin.bin, /opt/NetApp/snapcenter/spl/installation/plugins/uninstall, /opt/NetApp/snapcenter/spl/bin/spl, /opt/NetApp/snapcenter/scc/bin/scc
Cmnd_Alias PRECHECKCMD = sha224:checksum_value== /home/_LINUX_USER_/.sc_netapp/Linux_Prechecks.sh
Cmnd_Alias CONFIGCHECKCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/plugins/scu/scucore/configurationcheck/Config_Check.sh
Cmnd_Alias SCCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/bin/sc_command_executor
Cmnd_Alias SCCCMDEXECUTOR =checksum_value== /opt/NetApp/snapcenter/scc/bin/sccCommandExecutor
_LINUX_USER_ ALL=(ALL) NOPASSWD:SETENV: HPPLCMD, PRECHECKCMD, CONFIGCHECKCMD, SCCCMDEXECUTOR, SCCMD
Defaults: _LINUX_USER_ env_keep += "IATEMPDIR"
Defaults: _LINUX_USER_ env_keep += "JAVA_HOME"
Defaults: _LINUX_USER_ !visiblepw
Defaults: _LINUX_USER_ !requiretty
----
+
_LINUX_USER_ è il nome dell'utente non root che hai creato.

+
È possibile ottenere il valore _checksum_value_ dal file *sc_unix_plugins_checksum.txt*, che si trova in:

+
** _C:\ProgramData\ NetApp\ SnapCenter\Package Repository\sc_unix_plugins_checksum.txt_ se SnapCenter Server è installato sull'host Windows.
** _/opt/ NetApp/snapcenter/SnapManagerWeb/Repository/sc_unix_plugins_checksum.txt_ se SnapCenter Server è installato sull'host Linux.
+

IMPORTANT: L'esempio deve essere utilizzato solo come riferimento per la creazione dei propri dati.







== Requisiti dell'host AIX

Prima di installare il pacchetto di plug-in SnapCenter per AIX, è necessario assicurarsi che l'host soddisfi i requisiti.


NOTE: Su AIX sono supportate le applicazioni di archiviazione e Oracle.


NOTE: Il plug-in SnapCenter per UNIX, che fa parte del pacchetto di plug-in SnapCenter per AIX, non supporta gruppi di volumi simultanei.

|===
| Articolo | Requisiti 


 a| 
Sistemi operativi
 a| 
AIX 7.1 o successivo



 a| 
RAM minima per il plug-in SnapCenter sull'host
 a| 
4 GB



 a| 
Spazio minimo di installazione e registro per il plug-in SnapCenter sull'host
 a| 
2 GB


NOTE: È necessario allocare spazio su disco sufficiente e monitorare il consumo di spazio di archiviazione da parte della cartella dei registri.  Lo spazio di registro richiesto varia a seconda del numero di entità da proteggere e della frequenza delle operazioni di protezione dei dati.  Se non c'è spazio sufficiente sul disco, i registri per le operazioni eseguite di recente non verranno creati.



 a| 
Pacchetti software richiesti
 a| 
Java 11 IBM Java

Se hai aggiornato JAVA alla versione più recente, devi assicurarti che l'opzione JAVA_HOME situata in /var/opt/snapcenter/spl/etc/spl.properties sia impostata sulla versione JAVA corretta e sul percorso corretto.

|===
Per le informazioni più recenti sulle versioni supportate, vedere https://imt.netapp.com/matrix/imt.jsp?components=121073;&solution=1257&isHWU&src=IMT["Strumento matrice di interoperabilità NetApp"^] .



=== Configurare i privilegi sudo per gli utenti non root per l'host AIX

SnapCenter 4.4 e versioni successive consentono a un utente non root di installare il pacchetto di plug-in SnapCenter per AIX e di avviare il processo di plug-in.  I processi del plug-in verranno eseguiti come utente non root effettivo.  È necessario configurare i privilegi sudo per l'utente non root per consentire l'accesso a diversi percorsi.

*Cosa ti servirà*

* Sudo versione 1.8.7 o successiva.
* Modificare il file _/etc/ssh/sshd_config_ per configurare gli algoritmi del codice di autenticazione dei messaggi: MAC hmac-sha2-256 e MAC hmac-sha2-512.
+
Riavviare il servizio sshd dopo aver aggiornato il file di configurazione.

+
Esempio:

+
[listing]
----
#Port 22
#AddressFamily any
#ListenAddress 0.0.0.0
#ListenAddress ::
#Legacy changes
#KexAlgorithms diffie-hellman-group1-sha1
#Ciphers aes128-cbc
#The default requires explicit activation of protocol
Protocol 2
HostKey/etc/ssh/ssh_host_rsa_key
MACs hmac-sha2-256
----


*Informazioni su questo compito*

È necessario configurare i privilegi sudo per l'utente non root per consentire l'accesso ai seguenti percorsi:

* /home/_AIX_USER_/.sc_netapp/snapcenter_aix_host_plugin.bsx
* /custom_location/ NetApp/snapcenter/spl/installation/plugins/uninstall
* /posizione_personalizzata/ NetApp/snapcenter/spl/bin/spl


*Passi*

. Accedere all'host AIX su cui si desidera installare il pacchetto plug-in SnapCenter per AIX.
. Aggiungere le seguenti righe al file /etc/sudoers utilizzando l'utilità Linux visudo.
+
[listing, subs="+quotes"]
----
Cmnd_Alias HPPACMD = sha224:checksum_value== /home/_AIX_USER_/.sc_netapp/snapcenter_aix_host_plugin.bsx,
/opt/NetApp/snapcenter/spl/installation/plugins/uninstall, /opt/NetApp/snapcenter/spl/bin/spl
Cmnd_Alias PRECHECKCMD = sha224:checksum_value== /home/_AIX_USER_/.sc_netapp/AIX_Prechecks.sh
Cmnd_Alias CONFIGCHECKCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/plugins/scu/scucore/configurationcheck/Config_Check.sh
Cmnd_Alias SCCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/bin/sc_command_executor
_AIX_USER_ ALL=(ALL) NOPASSWD:SETENV: HPPACMD, PRECHECKCMD, CONFIGCHECKCMD, SCCMD
Defaults: _LINUX_USER_ env_keep += "IATEMPDIR"
Defaults: _LINUX_USER_ env_keep += "JAVA_HOME"
Defaults: _AIX_USER_ !visiblepw
Defaults: _AIX_USER_ !requiretty
----
+

NOTE: Se si dispone di una configurazione RAC, insieme agli altri comandi consentiti, è necessario aggiungere quanto segue al file /etc/sudoers: '/<crs_home>/bin/olsnodes'



È possibile ottenere il valore di _crs_home_ dal file _/etc/oracle/olr.loc_.

_AIX_USER_ è il nome dell'utente non root che hai creato.

È possibile ottenere il valore _checksum_value_ dal file *sc_unix_plugins_checksum.txt*, che si trova in:

* _C:\ProgramData\ NetApp\ SnapCenter\Package Repository\sc_unix_plugins_checksum.txt_ se SnapCenter Server è installato sull'host Windows.
* _/opt/ NetApp/snapcenter/SnapManagerWeb/Repository/sc_unix_plugins_checksum.txt_ se SnapCenter Server è installato sull'host Linux.



IMPORTANT: L'esempio deve essere utilizzato solo come riferimento per la creazione dei propri dati.
