---
permalink: protect-nsp/types_of_restore_strategies_supported_for_manually_added_netapp_supported_plugins_resources.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: È necessario definire una strategia prima di poter eseguire correttamente le operazioni di ripristino utilizzando SnapCenter.  Esistono due tipi di strategie di ripristino per le risorse plug-in supportate NetApp aggiunte manualmente.  Non è possibile recuperare manualmente le risorse plug-in supportate da NetApp . 
---
= Tipi di strategie di ripristino supportate per le risorse plug-in supportate NetApp aggiunte manualmente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario definire una strategia prima di poter eseguire correttamente le operazioni di ripristino utilizzando SnapCenter.  Esistono due tipi di strategie di ripristino per le risorse plug-in supportate NetApp aggiunte manualmente.


NOTE: Non è possibile recuperare manualmente le risorse plug-in supportate da NetApp .



== Ripristino completo delle risorse

* Ripristina tutti i volumi, qtree e LUN di una risorsa



NOTE: Se la risorsa contiene volumi o qtree, gli snapshot acquisiti dopo lo snapshot selezionato per il ripristino su tali volumi o qtree vengono eliminati e non possono essere recuperati.  Inoltre, se sugli stessi volumi o qtree è ospitata un'altra risorsa, anche tale risorsa verrà eliminata.



== Ripristino a livello di file

* Ripristina i file da volumi, qtree o directory
* Ripristina solo i LUN selezionati

