---
permalink: get-started/concept_authentication_methods_for_your_credentials.html 
sidebar: sidebar 
keywords: credentials, authentication, untrusted domain, local workgroup, windows authentication, SQL Server authentication, Linux authentication, AIX authentication, Oracle database authentication, Oracle ASM authentication, RMAN catalog authentication 
summary: 'Le credenziali utilizzano metodi di autenticazione diversi a seconda dell"applicazione o dell"ambiente.  Le credenziali autenticano gli utenti in modo che possano eseguire le operazioni SnapCenter .  È necessario creare un set di credenziali per l"installazione dei plug-in e un altro set per le operazioni di protezione dei dati.' 
---
= Metodi di autenticazione per le credenziali SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le credenziali utilizzano metodi di autenticazione diversi a seconda dell'applicazione o dell'ambiente.  Le credenziali autenticano gli utenti in modo che possano eseguire le operazioni SnapCenter .  Dovresti creare un set di credenziali per l'installazione dei plug-in e un altro per le operazioni di protezione dei dati.



== Autenticazione di Windows

Il metodo di autenticazione di Windows esegue l'autenticazione tramite Active Directory.  Per l'autenticazione di Windows, Active Directory è configurato all'esterno di SnapCenter.  SnapCenter esegue l'autenticazione senza alcuna configurazione aggiuntiva.  Per aggiungere host, installare pacchetti plug-in e pianificare attività, è necessario disporre delle credenziali Windows.



== Autenticazione di dominio non attendibile

SnapCenter consente agli utenti e ai gruppi appartenenti a domini non attendibili di creare credenziali Windows.  Per far sì che l'autenticazione vada a buon fine, è necessario registrare i domini non attendibili con SnapCenter.



== Autenticazione del gruppo di lavoro locale

SnapCenter consente la creazione di credenziali Windows con utenti e gruppi di lavoro locali.  L'autenticazione di Windows per gli utenti e i gruppi di lavoro locali non avviene durante la creazione delle credenziali di Windows, ma viene posticipata finché non vengono eseguite la registrazione dell'host e altre operazioni sull'host.



== Autenticazione di SQL Server

Il metodo di autenticazione SQL esegue l'autenticazione su un'istanza di SQL Server.  Ciò significa che un'istanza di SQL Server deve essere individuata in SnapCenter.  Pertanto, prima di aggiungere una credenziale SQL, è necessario aggiungere un host, installare pacchetti plug-in e aggiornare le risorse.  Per eseguire operazioni quali la pianificazione su SQL Server o l'individuazione di risorse è necessaria l'autenticazione di SQL Server.



== Autenticazione Linux

Il metodo di autenticazione Linux esegue l'autenticazione su un host Linux.  È necessaria l'autenticazione Linux durante la fase iniziale di aggiunta dell'host Linux e di installazione remota del pacchetto plug-in SnapCenter per Linux dalla GUI SnapCenter .



== Autenticazione AIX

Il metodo di autenticazione AIX esegue l'autenticazione su un host AIX.  È necessaria l'autenticazione AIX durante la fase iniziale di aggiunta dell'host AIX e di installazione remota del pacchetto plug-in SnapCenter per AIX dalla GUI SnapCenter .



== Autenticazione del database Oracle

Il metodo di autenticazione del database Oracle esegue l'autenticazione su un database Oracle.  Per eseguire operazioni sul database Oracle è necessaria l'autenticazione del database Oracle se l'autenticazione del sistema operativo (SO) è disabilitata sull'host del database.  Pertanto, prima di aggiungere una credenziale del database Oracle, è necessario creare un utente Oracle nel database Oracle con privilegi sysdba.



== Autenticazione Oracle ASM

Il metodo di autenticazione Oracle ASM esegue l'autenticazione su un'istanza di Oracle Automatic Storage Management (ASM).  L'autenticazione Oracle ASM è obbligatoria se è necessario accedere a un'istanza Oracle ASM e l'autenticazione del sistema operativo è disabilitata sull'host del database.  Prima di aggiungere una credenziale Oracle ASM, creare un utente Oracle con privilegi di sistema nell'istanza ASM.



== Autenticazione del catalogo RMAN

Il metodo di autenticazione del catalogo RMAN esegue l'autenticazione in base al database del catalogo Oracle Recovery Manager (RMAN).  Se hai configurato un meccanismo di catalogo esterno e registrato il tuo database nel database di catalogo, devi aggiungere l'autenticazione del catalogo RMAN.
