---
permalink: uninstall/reference_prerequisites_for_removing_a_host.html 
sidebar: sidebar 
keywords: uninstall, prerequisites, plug-in, plug-in packages 
summary: È possibile rimuovere un host se non si desidera più utilizzare SnapCenter per gestire i relativi processi di protezione dei dati.  Ad esempio, potresti voler rimuovere un host se non contiene più dati che devono essere protetti.  Prima di rimuovere un host da SnapCenter Server, è necessario eseguire le attività preliminari. 
---
= Prerequisiti per la rimozione di un host
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile rimuovere gli host e disinstallare singoli plug-in o pacchetti di plug-in utilizzando l'interfaccia utente grafica SnapCenter .  È anche possibile disinstallare singoli plug-in o pacchetti di plug-in su host remoti utilizzando l'interfaccia della riga di comando (CLI) sull'host SnapCenter Server oppure utilizzando l'opzione *Disinstalla un programma* di Windows localmente su qualsiasi host.

Prima di rimuovere un host da SnapCenter Server, è necessario completare i prerequisiti.

* Dovresti effettuare l'accesso come amministratore.
* È necessario assicurarsi che i processi di individuazione non siano in esecuzione sull'host.
* Dovresti ricevere un ruolo con le autorizzazioni necessarie per rimuovere tutti gli oggetti associati all'host.  In caso contrario, l'operazione di rimozione fallisce.
* È necessario confermare l'impronta digitale se la chiave SSH è stata modificata dopo aver aggiunto l'host a SnapCenter.
* È necessario confermare l'impronta digitale se l'host SnapCenter è stato aggiornato a una versione successiva di SnapCenter ma l'host del plug-in esegue ancora una versione precedente del plug-in.




== Prerequisiti per rimuovere un host utilizzando il controllo degli accessi basato sui ruoli

* Dovresti aver effettuato l'accesso utilizzando un ruolo RBAC che dispone delle autorizzazioni di lettura, eliminazione host, installazione, disinstallazione di plug-in ed eliminazione oggetti.
+
Gli oggetti possono essere cloni, backup, gruppi di risorse, sistemi di archiviazione e così via.

* Avresti dovuto aggiungere l'utente RBAC al ruolo RBAC.
* È necessario assegnare l'utente RBAC all'host, al plug-in, alle credenziali, ai gruppi di risorse e al sistema di archiviazione (per i cloni) che si desidera eliminare.
* Dovresti aver effettuato l'accesso a SnapCenter come utente RBAC.




== Prerequisiti per rimuovere un host con cloni creati dall'operazione del ciclo di vita del clone

* Avresti dovuto creare processi di clonazione utilizzando la gestione del ciclo di vita dei cloni per i database SQL.
* Dovresti aver creato un ruolo RBAC con autorizzazioni di lettura ed eliminazione clone, lettura ed eliminazione risorse, lettura ed eliminazione gruppi risorse, lettura ed eliminazione storage, lettura ed eliminazione provisioning, montaggio, smontaggio, installazione e disinstallazione plug-in, lettura ed eliminazione host.
* Avresti dovuto assegnare all'utente RBAC il ruolo RBAC.
* Dovresti aver assegnato l'utente RBAC all'host, al plug-in SnapCenter per Microsoft SQL Server, alle credenziali, al gruppo di risorse del ciclo di vita del clone e al sistema di archiviazione.
* Dovresti aver effettuato l'accesso a SnapCenter come utente RBAC.


Per informazioni sulla disinstallazione del SnapCenter Plug-in for VMware vSphere, vedere https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_remove_plugin.html["Rimuovere il SnapCenter Plug-in for VMware vSphere"^] .
