---
permalink: protect-mysql/snapcenter-plug-in-for-mysql-overview.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for MySQL 
summary: Il plug-in SnapCenter per MySQL è un componente lato host del software NetApp SnapCenter software che consente la gestione della protezione dei dati basata sulle applicazioni dei database MySQL.  Il plug-in per il database MySQL automatizza il backup, il ripristino e la clonazione dei database MySQL nel tuo ambiente SnapCenter . 
---
= Panoramica del plug-in SnapCenter per MySQL
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il plug-in SnapCenter per il database MySQL è un componente lato host del software NetApp SnapCenter software che consente la gestione della protezione dei dati basata sulle applicazioni dei database MySQL.  Il plug-in per il database MySQL automatizza il backup, il ripristino e la clonazione dei database MySQL nel tuo ambiente SnapCenter .

SnapCenter supporta configurazioni MySQL a istanza singola.  È possibile utilizzare il plug-in per il database MySQL sia in ambienti Linux che Windows.  Negli ambienti Windows, MySQL sarà supportato come risorsa manuale.

Una volta installato il plug-in per il database MySQL, è possibile utilizzare SnapCenter con la tecnologia NetApp SnapMirror per creare copie mirror dei set di backup su un altro volume.  È inoltre possibile utilizzare il plug-in con la tecnologia NetApp SnapVault per eseguire la replicazione del backup da disco a disco per la conformità agli standard.

Il plug-in SnapCenter per MySQL supporta NFS e SAN su layout di archiviazione ONTAP e Azure NetApp File.

Sono supportati i layout di archiviazione virtuale VMDK, vVol e RDM.

I collegamenti simbolici non sono supportati.
